locationtech/geotrellis

- spark/src/main/scala/geotrellis/spark/SpaceTimeKey.scala
- spark/src/main/scala/geotrellis/spark/io/AttributeCatalog.scala
- spark/src/main/scala/geotrellis/spark/io/Catalog.scala
- spark/src/main/scala/geotrellis/spark/io/accumulo/AccumuloAttributeCatalog.scala
- spark/src/main/scala/geotrellis/spark/io/accumulo/AccumuloCatalog.scala
- spark/src/main/scala/geotrellis/spark/io/accumulo/AccumuloDriver.scala
- spark/src/main/scala/geotrellis/spark/io/accumulo/AccumuloMetaDataCatalog.scala
- spark/src/main/scala/geotrellis/spark/io/accumulo/RasterAccumuloDriver.scala
- spark/src/main/scala/geotrellis/spark/io/accumulo/TimeRasterAccumuloDriver.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopAttributeCatalog.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopMetaDataCatalog.scala
- spark/src/main/scala/geotrellis/spark/service/TmsHttpService.scala
- spark/src/test/scala/geotrellis/spark/io/accumulo/AccumuloAttributeCatalogSpec.scala
- spark/src/test/scala/geotrellis/spark/io/accumulo/AccumuloCatalogSpec.scala
Created AttributeCatalog, so that any RootJsonReadable type can be read to and from the catalog by layer ID and attribute name. Still trying to figure out how to work that into the catalog infrastructure, tried out a couple API's but didn't really find something that worked yet.
Also added the ability to read a single tile out of AccumuloCatalog (this needs to be lifted up to the Catalog trait and implemented for HDFS).
> Added attribute catalog, pulling out single tile from Accumulo

- raster-test/src/test/scala/geotrellis/raster/op/global/CostDistanceWithPathsSpec.scala
- raster/src/main/scala/geotrellis/raster/op/global/CostDistance.scala
- raster/src/main/scala/geotrellis/raster/op/global/CostDistanceWithPaths.scala
- raster/src/main/scala/geotrellis/raster/op/global/GlobalMethods.scala
Adds a cost distance with shortest paths method for identifying the shortest paths from a start to a goal for the raster project.
This issue references this implementation: #954
> Adds a cost distance with shortest paths

- project/Build.scala
- project/Dependencies.scala
- spark/src/main/scala/geotrellis/spark/ingest/SpaceTimeInputKey.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopSparkContextMethods.scala
- spark/src/main/scala/geotrellis/spark/io/s3/GeoTiffS3InputFormat.scala
- spark/src/main/scala/geotrellis/spark/io/s3/S3InputFormat.scala
- spark/src/main/scala/geotrellis/spark/io/s3/S3InputSplit.scala
- spark/src/main/scala/geotrellis/spark/io/s3/S3RecordReader.scala
- spark/src/main/scala/geotrellis/spark/io/s3/TemporalGeoTiffS3InputFormat.scala
- spark/src/test/scala/geotrellis/spark/io/s3/GeoTiffS3InputFormatSpec.scala
- spark/src/test/scala/geotrellis/spark/io/s3/S3InputFormatSpec.scala
- spark/src/test/scala/geotrellis/spark/io/s3/TemporalGeoTiffS3InputFormatSpec.scala
Using AWS S3 SDK allows us to list files significantly faster than using Hadoop FileInputFormat.
This input format defines InputSplits using S3 pagination, giving a reasonable spark task size for RDDs created from this InputFormat.
Concrete implementations are added to read GeoTiffs from S3.
> S3 InputFormat

- spark/src/main/scala/geotrellis/spark/io/accumulo/BatchAccumuloInputFormat.scala
- spark/src/main/scala/geotrellis/spark/io/accumulo/MultiRangeInputSplit.scala
- spark/src/main/scala/geotrellis/spark/io/accumulo/MultiRangeRecordReader.scala
- spark/src/test/scala/geotrellis/spark/io/accumulo/BatchAccumuloInputFormatSpec.scala
This InputFormat groups the Ranges by tablet servers where they are located. The corresponding RecordReader will use BatchScanner to read them. The overall effect is to reduce the number of splits to the minimum possible and provide some parallelism in reading them. This reduces the spark overhead of processing each task.
> BatchAccumuloInputFormat

- spark/src/test/scala/geotrellis/spark/io/accumulo/BatchAccumuloInputFormatSpec.scala
Because I could not wait 5 minutes for Travis to tell me this on previous PR.
> Fix: move SparkContext reference into checked block

- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/decompression/LZWDecompression.scala
There was a bug in LZW decompression of GeoTiffs that caused an ArrayOutOfBounds exception. The file that was tripping it was way too big to include a unit test (I tried and failed at creating a small test case), but this did fix the issue.
> Check bounds on LZW decompression.

- project/Build.scala
- project/Version.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/CassandraAttributeCatalog.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/CassandraMetaDataCatalog.scala
- spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraAttributeCatalogSpec.scala
- spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraMetaDataCatalogSpec.scala
Implements CassandraAttributeCatalog and CassandraMetaDataCatalog. Also brings in required dependencies for interfacing with Cassandra.
The current test specs require a local cluster to be set up on 127.0.0.1; they will be skipped if no Cassandra cluster is up. Preferably, these tests should use mocks to eliminate dependencies on persisted tables and the developer's environment.
> Cassandra Attribute and Metadata Catalogs

- project/Version.scala
- spark/src/main/scala/geotrellis/spark/ingest/AccumuloIngestCommand.scala
- spark/src/main/scala/geotrellis/spark/ingest/AccumuloPyramidCommand.scala
- spark/src/main/scala/geotrellis/spark/ingest/HadoopIngestCommand.scala
- spark/src/main/scala/geotrellis/spark/ingest/Ingest.scala
- spark/src/main/scala/geotrellis/spark/ingest/NetCDFIngest.scala
- spark/src/main/scala/geotrellis/spark/ingest/NetCDFIngestHDFS.scala
- spark/src/main/scala/geotrellis/spark/ingest/Pyramid.scala
- spark/src/main/scala/geotrellis/spark/io/accumulo/AccumuloCatalog.scala
- spark/src/test/scala/geotrellis/spark/ingest/IngestSpec.scala
- spark/src/test/scala/geotrellis/spark/io/accumulo/AccumuloCatalogSpec.scala
- spark/src/test/scala/geotrellis/spark/io/hadoop/HadoopCatalogSpec.scala
- spark/src/test/scala/geotrellis/spark/io/s3/GeoTiffS3InputFormatSpec.scala
- spark/src/test/scala/geotrellis/spark/io/s3/TemporalGeoTiffS3InputFormatSpec.scala
This PR addresses the issue of forking collects on RDD. This happens during Ingest, when each RDD is required for saving/sink and for generating the next pyramid level. Also this is an issue during Catalog save, where the catalog needs to collect the raster histogram before saving.
In case of pyramid at most two RDDs are kept in memory at a time, the source and destination for each level, creating a rolling persistence effect.
> RDD Caching during Ingest and Catalog save

- spark/src/main/resources/reference.conf
- spark/src/main/scala/geotrellis/spark/cmd/args/CassandraArgs.scala
- spark/src/main/scala/geotrellis/spark/ingest/CassandraIngestCommand.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/CassandraInstance.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/CassandraMetaDataCatalog.scala
- spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraCatalogSpec.scala
Provides CassandraIngestCommand and moves the metadata tablename into a configuration file, similar to AccumuloInstance. Also implements zoomLevelsFor, which was needed for the gt-admin server.
Tested with climate data using the `ingest-cassandra` and `run-cassandra-server` scripts found [here](https://github.com/kyeah/gt-admin).
> CassandraIngestCommand + tweaks for CassandraInstance

- spark/src/main/scala/geotrellis/spark/io/accumulo/BatchAccumuloInputFormat.scala
TableId, not TableName is required to get a TabletLocator. Also attempt has been made to more closely follow the flow of getSplits in accumulo 1.6 branch.
> Fix: BatchAccumuloInputFormat

- project/Dependencies.scala
- spark/src/main/scala/geotrellis/spark/io/s3/RasterRDDReader.scala
- spark/src/main/scala/geotrellis/spark/io/s3/RasterRDDWriter.scala
- spark/src/main/scala/geotrellis/spark/io/s3/S3Client.scala
- spark/src/main/scala/geotrellis/spark/io/s3/S3RasterCatalog.scala
- spark/src/main/scala/geotrellis/spark/io/s3/package.scala
- spark/src/main/scala/geotrellis/spark/io/s3/spacetime/SpaceTimeRasterRDDReader.scala
- spark/src/main/scala/geotrellis/spark/io/s3/spacetime/package.scala
- spark/src/main/scala/geotrellis/spark/io/s3/spatial/SpatialRasterRDDReader.scala
- spark/src/main/scala/geotrellis/spark/io/s3/spatial/package.scala
- spark/src/main/scala/geotrellis/spark/utils/TaskUtils.scala
S3 Catalog had some issues:
- reader was not truncating/padding indexes like writer was
- some indexes were being skipped over by readKeys logic
- configuration was not being passed to the AmazonS3Client.
> Fixes to S3 catalog.

- spark/src/main/scala/geotrellis/spark/io/index/ZCurveKeyIndexMethod.scala
- spark/src/main/scala/geotrellis/spark/io/index/zcurve/ZSpaceTimeKeyIndex.scala
- spark/src/test/scala/geotrellis/spark/io/index/zcurve/ZSpaceTimeKeyIndexSpec.scala
A function `timeToGrid: DateTime => Int` have to be in a project scope, otherwise there would be `Unable to find class` error on workers, trying to read tiles stored in a custom way, but without having the definition of the exact ingest job in the result assembly.
P.S. tried to save code style, but it is possible to reduce code by using wildcards.
> ZCurve index build by pattern support

- vector-test/src/test/scala/spec/geotrellis/vector/GeometryResultSpec.scala
- vector/src/main/scala/geotrellis/vector/Results.scala
Simply adds a toGeometry method  to GeometryResult, so one could do something like:
```scala
(polygon & extent).toGeometry match {
case Some(geom) => // deal with the geometry as a geotrellis.vector.Geometry
case None => // same thing as NoResult
}
```
> Added a toGeometry method to GeometryResult

- project/Build.scala
- project/Version.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/Cassandra.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/CassandraAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/package.scala
- spark/src/test/resources/another-cassandra.yaml
- spark/src/test/scala/geotrellis/spark/OnlyIfCanRunSpark.scala
- spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraAttributeStoreSpec.scala
- spark/src/test/scala/geotrellis/spark/io/cassandra/CassandraRasterCatalogSpec.scala
- spark/src/test/scala/geotrellis/spark/io/cassandra/EmbeddedCassandraConnector.scala
- spark/src/test/scala/geotrellis/spark/io/cassandra/SharedEmbeddedCassandra.scala
Fixes #1097 
- updated spark cassandra connector and cassandra java driver versions to latest stable in Version.scala
- fixed cassandra config yaml (another-cassandra.yaml) for embedded Cassandra instance
- fixed SparkContext needing cassandra connection properties at creation in OnlyIfCanRunSpark.scala
- fixed "LayerNotFoundError expected but RuntimeError found", wasn't thrown in CassandraRasterCatalogSpec.scala tests, found Sys.error instead of throws Exception in CassandraAttributeStore.scala, replaced with LayerNotForundError from package.scala
ALL CASSANDRA UNIT TESTS COMPLETE SUCCESSFULLY
**JAVA INFO**
Seems that with (Open)JDK 7_80 CassandraRasterCatalogSpec.scala test fails occasionally with OutOfMemory / PermGenSpace, (MaxPermSize=384m come from somewhere), but with JDK 8 …
> Cassandra Unit Tests GO

- spark/src/main/scala/geotrellis/spark/io/AttributeCaching.scala
- spark/src/main/scala/geotrellis/spark/io/accumulo/AccumuloRasterCatalog.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopRasterCatalog.scala
- spark/src/main/scala/geotrellis/spark/io/s3/S3RasterCatalog.scala
- spark/src/test/scala/geotrellis/spark/io/accumulo/AccumuloRasterCatalogSpec.scala
- spark/src/test/scala/geotrellis/spark/io/hadoop/HadoopRasterCatalogSpec.scala
- spark/src/test/scala/geotrellis/spark/io/s3/S3RasterCatalogSpec.scala
To read/write a catalog Metadata, KeyBounds and KeyIndex are required. This PR adds the `AttributeCaching` trait that keeps a simple in memory cache for these attributes. The catalogs take care to read/write attribute only through the methods on this trait, keeping it locally consistent.
There are no provision to keep the cache consistent across different instances of a catalog at the moment. As a final escape hatch `.clearCache` method is provided as part of the trait.
> Catalog layer attribute caching

- spark/src/main/scala/geotrellis/spark/io/accumulo/AccumuloAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/accumulo/AccumuloRasterCatalog.scala
- spark/src/main/scala/geotrellis/spark/io/accumulo/RasterRDDWriter.scala
- spark/src/main/scala/geotrellis/spark/io/accumulo/TileReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopRasterCatalog.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/spacetime/SpaceTimeRasterRDDWriter.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/spatial/SpatialRasterRDDWriter.scala
- spark/src/main/scala/geotrellis/spark/io/package.scala
- spark/src/main/scala/geotrellis/spark/io/s3/S3AttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/s3/S3RasterCatalog.scala
- spark/src/main/scala/geotrellis/spark/io/s3/TileReader.scala
- spark/src/test/scala/geotrellis/spark/io/accumulo/AccumuloRasterCatalogSpec.scala
- spark/src/test/scala/geotrellis/spark/io/s3/S3RasterCatalogSpec.scala
This PR upgrade the use of `sys.error` in the catalog package to named exceptions that should make client code cleaner.
> Unify catalog exceptions

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/UInt16GeoTiffTileSpec.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/UInt16GeoTiffSegment.scala
UInt16GeoTIFFs were not being read correctly and needed to be converted to signed Ints. 
The added test only passes after this fix.
> Fixed UInt16GeoTiff reader bug and added a test

- spark/src/main/scala/geotrellis/spark/io/s3/S3AttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/s3/S3RasterCatalog.scala
Fixes issue with S3 catalog where using empty rootPath would result in path of "/layerName/zoom". The leading slash is interpreted as a folder with empty name by S3 browser.
> Fix s3 catalog rootpath

- buildall.sh
- engine-test/src/test/scala/geotrellis/engine/RasterSourceSpec.scala
- project/Build.scala
- project/Environment.scala
- project/Version.scala
- spark/src/test/scala/geotrellis/spark/RasterRDDBuilders.scala
Fixing travis build to generate non-zero exit code for all subproject build fails. Also bumping versions for spark and geotools.
> Travis Build and version bumps

- buildall.sh
- vector-test/src/test/scala/spec/geotrellis/vector/io/json/CrsSpec.scala
- vector-test/src/test/scala/spec/geotrellis/vector/io/json/FeatureFormatsSpec.scala
- vector/src/main/scala/geotrellis/vector/io/json/FeatureFormats.scala
- vector/src/main/scala/geotrellis/vector/io/json/GeoJson.scala
- vector/src/main/scala/geotrellis/vector/io/json/JsonFeatureCollection.scala
- vector/src/main/scala/geotrellis/vector/io/json/JsonFeatureCollectionMap.scala
- vector/src/main/scala/geotrellis/vector/io/json/package.scala
Before this, if we had the situation where we'd like to read a GeoJSON feature collection data property into a class but had no interest in ever writing it through GeoJSON, we'd have to do something like this:
```scala
case class NeighborhoodData(name: String, listName: String)
implicit object NeighborhoodDataFormat extends JsonFormat[NeighborhoodData] {
def write(obj: NeighborhoodData): JsValue = ???
def read(value: JsValue): NeighborhoodData = 
value.asJsObject.getFields("name", "listname") match {
case Seq(JsString(name), JsString(listName)) =>
NeighborhoodData(name, listName)
case _ => throw new DeserializationException("Couldn't read neighborhood data")
}
}
def fromJson(path: String): Seq[MultiPolygonFeature[String]] =
Source.fromFile(path)
.getLines
.mkString …
```
> Added JsonReader and JsonWriter for Feature[D]

- vector-test/src/test/scala/spec/geotrellis/vector/GeometryResultSpec.scala
- vector/src/main/scala/geotrellis/vector/MultiLine.scala
- vector/src/main/scala/geotrellis/vector/MultiPoint.scala
- vector/src/main/scala/geotrellis/vector/MultiPolygon.scala
- vector/src/main/scala/geotrellis/vector/Polygon.scala
- vector/src/main/scala/geotrellis/vector/Results.scala
- vector/src/main/scala/geotrellis/vector/package.scala
This adds implicits of Arrays of Point, Line, and Polygon to MultiPoint, MultiLine, and MultiPolygon.
It also adds methods on GeometryResult that aims to make extracting expected geometry types out of operation results.
> geotrellis.vector API functionality: implicits for arrays and Result conversions

- raster-test/src/test/scala/geotrellis/raster/reproject/RowTransformCheck.scala
- vector-test/src/test/scala/spec/geotrellis/vector/io/json/GeoJsonSpec.scala
- vector/src/main/scala/geotrellis/vector/Feature.scala
- vector/src/main/scala/geotrellis/vector/io/json/FeatureFormats.scala
- vector/src/main/scala/geotrellis/vector/io/json/JsonFeatureCollection.scala
- vector/src/main/scala/geotrellis/vector/io/json/JsonFeatureCollectionMap.scala
- vector/src/main/scala/geotrellis/vector/io/json/package.scala
- vector/src/main/scala/geotrellis/vector/package.scala
- vector/src/main/scala/geotrellis/vector/reproject/package.scala
This PR changes `abstract class Feature[D] { type G <: Geometry }` into `case class Feature[G <: Geometry, D](...)`. This fell out of me wanting to write a simple `mapData` method, and the current type architecture not allowing me to. This mostly affects internal code; the API should remain the same as long as users use things like `PointFeature[D]`, etc.
> Refactored Feature to include Geometry type as type param.

- spark/src/main/scala/geotrellis/spark/tiling/package.scala
This is what gdal2tiles uses, see here for an explanation: https://github.com/pramsey/gdal2tilesp/blob/master/gdal2tilesp.py#L141
> Set a more precise WebMercator world extent.

- sbt
newer version of sbt runner script to load the sbt-launcher.jar from valid typesafe repo url
(old version placed the launcher in ./lib/, and was not cached in ~/.sbt or ~/.ivy2 as one might expect), new repo URL caused failing download. New sbt runner downloads from current valid repo and seems to store/cache it in ~/.sbt/launchers/0.13.8/sbt-launch.jar 
`sbt` from https://github.com/paulp/sbt-extras/blob/master/sbt
> newer version of sbt runner script

- dev/build.sbt
- dev/src/main/scala/geotrellis/dev/RemoteClient.scala
- dev/src/main/scala/geotrellis/dev/RemoteServer.scala
- project/Dependencies.scala
This is an optional dependency to get Akka cluster metrics. It seems to no longer be available with the old org id on maven central. Dropping it now to fix the build.
> Removing sigar dependency

- macros/src/main/scala/geotrellis/macros/TypeConversionMacros.scala
- raster/src/main/scala/geotrellis/raster/resample/BilinearResample.scala
- raster/src/main/scala/geotrellis/raster/resample/CubicResample.scala
- In TypeConversionMacros, like `d2i`, there was an issue with the Expression possibly being evaluated twice. Capture the expression result in a `val` to prevent this.
- Fix to bilinear, it should round a double value instead of taking floor.
> Fixes to Bilinear, type conversion macro fix

- proj4/src/main/scala/geotrellis/proj4/CRS.scala
- raster-test/src/test/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReaderSpec.scala
- raster-test/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/GeoTiffCSParser.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/GeoKeyConstants.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/GeoKeyDirectory.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/TiffTags.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/writer/CoordinateSystemParser.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/writer/TiffTagFieldValue.scala
This commit improves support for projections when reading and writing
GeoTiffs. Before this commit, it looks as though almost all projections
were read as custom user projections, ignoring and not setting the
`ProjectedCSTypeGeoKey` properly in the process. In the suggestions for
geocoding rasters in the GeoTiff spec, if this code is set (e.g. an EPSG
code) then other parameters are unecessary.
This commit adds support for reading/writing the `ProjectedCSTypeGeoKey`
value properly to enable reading/writing projections like EPSG:3857 (web
-mercator) properly. Tests have been added for this purpose.
In the process of writing this task, I found
http://download.osgeo.org/pub/geotiff/samples/README which describes
additional GeoTiffs GeoTrellis should aim to support reading/writing
with to be …
> Add support for additional projections in geotiffs

- raster/src/main/scala/geotrellis/raster/io/geotiff/utils/ByteBufferExtensions.scala
When a tiff tag value is less than or equal to four bytes the offset (int32) of the tag metadata contains the actual value rather then the byte offset of where the value is written.
For instance a common NoData value of "0" would be encoded as count=2 offset=48
In this case we read the wrong ByteBuffer looking for the value.
> Fix Reading GeoTiff NoData tags <= 4 bytes

- project/Dependencies.scala
- spark/build.sbt
It is now published to maven central, so we can remove a resolver.
> scalaz-streams to 0.8

- project/Environment.scala
- raster/src/main/scala/geotrellis/raster/ByteArrayTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/ByteGeoTiffSegment.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/ByteGeoTiffSegmentCollection.scala
Fixes two use cases:
- ByteArrayTile.fromBytes, which used when we decompress GeoTiff into array tiles 
- NoDataByteGeoTiffSegment, which is used when reading GeoTiff segment by segment.
This also removes "& FF" on get from ByteGeoTiffArrayTile, leaving it as a signed byte container.
> GeoTiff Byte NoData handling

- engine/src/main/scala/geotrellis/engine/Cache.scala
- spark/src/main/scala/geotrellis/spark/io/Cache.scala
- spark/src/main/scala/geotrellis/spark/io/FileCache.scala
- spark/src/main/scala/geotrellis/spark/io/s3/S3LayerReader.scala
- spark/src/main/scala/geotrellis/spark/io/s3/S3RDDReader.scala
- spark/src/main/scala/geotrellis/spark/utils/cache/FileCache.scala
- spark/src/main/scala/geotrellis/spark/utils/cache/cache.scala
- spark/src/test/scala/geotrellis/spark/utils/cache/CacheSpec.scala
GeoTrellis engine has a nice set of caching functionality that is not at all used there. Caching has recently useful in spark subproject where it is used `S3LayerReader` and some client code.
This PR moves those cache implementations over, merges them with `FileCache` class and cleans up some naming issues.
> Moving Cache class hierarchy to spark sub-project

- README.md
IRC has mostly been foregone in favor of Gitter
> Remove reference to IRC

- engine/src/main/scala/geotrellis/engine/render/RenderRasterSourceMethods.scala
- raster-test/src/test/scala/geotrellis/raster/render/RenderMethodsSpec.scala
- raster/src/main/scala/geotrellis/raster/render/ColorBreaks.scala
- raster/src/main/scala/geotrellis/raster/render/ColorMap.scala
- raster/src/main/scala/geotrellis/raster/render/RenderMethods.scala
- raster/src/main/scala/geotrellis/raster/render/png/Renderer.scala
Previously we weren't allowed to color a tile of doubles with color breaks that were also doubles. For instance, if we had breaks that corresponding to the values of 0.0 - 1.0, and colors to match those breaks, we now are able to render a tile that has values 0.0 - 1.0 with those breaks.
ColorBreaks changes from being a `case class ColorBreaks(limits: Array[Int], colors: Array[Int])` to a trait, with `IntColorBreaks` and `DoubleColorBreaks` implementations. This is an API change.
> Added ability to color double tiles with double color breaks.

- spark/src/main/scala/geotrellis/spark/io/s3/S3Client.scala
S3 credentials are handled by InstanceProfileCredentialsProvider when they are expired.
If we pass the provider to AWS `AmazonS3Client` it will delegate to provider `.getCredentials` call on requests, triggering refresh logic.
Confusingly both AWS SDK and our code as `AmazonS3Client` but they follow naming convention in both packages.
> Handle S3Client IAM credential expiration

- raster-test/src/test/scala/geotrellis/raster/op/local/MaskSpec.scala
This is a small set of changes and I haven't *proven* that the problem is fixed (the true problem is probably somewhere deep inside JTS), but I've not been able to cause a failure after the change. To verify that the change had its desired effect, I ran the test loop more than a 1,000,000 times without an error (it was failing every hundred or so iterations prior to the change).
Odd as it may seem, if two corners of a rectangle are outside the hull of an outer rectangle, JTS gracefully handles the creation of an 8 sided, concave polygon. Absurdities result from attempting to do this with two triangles in which the inner has one corner outside the outer.
I'll include some images of the produced geometries to give a sense of how, exactly, they were in error:
> Build square instead of triangle for random mask test

- spark/src/main/scala/geotrellis/spark/tiling/ZoomedLayoutScheme.scala
- spark/src/test/scala/geotrellis/spark/tiling/ZoomedLayoutSchemeSpec.scala
This modifies the zoom level algorithm to include a resolution threshold, which behaves in the following way: the cell size is matched to a zoom level for which it is more resolute than, but less resolute then the resolution of the next zoom level up. If the ratio between the cell size resolution and the zoom level resolution to the difference of the resolutions of the zoom and the next level up is less than the resolution threshold, then that zoom level is returned. Otherwise the next zoom level up is returned.
> Modified ZoomedLayoutScheme zoom level algorithm.

- project/Dependencies.scala
- vector/src/main/scala/geotrellis/vector/Feature.scala
No compile problems or test failures after upgrading.  I looked over the release notes and did a quick review of geotrellis-vector and didn't see anything that needed to be updated.  I'm going to look into how the new LineDissolver in JTS compares with the LineDissolve operation in geotrellis, if the JTS version seems clearly superior it might make sense to include that change in this PR.
> Upgrade to JTS version 1.14.0

- .sbtignore
- buildall.sh
- proj4/src/main/scala/geotrellis/proj4/CRS.scala
- raster-test/build.sbt
- raster-test/src/test/scala/geotrellis/raster/reproject/ReprojectRasterExtentSpec.scala
- raster-test/src/test/scala/geotrellis/raster/reproject/ReprojectSpec.scala
- raster-test/src/test/scala/geotrellis/raster/reproject/RowTransformSpec.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/MultiBandGeoTiff.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/SingleBandGeoTiff.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/writer/TiffTagFieldValue.scala
- raster/src/main/scala/geotrellis/raster/reproject/Reproject.scala
- raster/src/main/scala/geotrellis/raster/reproject/ReprojectRasterExtent.scala
- spark/src/main/scala/geotrellis/spark/op/focal/FocalOperation.scala
- spark/src/main/scala/geotrellis/spark/tiling/MapKeyTransform.scala
This PR includes some changes to raster reprojection, mainly
- The extent for the reprojected raster uses a densified version of the extent, reducing the code from the GDAL ported method.
- There was a "bug" in how we were determining the pixel size (I say "bug" in quotes because it's just an estimate). This more closely mirrors what GDAL is doing, which is verified by some tests around reprojecting raster extents from tiles of a landsat image.
Other changes include:
- Added a `fromEpsgCode` to CRS
- Added a `MapKeyTransform` that takes a layout level
- Fixed a GeoTiff writing bug that was happening when we were writing GeoTiffs without any GeoDoubleKey tags.
Also, this PR adds an `.sbtignore` that aims to reduce the output of the build (especially in travis). This will potentially have …
> Fixes and changes to Reprojection

- raster/src/main/scala/geotrellis/raster/BitArrayTile.scala
- raster/src/main/scala/geotrellis/raster/CellType.scala
* Fixes `CellType.fromString` function (added `bool` case, useful for etl)
* Fixed `copy` function for `BitArrayTile` (it copied `BitArrayTile` to `ByteArrayTile`)
> BitType raster fixes

- spark/src/main/scala/geotrellis/spark/io/RDDFilter.scala
- spark/src/test/scala/geotrellis/spark/RDDQuerySpec.scala
A method to provide intersection queries against polygons has been added.  It does so by rasterizing the polygon into an extent fashioned to mirror the set of keys that meet the polygon.
Still Requires:
Fixes #1228
> Use Rasterizer to Find Keys Covering Polygon

- raster-test/src/test/scala/geotrellis/raster/rasterize/extent/ExtentRasterizerSpec.scala
- raster/src/main/scala/geotrellis/raster/rasterize/Rasterizer.scala
- raster/src/main/scala/geotrellis/raster/rasterize/extent/ExtentRasterizer.scala
The new functionality is relatively simple: bounds for a two-dimensional loop are constructed, and the function *f* is called on each pixel within the bounds.
The new tests include:
* Stand-alone tests of the extent rasterization functionality.
* Cross-validation between the extent rasterization and the polygon rasterization.
> Extent Rasterizer

- slick/src/main/scala/geotrellis/slick/PostGisProjectionSupport.scala
- slick/src/main/scala/geotrellis/slick/PostGisSupport.scala
- slick/src/test/scala/geotrellis/slick/Data.scala
- vector/src/main/scala/geotrellis/vector/Geometry.scala
- vector/src/main/scala/geotrellis/vector/affine/AffineTransformation.scala
- vector/src/main/scala/geotrellis/vector/io/WKB/WKB.scala
- vector/src/main/scala/geotrellis/vector/io/WKT/WKT.scala
- vector/src/main/scala/geotrellis/vector/io/WKT/package.scala
Geometry#apply includes an unsafe cast for convenience when converting general JTS Geometry instances into geotrellis.vector.Geometry.  However because the cast is done with type parameter instead of a concrete class, no check is actually performed in the apply method, and in the event of a programmer error the runtime exception may happen far from the call.  With this PR, Geometry.apply would perform the check before the converted object is returned, throwing an exception on failure.
> Check the cast in Geometry#apply for earlier failures

- raster/src/main/scala/geotrellis/raster/Raster.scala
- raster/src/main/scala/geotrellis/raster/op/zonal/summary/TileIntersection.scala
- spark/src/test/scala/geotrellis/spark/op/zonal/summary/FeatureRDDSpec.scala
- vector-test/src/test/scala/spec/geotrellis/vector/io/json/GeoJsonSpec.scala
- vector/src/main/scala/geotrellis/vector/Extent.scala
- vector/src/main/scala/geotrellis/vector/Feature.scala
- vector/src/main/scala/geotrellis/vector/package.scala
- vector/src/main/scala/geotrellis/vector/reproject/package.scala
This does have an impact throughout the codebase since some parts of the code convert tiles to features and back.  In this branch I've simply used PolygonFeature for this instead of ExtentFeature - I could also look into extending Feature to support "geometries" that are not part of the Geometry type hierarchy to avoid converting back-and-forth.
> Remove 'Extent' from the Geometry type hierarchy

- spark/src/main/scala/geotrellis/spark/SpatialKey.scala
- spark/src/main/scala/geotrellis/spark/io/index/HilbertKeyIndexMethod.scala
- spark/src/main/scala/geotrellis/spark/io/index/KeyIndex.scala
- spark/src/main/scala/geotrellis/spark/io/index/RowMajorKeyIndexMethod.scala
- spark/src/main/scala/geotrellis/spark/io/index/hilbert/HilbertSpaceTimeKeyIndex.scala
- spark/src/main/scala/geotrellis/spark/io/index/hilbert/README.md
- spark/src/test/scala/geotrellis/spark/io/PersistenceSpec.scala
- spark/src/test/scala/geotrellis/spark/io/accumulo/AccumuloSpaceTimeAlternativeSpec.scala
- spark/src/test/scala/geotrellis/spark/io/index/hilbert/HilbertSpaceTimeKeyIndexSpec.scala
- spark/src/test/scala/geotrellis/spark/testfiles/TestFiles.scala
Contains the following changes:
* The x- and y-dimensions had been transposed in the Hilbert Index creation code.  This was probably not detected earlier because the two dimensions are typically about the same size?
* The calculation of the location on the Hilbert curve corresponding to a particular key has been adjusted.
* A corner-case in the calculation of the number of bits required to represent numbers has been adjusted.
* The resolution function has been changed to take the minimum and maximum of the range as parameters, rather than the length as a single parameter.  This makes usage mistakes less likely.
https://github.com/geotrellis/geotrellis/pull/1303 ⊂ https://github.com/geotrellis/geotrellis/pull/1299
https://github.com/geotrellis/geotrellis/pull/1303 ⊂ …
> Hilbert Curve Fixes

- raster-test/src/test/scala/geotrellis/raster/histogram/StreamingHistogramSpec.scala
This *should* make a spurious failure in the `StreamingHistogramSpec` tests very unlikely.
> Make Spurious Failure Less Likely

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/ArrayMultiBandTileSpec.scala
- raster-test/src/test/scala/geotrellis/raster/io/geotiff/GeoTiffMultiBandTileSpec.scala
- raster/src/main/scala/geotrellis/raster/ArrayMultiBandTile.scala
- raster/src/main/scala/geotrellis/raster/MultiBandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffMultiBandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/UInt32GeoTiffTile.scala
Subsetted versions of the `combine` and `map` methods are provided for all `MultiBandTile` derived types.  These are "subsetted" in the sense that they allow combining (respectively mapping) over a subset of the bands of a `MultiBandTile`.
> Subsetted combine and map Methods

- util/build.sbt
This change supplies a `build.sbt` file for the `geotrellis-util` project.
> Supply build.sbt File for geotrellis-util

- spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala
- spark/src/main/scala/geotrellis/spark/RasterMetaData.scala
- spark/src/main/scala/geotrellis/spark/ingest/Ingest.scala
- spark/src/main/scala/geotrellis/spark/ingest/MultiBandIngest.scala
- spark/src/test/scala/geotrellis/spark/ingest/IngestSpec.scala
- spark/src/test/scala/geotrellis/spark/io/s3/GeoTiffS3InputFormatSpec.scala
Currently, input crs forced to be equal dest crs.
> Fixed input src in etl and ingest objects 

- spark/src/main/scala/geotrellis/spark/io/RDDFilter.scala
- spark/src/test/scala/geotrellis/spark/io/CoordinateSpaceTimeTests.scala
This filter allows an RDD to be filtered so that only items from a particular instant are retained.
> Provide an At RDD Filter

- spark/src/main/scala/geotrellis/spark/buffer/BufferTiles.scala
- spark/src/test/scala/geotrellis/spark/buffer/BufferTilesSpec.scala
These changes (attempt to) fix a bug in the `BufferTile` functionality.  That bug would cause exceptions when trying to process certain non-rectangular RDDs.
> BufferTiles Fix

- spark/src/main/scala/geotrellis/spark/KeyBounds.scala
- spark/src/main/scala/geotrellis/spark/io/RDDFilter.scala
- spark/src/main/scala/geotrellis/spark/io/filter/Implicits.scala
- spark/src/main/scala/geotrellis/spark/io/filter/RasterRDDFilterMethods.scala
- spark/src/main/scala/geotrellis/spark/package.scala
- spark/src/test/scala/geotrellis/spark/RasterRDDFilterMethodsSpec.scala
These changes add a `filterByKeyBounds` method to the `RasterRDD` type that allows the same to be filtered by one or more `KeyBounds`.
~~The `.filterByKeyBounds(...)` method returns a `BoundedRDDQuery` instead of an `RDDQuery` because the former has a `toRDD` method and the latter does not.~~
> Raster RDD Filter Methods

- benchmark/build.sbt
- build.sbt
- gdal/build.sbt
- macros/build.sbt
- project/Dependencies.scala
- project/Version.scala
- project/plugins.sbt
- raster-test/build.sbt
- raster/build.sbt
- raster/src/main/scala/geotrellis/raster/io/geotiff/compression/Predictor.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/TiffTags.scala
- scripts/cleanall.sh
- spark/build.sbt
The following dependencies have not been upgraded:
* com.typesafe.config due to incompatible byte code
* com.typesafe.slick due to use of an extension that does not support the newer version
* hadoop due to the fact that it is marked "provided"
* spark due to the fact that it is marked "provided"
* com.google.guava.guava due to the fact that it isn't clear which version to upgrade to
> Upgrade All Dependencies

- project/Dependencies.scala
- spark/build.sbt
The postgres and AWS SDK dependency bumps have been reverted.
> Revert Two Dependency Upgrades

- engine-test/build.sbt
- raster-test/build.sbt
- raster-test/src/test/scala/geotrellis/raster/regiongroup/RegionGroupSpec.scala
- raster-test/src/test/scala/geotrellis/raster/vectorize/VectorizeSpec.scala
- raster/build.sbt
- raster/src/main/scala/geotrellis/raster/package.scala
- raster/src/main/scala/geotrellis/raster/regiongroup/RegionGroup.scala
- raster/src/main/scala/geotrellis/raster/vectorize/Polygonizer.scala
- raster/src/main/scala/geotrellis/raster/vectorize/SingleBandRasterVectorizeMethods.scala
- raster/src/main/scala/geotrellis/raster/vectorize/TileVectorizeMethods.scala
- raster/src/main/scala/geotrellis/raster/vectorize/Vectorize.scala
- shapefile/build.sbt
- vector/src/main/scala/geotrellis/vector/Polygon.scala
There was a bug in situations where we were generating polygons with holes, of various values; if the linear rings that were generated for the holes of a polygon intersected, it would produce incorrect geometries. This fix unions all holes so that we are assigning unique non-intersecting linear rings to polygon holes.
/cc @owcm @kagoentzel 
Fixes #1350
Fixes #1361
> Fixed a bug in vectorization.

- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/HadoopModule.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/MultibandSpaceTimeHadoopOutput.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/TemporalMultibandGeoTiffHadoopInput.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopSparkContextMethods.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/formats/TemporalMultiBandGeoTiffInputFormat.scala
This PR adds support for hadoop temporal multiband geotiffs to spark-etl.
Changes:
* Changed the MultibandSpaceTimeHadoopOutput to use correctly use MultiBandTile instead of Tile.  
* Added new TemporalMultibandGeoTiffHadoopInput input to spark-etl
* Added new hadoopTemporalMultiBandGeoTiffRDD methods to HadoopSparkContextMethods
* Add TemporalMultiBandGeoTiffInputFormat input format.
> Support for temporal hadoop multiband geotiffs

- vector/src/main/scala/geotrellis/vector/Extent.scala
- vector/src/main/scala/geotrellis/vector/SpatialIndex.scala
As per #1249, add an overload of ``insert`` on ``SpatialIndex`` that accepts an ``Extent``.  Also while I was looking at ``SpatialIndex`` I made a couple of other changes:
* Give it a default parameter so you do not always need to choose a Measure when constructing a spatial index.
* Make ``pointsInExtentAsJavaList`` return a ``java.util.List`` rather than ``scala.collection.immutable.List``
* Add a ``traversePointsInExtent`` method that queries and returns a ``Traversable`` so the result list doesn't necessarily need to be materialized
* Reimplement ``pointsInExtent`` in terms of ``traversePointsInExtent`` so that we don't need to copy a Java List (this approach iterated over the results twice.)
> Performance/API improvements to SpatialIndex

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/GeoTiffMultiBandTileSpec.scala
- raster/src/main/scala/geotrellis/raster/ArrayMultiBandTile.scala
- raster/src/main/scala/geotrellis/raster/SimpleMultiBandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/MultiBandGeoTiff.scala
This pull request adds a `bands` (reorder) method to `MultiBandTiles`, where possible.
In https://github.com/geotrellis/geotrellis/commit/b78a1ef7b3d4ab792de19b5e4ea3f6a0bb6ecb82, a trait is added to gurantee the existence of the method where it is possible to do so.  That commit can be removed if it is not desired.
Closes #1112
> Supply MultiBandTile bands (reorder) Method

- raster/src/main/scala/geotrellis/raster/TileLayout.scala
- spark/src/main/scala/geotrellis/spark/filter/Implicits.scala
- spark/src/main/scala/geotrellis/spark/filter/SpaceTimeRasterRDDFilterMethods.scala
- spark/src/main/scala/geotrellis/spark/filter/SpaceTimeRasterToSpatialMethods.scala
- spark/src/test/scala/geotrellis/spark/filter/RasterRDDFilterMethodsSpec.scala
- spark/src/test/scala/geotrellis/spark/testfiles/TestFiles.scala
These changes equip every `RasterRDD` keyed by `SpaceTimeKey` with a `toSpatial` (formerly `filterByInstant`) method that filters out all entries not occurring at the given instant, and also projects the keys to the `SpatialKey` type.
Closes #1057
> Provide toSpatial Method

- spark/src/main/scala/geotrellis/spark/ingest/Pyramid.scala
- spark/src/main/scala/geotrellis/spark/io/kryo/KryoRegistrator.scala
Hadoop 2.6.x and 2.7.x depend on `avro 1.7.4`. We have newer `1.8.0` version and we use new, constructor function https://github.com/geotrellis/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/kryo/KryoRegistrator.scala#L212 which is available only in `avro 1.8.0`. That may cause a problem during ingest which looks like that: 
```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.avro.Schema$Field.<init>(Ljava/lang/String;Lorg/apache/avro/Schema;Ljava/lang/String;Ljava/lang/Object;)V
at geotrellis.spark.io.kryo.KryoRegistrator.registerClasses(KryoRegistrator.scala:212)
```
Due to tested compatibility we can use the old constructor.
> Fix avro field constructor compatibility

- spark/src/main/scala/geotrellis/spark/io/kryo/KryoRegistrator.scala
- spark/src/test/scala/geotrellis/spark/TestRegistrator.scala
We don't have control over the avro version, so the registration process can cause conflicts. See gitter chat below: 
pomadchin 11:37
@lossyrob you want to remove it form registration? now we have to add these lines manually on the client side? hm
lossyrob 11:42
you don’t have to add them
it just means that the schema will be encoded with a string to identify the class
which causes a little bit of bloat
for serialization
but if a client wants to solve that, then yeah the would have to register the schema themselves with Kryo
which makes sense, because it’s a client side dependency
if we don’t have control over the Avro they are using, then we shouldn’t register it
pomadchin 11:43
lossyrob 11:43
unless we explicitly state, “this is the avro version you have to use"
but then that’s a bit …
> Remove avro schema from Kryo registration.

- raster/src/main/scala/geotrellis/raster/CellType.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/UInt32GeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/UInt32GeoTiffTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReader.scala
- raster/src/main/scala/geotrellis/raster/package.scala
This PR removes references to UIntCells at a slight cost to elegance of code in GeoTiffReader and GeoTiffTile/GeoTiffMultibandTile
> Remove references to UIntCells

- raster-test/src/test/scala/geotrellis/raster/render/ColorMapSpec.scala
- raster/src/main/scala/geotrellis/raster/render/PngRenderMethods.scala
- raster/src/main/scala/geotrellis/raster/render/png/PngColorEncoding.scala
I noticed that fallback colors were being handled improperly in indexed PNGs. Logic was added to handle those cases and tests constructed to ensure that both nodata and fallback cases are handled appropriately.
> Add ability to handle fallback colors on indexed pngs

- s3/src/main/scala/geotrellis/spark/io/s3/SaveToS3.scala
- s3/src/main/scala/geotrellis/spark/io/s3/SaveToS3Methods.scala
- s3/src/main/scala/geotrellis/spark/io/s3/package.scala
- s3/src/test/scala/geotrellis/spark/io/s3/S3SaveImagesSpec.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/SpatialRenderOutput.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/MoreSaveToHadoopMethods.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/SaveToHadoop.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/SaveToHadoopMethods.scala
- spark/src/main/scala/geotrellis/spark/io/slippy/HadoopSlippyTileWriter.scala
- spark/src/test/scala/geotrellis/spark/render/SaveImagesSpec.scala
Fixes incorrect parsing of URI template when saving to s3, adds tests to cover the failures.
Also changes `SaveToS3Methods` object to `SaveToS3` to better describe what it does. Extension method `.saveToS3()`  remains unchanged.
> Fix saveToS3 path template parsing 

- raster/src/main/scala/geotrellis/raster/reproject/RasterReprojectMethods.scala
- raster/src/main/scala/geotrellis/raster/reproject/ReprojectRasterExtent.scala
- spark/src/main/scala/geotrellis/spark/TileLayerMetadata.scala
- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
- spark/src/test/scala/geotrellis/spark/TestRegistrator.scala
- spark/src/test/scala/geotrellis/spark/reproject/TileRDDReprojectSpec.scala
- spark/src/test/scala/geotrellis/spark/tiling/LayoutDefinitionSpec.scala
- spark/src/test/scala/geotrellis/spark/tiling/MapKeyTransformSpec.scala
This set of changes shortcuts out of reprojection if the CRS's are the same. There's some floating point errors that can happen if you send what should be a no-op through reprojection, which can have undesirable consequences.
> Shortcut out of reproject if it's the same CRS

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloRDDReader.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3RDDReader.scala
- spark/src/main/scala/geotrellis/spark/io/file/FileRDDReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopRDDReader.scala
Bug was found in Accumulo RDD Reader:
```scala
InputFormatBase.setRanges(job, ranges)
```
Empty ranges (empty list) means to scan full table.
* How to achieve this situation: to query by keys that are not intersecting with ingested.
* Why this bug was not noticed (probably some other reasons / mb just had no such case): https://github.com/geotrellis/geotrellis/blob/master/accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloRDDReader.scala#L54
* How i noticed it: experimented on temporal ingest, and found that i always have lots of spark tasks while querying by not ingested time.
Probably that's a good idea just to return an empty RDD on empty query bounds, though using a return is a bit dirty.
> Fix possible weird rdd readers behaviour on empty queryKeyBounds

- spark/src/main/scala/geotrellis/spark/TileLayerMetadata.scala
- spark/src/main/scala/geotrellis/spark/package.scala
This patch includes a fix to API, `TileLayerMetadata.fomRdd[K1, V, K](layoutDefinition)` now returns `TileLayerMetadata[K]` instead of `(Int, TileLayerMetadata[K])`. This is both consistent with the other invocation and more correct since layoutDefinition bypasses the zoom level generation process.
Also `rdd.collectMetadata[K](layoutScheme)` and `rdd.collectMetadata[K](layoutDefinition)` are added to cover those cases when `crs` must be collected.
> rdd.collectMetadata[K] covers all cases

- raster-test/src/test/scala/geotrellis/raster/histogram/StreamingHistogramSpec.scala
- raster/src/main/scala/geotrellis/raster/histogram/StreamingHistogram.scala
- raster/src/main/scala/geotrellis/raster/io/json/Implicits.scala
- raster/src/main/scala/geotrellis/raster/io/json/StreamingHistogramJson.scala
In this pull request, support is added for serializing (and deserializing) the `StreamingHistogram` type to (and from) Json.
Closes #1420
> Streaming Histogram Json Serialization

- raster-test/src/test/scala/geotrellis/raster/histogram/FastMapHistogramSpec.scala
- raster/src/main/scala/geotrellis/raster/histogram/FastMapHistogram.scala
FastMapHistogram was storing items and counts in a single array, with element 2\*i holding the item and 2\*i+1 storing the count. Counts could roll over for values above Int.MaxValue. This change splits the items and counts into two arrays, where the latter now stores Long values.
> Store FastMapHistogram counts as longs

- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
- spark/src/main/scala/geotrellis/spark/tiling/CutTiles.scala
We weren't passing the resample method to the merge call in CutTiles, which was an oversight. This fixes it. Reprojecting still forces NearestNeighbor for the `tileToLayout` call when using a FloatingLayoutScheme, since the cells will line up and the bilinear computation shouldn't happen because of potential floating point errors or NoData overriding behavior.
> Pass resampling method argument to merge in CutTiles.

- raster-test/src/test/scala/geotrellis/raster/CellTypeSpec.scala
- raster/src/main/scala/geotrellis/raster/CellType.scala
Handle negative, +/-Infinity, NaN.
Specifically `float64udNaN` will parse as `float64` and `float32udNaN` will parse as `float32`
> Fixes to user defined float/double CellType parsing

- spark/src/main/scala/geotrellis/spark/io/index/ZCurveKeyIndexMethod.scala
- spark/src/main/scala/geotrellis/spark/io/index/zcurve/ZSpaceTimeKeyIndex.scala
The operand 24 was missing in byMonth/byYear methods.
> Fix month and year calculations

- build.sbt
`geotrellis/proj4/src/main/java/org/osgeo/proj4j/util/PolarCoordinate.java` line 18 contains both a lambda and a phi (the actual greek characters, not the words), which results in the following compilation error on some systems: "unmappable character for encoding ASCII".
This change prevents that error.
> Handle Special Characters

- raster/src/main/scala/geotrellis/raster/ArrayMultibandTile.scala
- spark/src/main/scala/geotrellis/spark/io/avro/codecs/TileCodecs.scala
- spark/src/test/scala/geotrellis/spark/io/avro/AvroTools.scala
- spark/src/test/scala/geotrellis/spark/io/avro/TileCodecsSpec.scala
There is an inconsistency between encode and decode methods of ArrayTileCodecs for int and byte types: when encoding, it writes zero, but when decoding it expects min value for a type.
> Fix nodata values in codecs

- raster-test/src/test/scala/geotrellis/raster/render/ColorRampSpec.scala
- raster/src/main/scala/geotrellis/raster/render/ColorRamp.scala
What we initially thought to be a problem with either `geotrellis-admin` or my ingesting process turned out to be an issue with how `ColorMap`s are created by `geotrellis-raster`. 
The following is output from the `geotrellis-admin` server inside `docker-compose`:
```
adminserver_1  | [ERROR] [05/20/2016 16:52:04.572] [geotrellis-admin-server-akka.actor.default-dispatcher-5] [akka://geotrellis-admin-server/user/geotrellis-admin-service] Error during processing of request HttpRequest(GET,http://adminserver:8080/gt/tms/nlcd-tms-epsg3857-testing3/3/2/2?colorRamp=blue-to-yellow-to-red-heatmap&breaks=4d7ed1b2-7d99-48e7-bba9-ee963fcef49f&opacity=100,List(Host: adminserver:8080, Connection: close, User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0, Accept-Language: …
```
> Handle entire layers of `NODATA`

- raster-test/src/test/scala/geotrellis/raster/histogram/StreamingHistogramSpec.scala
- raster/src/main/scala/geotrellis/raster/summary/SummaryMethods.scala
A paramater was unused in for streaming histograms, this should rectify that
> Add ability to specify number of streaming buckets

- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopSparkContextMethods.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/formats/TemporalGeoTiffInputFormat.scala
To read temporal GeoTiffs we need to specify the tag and date format, which is not standard. Without this fix there is no way to do this outside using `TemporalGeoTiffInputFormat`. This PR adds the two required arguments to the extension methods on `SparkContext` with default values.
> SparkContext temporal GeoTiff format args

- scripts/publish-local-211.sh
For local publishing when you know you only need it for Scala 2.11. Faster than using `publish-local-crossversion.sh`.
> Add local publishing script for Scala 2.11

- spark-etl/src/main/scala/geotrellis/spark/etl/EtlConf.scala
When specifying `--layoutExtent=...` during `spark-etl` use, one must currently also provide a `cellSize` and a `cellType`. As discussed [in this PR comment](https://github.com/azavea/azavea-data-hub/pull/36#discussion_r65429017), `cellType` is no longer needed here.
This change affects the documentation updates in azavea/azavea-data-hub#36.
> Remove dep on `cellType` when specifying `layoutExtent`

- raster-test/src/test/scala/geotrellis/raster/histogram/StreamingHistogramSpec.scala
- raster/src/main/scala/geotrellis/raster/histogram/StreamingHistogram.scala
Fixes #1462 and ameliorates #1499
This set of changes makes sure that any `ClassBreaks` produced will start with the minimum value and interpolate the values in between according to the bins observed by the streaming histogram.
> Add logic to ensure use of minval/avoid repetition of breaks

- spark-etl/src/main/scala/geotrellis/spark/etl/EtlConf.scala
> Backport: Remove dep on `cellType` when specifying `layoutExtent`

- .travis.yml
- .travis/build-and-test-set-1.sh
- .travis/build-and-test-set-2.sh
- .travis/build-and-test.sh
- build.sbt
This modifies the travis build to run only a subset of the tests, based on the JDK version and the scala version. It takes the commit hash into account so that it randomizes which run set will be executed for which environment. For instance, the second travis run for this executed these sets:
```
Scala 2.10.6, openjdk7   - Run set 2
Scala 2.11.8, openjdk7   - Run set 1
Scala 2.10.6, oraclejdk7 - Run set 1
Scala 2.11.8, oraclejdk7 - Run set 2
Scala 2.10.6, oraclejdk8 - Run set 2
Scala 2.11.8, oraclejdk8 - Run set 1
```
For the previous travis run of this PR, the run sets were flipped.
This modifies the building that was being run in a couple of ways: we no longer compile projects that are going to be compiled transitively by other projects, and runs tests on `slick` and `shapefile` as …
> Modified travis test runs to cut down on run time.

- raster-test/src/test/scala/geotrellis/raster/render/ColorMapSpec.scala
- raster/src/main/scala/geotrellis/raster/render/ColorMap.scala
When using the `render` output module in the ETL process, one must provide a `breaks` argument, or all tiles will be rendered grayscale. Example:
```console
--output render -O encoding=png path=file:///home/colin/tiles/{name}/{z}-{x}-{y}.png breaks="23:cc00ccff;30:aa00aaff;120:ff0000ff"
```
The problem is that for datasets which don't have well-defined colour breaks ahead of time like `nlcd`, there's no way to know what your break string should be for input into ETL. A `ColorMap` object can be created easily given `RDD.colorBreaks` and then rendered to a PNG within Scala code, but there is no way to know what `String` would represent that `ColorMap` from the outside. This chicken-and-egg problem requires a greater fix to how ETL accepts breaks information from the outside, but this is a …
> ColorMap => String

- spark/src/main/scala/geotrellis/spark/io/avro/AvroEncoder.scala
This PR adds a little bit of information necessary to properly understand why the Avro decoding process fails in some circumstances and is a response to #1477
The new error looks something like:
```scala
org.apache.avro.AvroTypeException: Found geotrellis.raster.ByteArrayTile, expecting geotrellis.raster.ArrayMultibandTile, missing required field bands. If attempting to read multiband tiles, use a Reader[K, MultibandTile] rather than Reader[K, Tile]
```
> Add detail to avro exception message

- .travis/build-and-test-set-1.sh
- build.sbt
- doc-examples/build.sbt
- doc-examples/src/main/scala/geotrellis/doc/examples/spark/SparkExamples.scala
- docs/spark/spark-examples.md
- scripts/buildall-2.11.sh
- scripts/buildall.sh
Added a subproject that we can use for compiling documentation examples.
Added an example for starting with an `RDD[(ProjectedExtent, Tile)]` and ending up with a GeoTiff.
> doc-examples subproject; example for tiling to GeoTiff

- spark-etl/build.sbt
- spark-etl/src/main/scala/geotrellis/spark/etl/EtlConf.scala
Since Scallaop 1.x automatic verification of configuration objects no longer works - now we must call `.verify()` function manually. Updates Scallop and fixes EtlConf class.
> Fix Spark Etl

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloUtils.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopLayerWriter.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopRDDWriter.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopValueReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/formats/FilterMapFileInputFormat.scala
- spark/src/main/scala/geotrellis/spark/io/index/KeyIndex.scala
- spark/src/main/scala/geotrellis/spark/partition/IndexPartitioner.scala
- spark/src/main/scala/geotrellis/spark/util/GroupIterator.scala
- spark/src/main/scala/geotrellis/spark/util/cache/cache.scala
- spark/src/test/scala/geotrellis/spark/util/cache/CacheSpec.scala
This PR improves HDFS layer writing and random value reading support.
`HadoopValuesReader` now opens up `MapFile.Readers` for each map file in the layer. These readers cache the index of available keys so they are able to provide quick lookups. This replaces and improves previous method of using `FileInputFormat` to query for a single record.
`HadoopRDDWriter` has multiple improvements:
- Accomplishes it's task with a single shuffle step
- This is possible because instead of estimating the blocks required by counting we simply roll over to a new file when the record being written is about to surpass the block boundary.
- Instead of using a groupBy we sort our records on shuffle which uses IO index to partition the records
- Writes happen through mapping the partition iterator, this is …
> Better HDFS Support

- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiff.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffImageData.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffOptions.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffSegment.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffSegmentCollection.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffSegmentLayout.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffTile.scala
I added documentation to most methods and a few vals in the GeoTiff* files. There are a few more things that I want to add, but I think I'll need some things explained before I do.
> Added documentation to the GeoTiff* files

- spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/EtlConf.scala
- spark/src/main/scala/geotrellis/spark/TileLayerMetadata.scala
This PR addresses https://github.com/geotrellis/geotrellis/issues/1484 by adding an optional "maxZoom" argument to ETLConf (with a default value of 0), and modifies both the Etl and TileLayerMetadata classes to handle that option.
In testing with the Chattanooga demo however, setting maxZoom levels above 10 often led to the ingestion process being killed due to lack of memory.  Increasing VM memory to 6 GB, and the memory available to the ingestion process to 4 GB, allowed the ingestion process to succeed up to zoom level 12.
> Add ETL option to specify upper zoom limit for raster layer ingestion

- project/Environment.scala
- spark/src/main/scala/geotrellis/spark/join/SpatialJoin.scala
- spark/src/main/scala/geotrellis/spark/join/SpatialJoinMethods.scala
- spark/src/main/scala/geotrellis/spark/partition/SpacePartitioner.scala
When performing spatial joins using the current version of Spark (1.6.1) with Geotrellis 0.10.1 (itself compiled against Spark 1.5.2), spatial joins fail with a NoSuchMethodError.
For example, running SpatialSparkExample.scala with the code at [https://gist.github.com/aeffrig/f49cefdb5326e0917263a926cd71c14b] and two overlapping Landsat images as arguments results in
```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.rdd.ShuffledRDD.<init>(Lorg/apache/spark/rdd/RDD;Lorg/apache/spark/Partitioner;)V
at geotrellis.spark.partition.SpacePartitioner.apply(SpacePartitioner.scala:65)
at geotrellis.spark.join.SpatialJoin$.join(SpatialJoin.scala:53)
at geotrellis.spark.join.SpatialJoinMethods.spatialJoin(SpatialJoinMethods.scala:20)
at …
```
> Add ClassTag where needed for compatibility with Spark 1.6.1

- spark/src/main/scala/geotrellis/spark/merge/RDDLayoutMerge.scala
- spark/src/main/scala/geotrellis/spark/merge/RddLayoutMergeMethods.scala
This is another example of why we don't put functionality into classes that will close over implicit class type parameter context bounds.
Fixes #1567
> Moved RDDLayoutMergeMethods functionality to object.

- shapefile/build.sbt
Travis started working again because we explicitly list where to get jai in the geotools subproject; this PR does this for the shapefile project for completeness.
> Added jai as explicit url dependency, to fix Travis builds.

- slick/src/test/scala/geotrellis/slick/PostgisSpec.scala
There's one slick test that fails Travis off and on; on inspection, the only thing I can see off about it is that it creates a query before creating the schema and populating the table. This is more correct, but I'm unsure it will solve our Travis woes; one can only hope.
> Create query after table is populated in slick test.

- doc-examples/src/main/scala/geotrellis/doc/examples/spark/SparkExamples.scala
- doc-examples/src/test/scala/geotrellis/doc/examples/spark/SparkExamplesTests.scala
- docs/spark/spark-examples.md
- raster/src/main/scala/geotrellis/raster/MultibandTile.scala
There was a spark example in which it was a bit awkward to create a new multiband tile out of a multiband tile by applying a focal median operation over each band. This API addition makes it less awkward.
> Added mapBands to MultibandTile, updated doc example using it.

- docs/arch/adr-0002-hdfs-raster-layers.md
This ADR describes current implementation of the HDFS layers and key design decisions that were considered. This is intended to as both documentation and starting off point for further improvements.
> ADR: HDFS Raster Layers

- spark/src/main/scala/geotrellis/spark/summary/polygonal/Implicits.scala
- spark/src/main/scala/geotrellis/spark/summary/polygonal/PolygonalSummaryTileRDDMethods.scala
Previously, the abstact class `PolygonalSummaryTileLayerRDDMethods` required a `TileLayerRDD`, which has certain constraints on what its metadata must contain. This was restrictive, as the `polygonalSummary` methods only require RDDs whose internals can be converted to Rasters. This PR relaxes the type requirements, such that anything that can convert to Rasters can use these summary methods automatically.
> [Polygonal Summary] Relax types to anything `Tile`d

- accumulo/src/main/resources/reference.conf
- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloWriteStrategy.scala
- cassandra/src/main/resources/reference.conf
- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraAttributeStore.scala
- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraRDDReader.scala
- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraRDDWriter.scala
- docs/spark/spark-io.md
- hbase/src/test/scala/geotrellis/spark/io/hbase/HBaseSpaceTimeSpec.scala
- hbase/src/test/scala/geotrellis/spark/io/hbase/HBaseSpatialSpec.scala
- hbase/src/test/scala/geotrellis/spark/io/hbase/HBaseTileFeatureSpaceTimeSpec.scala
- hbase/src/test/scala/geotrellis/spark/io/hbase/HBaseTileFeatureSpatialSpec.scala
- project/Version.scala
- s3/src/main/resources/reference.conf
- s3/src/main/scala/geotrellis/spark/io/s3/S3RDDReader.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3RDDWriter.scala
- spark/src/main/resources/reference.conf
- spark/src/main/scala/geotrellis/spark/io/file/FileRDDReader.scala
> Parallelize reads

- docs/concepts/projections-extents-layouts.md
*The other day, on gitter:*
Me: Alright, I'm digging into the relationship between projections, layout definitions, and extents.
@echeipesh : That sounds like a title of an excellent doc page I wish we had.
> `Projections, Extents, and Layout Definitions` doc

- doc-examples/src/main/scala/geotrellis/doc/examples/spark/VoxelKey.scala
- docs/spark/custom-key.md
Example documentation on how to implement a new key type, used in `KeyIndex`es and many GeoTrellis operations.
> Example: VoxelKey

- s3/src/main/scala/geotrellis/spark/io/s3/S3InputFormat.scala
An s3 URL can come in a few different flavors. This updates a regex to handle them.
> Make regex for s3 URLs handle s3/s3a/s3n

- .travis/build-and-test-set-2.sh
- geowave/build.sbt
- geowave/src/main/scala/geotrellis/spark/io/kryo/GeowaveKryoRegistrator.scala
- geowave/src/test/scala/geotrellis/spark/io/geowave/GeoWaveFeatureRDDReaderSpec.scala
- geowave/src/test/scala/geotrellis/spark/io/geowave/GeowaveSpatialSpec.scala
- scripts/geowaveTestDB.sh
This allows the tests in the GeoWave subproject to pass.  Because there is [currently an incompatibility with the latest versions of GeoWave](https://github.com/ngageoint/geowave/issues/914), an older version of GeoWave must (currently) be built and installed in one's local `~/.m2` repository.  The complete sequence is:
1. Build an older version of GeoWave locally.  That can be done by pulling down [this repository](https://github.com/jamesmcclain/GeoWaveDocker) and typing `make world`.
2. Apply the diff listed at the bottom of this comment to this branch
3. Type `docker run -td --restart=always --net=geowave -p 50095:5009 -p 21810:2181 -p 9997:9997 -p 9999:9999 --hostname leader --name leader jamesmcclain/geowave:c127c16` to start a local GeoWave instance
4. Type `echo leader localhost > …
> Fix GeoWave Tests

- spark/src/main/scala/geotrellis/spark/mapalgebra/focal/FocalTileLayerCollectionMethods.scala
- spark/src/main/scala/geotrellis/spark/mapalgebra/focal/FocalTileLayerRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/mapalgebra/focal/hillshade/HillshadeTileLayerCollectionMethods.scala
- spark/src/main/scala/geotrellis/spark/mapalgebra/focal/hillshade/HillshadeTileLayerRDDMethods.scala
- spark/src/test/scala/geotrellis/spark/mapalgebra/focal/SlopeSpec.scala
Fixes: https://github.com/geotrellis/geotrellis/issues/1629
Slope, Aspect and Hillshade operations return tiles with cell type of double.
RDD Metadata of input needs to be adjusted to reflect this change in cell type.
> Fix metadata on surface calculations

- geomesa/src/main/scala/geotrellis/geomesa/geotools/FeatureToGeoMesaSimpleFeatureMethods.scala
- geomesa/src/main/scala/geotrellis/geomesa/geotools/GeoMesaImplicits.scala
- geomesa/src/main/scala/geotrellis/geomesa/geotools/GeometryToGeoMesaSimpleFeature.scala
- geomesa/src/main/scala/geotrellis/spark/io/geomesa/GeoMesaFeatureReader.scala
- geomesa/src/main/scala/geotrellis/spark/io/geomesa/GeoMesaFeatureWriter.scala
- geomesa/src/main/scala/geotrellis/spark/io/geomesa/GeoMesaInstance.scala
- geomesa/src/main/scala/geotrellis/spark/io/geomesa/kryo/KryoRegistrator.scala
- geomesa/src/main/scala/geotrellis/spark/io/geomesa/package.scala
- geomesa/src/main/scala/org/locationtech/geomesa/jobs/mapreduce/GeoMesaInputFormat.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeoWaveFeatureRDDReader.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeoWaveFeatureRDDWriter.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeowaveAttributeStore.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeowaveLayerReader.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeowaveLayerWriter.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeowaveUtil.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/SerializablePersistable.scala
- geowave/src/main/scala/geotrellis/spark/io/kryo/GeowaveKryoRegistrator.scala
- util/src/main/java/geotrellis/util/annotations/experimental.java
Although an `@experimental` decorator has been created and used, this changeset is a largely a cosmetics- and documentation-related one.  That is because giving the decorator any real teeth (e.g. displaying warning at compile-time when experimental features are used) would seem to require writing a compiler plugin.
Fixes #1677
> Mark GeoWave and GeoMesa Experimental

- spark/src/main/scala/geotrellis/spark/summary/StatsTileRDDMethods.scala
- spark/src/test/scala/geotrellis/spark/summary/StatsTileRDDMethodsSpec.scala
This changeset provides the capability to compute histograms over a fraction of the tiles in an RDD.
Fixes #1465
> Histograms Over Fractions of RDDs of Tiles

- raster-test/src/test/scala/geotrellis/raster/sigmoidal/SigmoidalContrastSpec.scala
- raster/src/main/scala/geotrellis/raster/package.scala
- raster/src/main/scala/geotrellis/raster/sigmoidal/MultibandSigmoidalMethods.scala
- raster/src/main/scala/geotrellis/raster/sigmoidal/SigmoidalContrast.scala
- raster/src/main/scala/geotrellis/raster/sigmoidal/SinglebandSigmoidalMethods.scala
- spark/src/main/scala/geotrellis/spark/package.scala
- spark/src/main/scala/geotrellis/spark/sigmoidal/Implicits.scala
- spark/src/main/scala/geotrellis/spark/sigmoidal/RDDMultibandSigmoidalMethods.scala
- spark/src/main/scala/geotrellis/spark/sigmoidal/RDDSigmoidalContrast.scala
- spark/src/main/scala/geotrellis/spark/sigmoidal/RDDSinglebandSigmoidalMethods.scala
- spark/src/test/scala/geotrellis/spark/sigmoidal/RDDSigmoidalContrastSpec.scala
- util/src/main/scala/geotrellis/util/ByteReader.scala
- util/src/main/scala/geotrellis/util/BytesStreamer.scala
- util/src/main/scala/geotrellis/util/StreamByteReader.scala
Still needs:
Original:
Imagemagick (`convert -sigmoidal-contrast 10,50%`):
This PR (with alpha=0.5 and beta=10):
> Sigmoidal Contrast

- raster/src/main/scala/geotrellis/raster/io/geotiff/UInt16GeoTiffMultibandTile.scala
This fixes a slight oversight which causes a compiler warning (though, contingently, it happens to be the case that there are no possible runtime errors as a result of this oversight - the only thing that can get passed into this constructor is the type which this PR changes the constructor to expect).
> Fix non-exhaustive match

- doc-examples/src/main/scala/geotrellis/doc/examples/spark/SparkExamples.scala
- docs/spark/spark-examples.md
- spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala
- spark-testkit/src/main/scala/geotrellis/spark/testkit/TileLayerRDDBuilders.scala
- spark/src/main/scala/geotrellis/spark/ingest/Ingest.scala
- spark/src/main/scala/geotrellis/spark/ingest/MultibandIngest.scala
- spark/src/main/scala/geotrellis/spark/package.scala
- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
- spark/src/test/scala/geotrellis/spark/reproject/TileRDDReprojectSpec.scala
It turns out that the solution form #1405 was already present in the code.  All uses of `TileLayerMetadata.fromRdd` in the code and the markdown examples have been changed to use the `collectMetadata` methods.
Fixes #1405
> Use `collectMetadata` instead of `TileLayerMetadata.fromRdd`

- s3/src/main/scala/geotrellis/spark/io/s3/GeoTiffS3InputFormat.scala
- s3/src/main/scala/geotrellis/spark/io/s3/MultibandGeoTiffS3InputFormat.scala
- s3/src/main/scala/geotrellis/spark/io/s3/TemporalGeoTiffS3InputFormat.scala
- s3/src/main/scala/geotrellis/spark/io/s3/TemporalMultibandGeoTiffS3InputFormat.scala
- s3/src/test/scala/geotrellis/spark/io/s3/GeoTiffS3InputFormatSpec.scala
- spark-etl/src/main/resources/input-schema.json
- spark-etl/src/main/scala/geotrellis/spark/etl/config/Input.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/config/json/ConfigFormats.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/GeoTiffHadoopInput.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/GeoTiffSequenceHadoopInput.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/MultibandGeoTiffHadoopInput.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/MultibandGeoTiffSequenceHadoopInput.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/TemporalGeoTiffHadoopInput.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/TemporalMultibandGeoTiffHadoopInput.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/s3/GeoTiffS3Input.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/s3/MultibandGeoTiffS3Input.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/s3/TemporalGeoTiffS3Input.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/s3/TemporalMultibandGeoTiffS3Input.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopSparkContextMethods.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/formats/GeotiffInputFormat.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/formats/MultibandGeoTiffInputFormat.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/formats/TemporalGeoTiffInputFormat.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/formats/TemporalMultibandGeoTiffInputFormat.scala
- spark/src/test/scala/geotrellis/spark/ingest/IngestSpec.scala
Fixes https://github.com/geotrellis/geotrellis/issues/1414
Double checked that we can read tiffs without crs (crs would be set to `LatLng`), added additional setting `inputCrs` for `S3` and `Hadoop` `InputFormats`.
> Ingest tiles without CRS in metadata

- vector-test/src/test/scala/spec/geotrellis/vector/io/json/GeometryFormatsSpec.scala
- vector/src/main/scala/geotrellis/vector/io/json/GeometryFormats.scala
This PR allows GeoTrellis to read GeoJson with 3-dimensional coordinate information by adopting the approach of throwing out the z-coordinate.  Smarter handling of elevation data will require a more thorough approach, requiring a new Geometry subclass with z-coordinate capabilities, which would necessarily percolate out into the rest of the library.
This PR closes issues #1272.
> Add support for 3d points in GeoJson

- s3/src/main/scala/geotrellis/spark/io/s3/S3AttributeStore.scala
Since it already transitively extends it through `BlobLayerAttributeStore`.
> `S3AttributeStore` doesn't need to extend `AttributeStore`

- spark/src/main/scala/geotrellis/spark/io/hadoop/HdfsUtils.scala
- spark/src/test/scala/geotrellis/spark/io/hadoop/HdfsUtilsSpec.scala
This PR adds a rangeRead method to HdfsUtils that allows for reading ranges of bytes.
> Hdfs Range Reads

- docs/tutorials/etl.md
- mkdocs.yml
> ETL Tutorial

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/MultibandCropIteratorSpec.scala
- raster-test/src/test/scala/geotrellis/raster/io/geotiff/SinglebandCropIteratorSpec.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/CropIterator.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/MultibandCropIterator.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/MultibandGeoTiff.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/SinglebandCropIterator.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/SinglebandGeoTiff.scala
This PR adds a `CropIterator` abstract class and its two subclasses: `SinglebandCropIterator` and `MultibandCropIterator`. These new classes are extensions of `Iterator` that will take a GeoTiff and split it into multiple GeoTiffs based on inputted dimensions. The returned values will be these sub-tiles.
> Crop Iterator for GeoTiffs

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/BigTiffSpec.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/ArraySegmentBytes.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/BufferSegmentBytes.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReader.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/TiffTagsReader.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/BasicTags.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/TiffTagMetadata.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/TileTags.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/codes/TiffFieldType.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/util/ByteReaderExtensions.scala
- s3-testkit/src/main/scala/geotrellis/spark/io/s3/testkit/MockS3ByteReader.scala
- util/src/main/scala/geotrellis/util/ByteReader.scala
- util/src/main/scala/geotrellis/util/StreamByteReader.scala
This PR adds the ability for GeoTrellis to read Big, GeoTiff files. It is important to note that this **will only work with GeoTiffs**. Regular BigTiff files are currently not supported even though their smaller counterparts are. This is an issue that will be addressed and fixed in the near future.
> Reading Big GeoTiffs

- raster-test/src/test/scala/geotrellis/raster/matching/HistogramMatchingSpec.scala
- raster/src/main/scala/geotrellis/raster/equalization/HistogramEqualization.scala
- raster/src/main/scala/geotrellis/raster/equalization/SinglebandEqualizationMethods.scala
- raster/src/main/scala/geotrellis/raster/histogram/StreamingHistogram.scala
- raster/src/main/scala/geotrellis/raster/matching/HistogramMatching.scala
- raster/src/main/scala/geotrellis/raster/matching/MultibandMatchingMethods.scala
- raster/src/main/scala/geotrellis/raster/matching/SinglebandMatchingMethods.scala
- raster/src/main/scala/geotrellis/raster/package.scala
- raster/src/main/scala/geotrellis/raster/sigmoidal/MultibandSigmoidalMethods.scala
- raster/src/main/scala/geotrellis/raster/sigmoidal/SinglebandSigmoidalMethods.scala
- spark/src/main/scala/geotrellis/spark/equalization/RDDHistogramEqualization.scala
- spark/src/main/scala/geotrellis/spark/equalization/RDDMultibandEqualizationMethods.scala
- spark/src/main/scala/geotrellis/spark/equalization/RDDSinglebandEqualizationMethods.scala
- spark/src/main/scala/geotrellis/spark/matching/Implicits.scala
- spark/src/main/scala/geotrellis/spark/matching/RDDHistogramMatching.scala
- spark/src/main/scala/geotrellis/spark/matching/RDDMultibandMatchingMethods.scala
- spark/src/main/scala/geotrellis/spark/matching/RDDSinglebandMatchingMethods.scala
- spark/src/main/scala/geotrellis/spark/package.scala
- spark/src/main/scala/geotrellis/spark/sigmoidal/Implicits.scala
- spark/src/main/scala/geotrellis/spark/sigmoidal/RDDMultibandSigmoidalMethods.scala
- spark/src/main/scala/geotrellis/spark/sigmoidal/RDDSigmoidalContrast.scala
- spark/src/main/scala/geotrellis/spark/sigmoidal/RDDSinglebandSigmoidalMethods.scala
- spark/src/test/scala/geotrellis/spark/matching/RDDHistogramMatchingSpec.scala
- spark/src/test/scala/geotrellis/spark/sigmoidal/RDDSigmoidalContrastSpec.scala
Still Needs:
The original image.
The image after sigmoidal contrast.  Notice that the histogram shown in the screenshot includes the boundary around the image.
The raw image after its histogram has been matched to that of the sigmoidal contrast image.  Notice that it is darker than the original and the histogram looks different.
Here is the histogram of just inner part of the "histogram matching" image (without the boundary); that image inherited its histogram from the entire "sigmoidal contrast" image (including the boundary, not just the inner part).  The histogram of the inner part of the "histogram matching" image agrees nicely with the histogram of the entire "sigmoidal contrast" image (which is the histogram that we were trying to match).
> Histogram Matching

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloAttributeStore.scala
- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraAttributeStore.scala
- hbase/src/main/scala/geotrellis/spark/io/hbase/HBaseAttributeStore.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3AttributeStore.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/OutputPlugin.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/SpatialRenderOutput.scala
- spark/src/main/scala/geotrellis/spark/io/file/FileAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopAttributeStore.scala
- spark/src/test/scala/geotrellis/spark/io/AttributeStoreSpec.scala
This feature allows us to include client code in the save process for ETL. Lets us do things like:
```scala
EtlConf(args) foreach { conf =>
val etl = Etl(conf)
val sourceTiles = etl.load[ProjectedExtent, Tile]
val (zoom, tiled) = etl.tile[ProjectedExtent, Tile, SpatialKey](sourceTiles)
etl.save[SpatialKey, Tile](LayerId(etl.input.name, zoom), tiled, { (attributeStore, layerWriter, layerId, rdd) =>
// Save off histogram computed from zoom 9, store in zoom 0's attributes.
if(layerId.zoom == 9) {
val histogram = rdd.histogram(512)
attributeStore.write(
layerId.copy(zoom = 0),
"histogram",
histogram: Histogram[Double])
}
})
}
```
which is otherwise very difficult to do in the ETL context.
__Also in this PR__
Changing the layerExists functionality on AttributeStore to check specifically for …
> Added save action to ETL

- raster/src/main/scala/geotrellis/raster/package.scala
- raster/src/main/scala/geotrellis/raster/summary/MultibandTileSummaryMethods.scala
- raster/src/main/scala/geotrellis/raster/summary/SinglebandTileSummaryMethods.scala
- spark/src/main/scala/geotrellis/spark/summary/Implicits.scala
- spark/src/main/scala/geotrellis/spark/summary/StatsMultibandTileRDDMethods.scala
Adds method extensions for `histogram` and related stats functions to `MultibandTile` and `RDD[(K, MultibandTile)]`.
Because `MultibandTile` is essentially a `Vector[Tile]` the extension methods have little choice than return an `Array` of their `Tile` counterpart.
Fixes: https://github.com/geotrellis/geotrellis/issues/1773
> Multiband histogram methods

- raster-test/src/test/scala/geotrellis/raster/merge/TileMergeMethodsSpec.scala
- raster/src/main/scala/geotrellis/raster/merge/SinglebandTileMergeMethods.scala
There was a bug which took effect when we used the extent-based merge methods on cell types that had no NoData handling. This is caused by the interpolation returning NoData values when we interpolate outside the bounds of the original tile, so was happening when we were interpolating values of a larger raster with the values of a smaller one (e.g. during tileToLayout and Pyramiding)
> Fixed bug in merge logic.

- raster-test/src/test/scala/geotrellis/raster/equalization/HistogramEqualizationSpec.scala
- raster/src/main/scala/geotrellis/raster/equalization/HistogramEqualization.scala
- raster/src/main/scala/geotrellis/raster/matching/HistogramMatching.scala
Verified using by equalizing Landsat imagery using histogram of the layer recorded at ingest.
Supersedes #1799
> Fix math error in CDF interpolation

- project/Boilerplate.scala
- raster-test/src/test/scala/geotrellis/raster/ArrayTileSpec.scala
- raster-test/src/test/scala/geotrellis/raster/DelayedConversionMultibandTileSpec.scala
- raster-test/src/test/scala/geotrellis/raster/DelayedConversionTileSpec.scala
- raster-test/src/test/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTileSpec.scala
- raster/src/main/scala/geotrellis/raster/ArrayMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/ArrayTile.scala
- raster/src/main/scala/geotrellis/raster/BitArrayTile.scala
- raster/src/main/scala/geotrellis/raster/ByteArrayTile.scala
- raster/src/main/scala/geotrellis/raster/CellType.scala
- raster/src/main/scala/geotrellis/raster/DelayedConversionMethods.scala
- raster/src/main/scala/geotrellis/raster/DelayedConversionMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/DelayedConversionTile.scala
- raster/src/main/scala/geotrellis/raster/DoubleArrayTile.scala
- raster/src/main/scala/geotrellis/raster/IntArrayTile.scala
- raster/src/main/scala/geotrellis/raster/MultibandTile.scala
- raster/src/main/scala/geotrellis/raster/PixelInterleaveBandArrayTile.scala
- raster/src/main/scala/geotrellis/raster/ShortArrayTile.scala
- raster/src/main/scala/geotrellis/raster/Tile.scala
- raster/src/main/scala/geotrellis/raster/UByteArrayTile.scala
- raster/src/main/scala/geotrellis/raster/UShortArrayTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/package.scala
This feature solves a very specific problem: Sometimes you want to `map` over a Tile, or `combine` a MulitbandTile's bands, or the like, and have the resulting Tile be of a different `CellType` then the original tile. For instance, when doing NDVI, if you do this on a `IntConstantNoDataCellType` multiband raster:
```scala
multibandTile.combineDouble(3, 4) { (r, ir) =>
(ir - r) / (ir + r)
}
```
You'll get garbage values, since the ratio produces results from [-1, 1], but our result tile will be `IntConstantNoDataCelltype`, which will not hold the floating point values. What you have to do now is convert it to a floating point valued raster first:
```scala
multibandTile.convert(DoubleConstantNoDataCellType).combineDouble(3, 4) { (r, ir) =>
(ir - r) / (ir + r)
}
```
This is awful for …
> DelayedConvert feature

- raster-test/src/test/scala/geotrellis/raster/rasterize/polygon/PolygonRasterizerSpec.scala
- raster/src/main/scala/geotrellis/raster/rasterize/polygon/PolygonRasterizer.scala
The issue was that when there were edges which crossed a pixel but whose intersection with the scan rectangle was outside of that pixel, the pixel was not being reported.
Supersedes #1800
Connects #1801
> Fix Non-Point Pixel + Partial Cell Rasterizer Bug

- spark-etl/src/main/scala/geotrellis/spark/etl/config/Input.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/config/json/ConfigFormats.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/GeoTiffHadoopInput.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/MultibandGeoTiffHadoopInput.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/TemporalGeoTiffHadoopInput.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/TemporalMultibandGeoTiffHadoopInput.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/s3/GeoTiffS3Input.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/s3/MultibandGeoTiffS3Input.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/s3/TemporalGeoTiffS3Input.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/s3/TemporalMultibandGeoTiffS3Input.scala
`maxTileSize` and `numPartitions` needed to be passed from ETL configuration through to hadoop and s3 GeoTiff inputs.
> Added missing options to hadoop and s3 input

- vector-test/src/test/scala/spec/geotrellis/vector/voronoi/ConformingDelaunaySpec.scala
- vector-test/src/test/scala/spec/geotrellis/vector/voronoi/DelaunaySpec.scala
- vector/src/main/scala/geotrellis/vector/package.scala
- vector/src/main/scala/geotrellis/vector/voronoi/ConformingDelaunay.scala
- vector/src/main/scala/geotrellis/vector/voronoi/Delaunay.scala
- vector/src/main/scala/geotrellis/vector/voronoi/package.scala
This changeset includes the addition of a wrapper around the JTS `ConformingDelaunayTriangulationBuilder` functionality.  This is of use for polygon triangulation.
Supersedes #1821
> Conforming Delaunay

- .travis/build-and-test-set-2.sh
- scripts/buildall.sh
- scripts/publish-local.sh
- scripts/publish-m2.sh
- scripts/publish-snapshot.sh
- scripts/runTestDBs.sh
The GeoWave API has changed and broken our support for them - this will suppress travis failures while we await solidification of the API
> Remove gwave tests from CI run

- slick/src/main/scala/geotrellis/slick/PostGisProjectionSupport.scala
- slick/src/test/scala/geotrellis/slick/PostGisProjectionSupportSpec.scala
- vector/build.sbt
- vector/src/main/scala/geotrellis/vector/io/WKB/WKB.scala
- vector/src/main/scala/geotrellis/vector/io/WKT/WKT.scala
Currently, a hex string starting with `\x` will be interpreted as well known text rather than well known binary which breaks PostGIS support. This PR introduces support for such hex strings.
> Fix support for slick WKB reading

- slick/build.sbt
We're currently seeing a weird failure on hudson builds related to a logging class not being found in Slick. This _may_ fix that problem
> Remove slick project's sl4j exclusion

- spark/src/main/scala/geotrellis/spark/join/VectorJoin.scala
- spark/src/main/scala/org/apache/spark/rdd/FilteredCartesianRDD.scala
- spark/src/test/scala/geotrellis/spark/join/VectorJoinRDDSpec.scala
A new RDD type has been defined, which is similar to the existing `CartesianRDD` type, but which allows short-circuiting of communication when a partition can be demonstrated to be disjoint from another (the word  "disjoint" is defined by a predicate function).  This behavior is useful for performing vector joins.
When joining an RDD of 10,000 elements (split into 32 partitions) to itself (giving the driver 32GB of memory, running locally on 32 cores), I get the following results:
```
vector join apply: count=88804   millis=17014
vector join naive: count=88804   millis=43075
```
10,000 (64 partitions):
```
vector join apply: count=88804   millis=25334
vector join naive: count=88804   millis=42647
```
10,000 (128 partitions):
```
vector join apply: count=88804   millis=32060
vector join …
```
> Remediate VectorJoin

- about.html
- contributing.md
- proj4/src/main/scala/geotrellis/proj4/CRS.scala
- proj4/src/main/scala/geotrellis/proj4/io/wkt/WKT.scala
- proj4/src/test/scala/geotrellis/proj4/io/wkt/WKTTest.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/writer/CoordinateSystemParser.scala
- Added more info in contributing.md
- Changed inconsistent naming of EPSG vs Epsg in code
- Gave a better error message for CRS write fails
- Modified about.html with 3rd party dependencies (autogenerated from Eclipse IP log)
> Cleanup for 1.0

- spark/src/main/scala/geotrellis/spark/buffer/CollectNeighbors.scala
- spark/src/main/scala/geotrellis/spark/buffer/CollectNeighborsMethods.scala
- spark/src/test/scala/geotrellis/spark/buffer/CollectNeighborsSpec.scala
Needs to be iterable instead of a Map, because K could have multiple keys with the same spatial component hence multiple neighbors of the same Direction. Thanks to @jpolchlo for the catch.
> Changed return type of CollectWithNeighbors

- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiff.scala
Fixes #1774 after locationtech repo move
> Add convenience overloads to GeoTiff companion object

- raster-test/src/test/scala/geotrellis/raster/rasterize/polygon/FractionalRasterizerSpec.scala
- raster/src/main/scala/geotrellis/raster/rasterize/package.scala
- raster/src/main/scala/geotrellis/raster/rasterize/polygon/FractionalRasterizer.scala
- raster/src/main/scala/geotrellis/raster/rasterize/polygon/PolygonRasterizer.scala
In this changeset, a polygon rasterizer which reports partial pixels and the respective fractions of those pixels that are covered by the polygon is presented.  The approach used seems to be the most efficient that is practical if sub-pixel geometries are to be supported.
[This resource](https://gis.stackexchange.com/questions/59821/how-to-calculate-volume-from-a-raster-file) recommends the same method for volumetric calculation as we are envisioning.  I have not found any contradictory resources.
> Fractional-Pixel Polygon Rasterizer

- pointcloud/src/main/scala/geotrellis/spark/io/hadoop/HadoopPointCloudRDD.scala
- pointcloud/src/main/scala/geotrellis/spark/io/hadoop/formats/PointCloudInputFormat.scala
- pointcloud/src/main/scala/geotrellis/spark/io/s3/S3PointCloudInputFormat.scala
- pointcloud/src/main/scala/geotrellis/spark/io/s3/S3PointCloudRDD.scala
- pointcloud/src/main/scala/geotrellis/spark/pointcloud/json/package.scala
We can reproject points before reading them into JVM memory.
> Reproject points using PDAL pipeline

- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopAttributeStore.scala
It's possible that the hostname that is supplied to the HadoopAttributeStore is different than the one in paths returned by HdfsUtils.listFiles, even though they point to the same files. Use relative paths to check if an attribute file exists to avoid this conflict.
> Use relative paths to check if layerExists in HadoopAttributeStore

- pointcloud/src/main/scala/geotrellis/spark/io/hadoop/formats/PointCloudInputFormat.scala
- pointcloud/src/main/scala/geotrellis/spark/io/s3/S3PointCloudInputFormat.scala
- project/Dependencies.scala
WARN: rebuild your local PDAL to use this update
But it may work without rebuild; as only one not important func call was redesigned
P.S. (not caused by my commit, double checked it) 
```
[info] - should be able to produce a tile *** FAILED ***
[info]   420.506564462933 was not greater than 435.49 (PointCloudDemSpec.scala:60)
```
> Update PDAL version

- raster/src/main/scala/geotrellis/raster/io/json/Implicits.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/config/json/ConfigFormats.scala
The format for `CellSize` in particular was in an odd place. It's been moved to `raster`.
> Bring home orphaned `raster` JsonFormats

- project/plugins.sbt
The PGP plugin works better as a globally installed plugin, and if you have the proper 1.0 version installed, you get SBT errors about the conflicting versions of plugins. This removes it, with the thought that if you are publishing signed JARs of GeoTrellis, you should have `sbt-plugin` installed globally.
> Removed pgp plugin.

- spark/src/main/scala/geotrellis/spark/io/avro/AvroEncoder.scala
Changed the `toBinary` and `fromBinary` methods in `AvroEncoder` so that user has control on whether they when to compress and/or decompress an `Array[Byte]`, respectively.
I've published this branch locally and used it with `GeoPySpark`, and it worked.
> Fixed AvroEncoder So That it Will Now Work With the Python Bindings

- build.sbt
- geowave/build.sbt
- macros/build.sbt
- project/Dependencies.scala
- project/Environment.scala
- project/Version.scala
- raster/build.sbt
- vectortile/build.sbt
Everything is updated up to latest version, except Accumulo, as Accumulo update can break compatibility with old Accumulo versions. And didn't touch `kryo` in the geowave project, as it may cause serialization issues.
```
geotrellis > dependencyUpdates
[info] No dependency updates found for geotrellis-vector
[info] No dependency updates found for geotrellis-raster
[info] No dependency updates found for geotrellis-vectortile
[info] Found 1 dependency update for geotrellis-spark
[info]   org.scalaz.stream:scalaz-stream : 0.8.6a -> 0.8.6
[info] No dependency updates found for geotrellis-geotools
[info] No dependency updates found for geotrellis-spark-etl
[info] No dependency updates found for geotrellis-raster-test
[info] No dependency updates found for geotrellis-s3
[info] No dependency …
```
> Dependencies update

- pointcloud/src/main/scala/geotrellis/pointcloud/pipeline/package.scala
More implicits to avoid PipelineConstructor cast into pipeline expression.
> Implicits fix

- pointcloud/src/main/scala/geotrellis/pointcloud/spark/triangulation/StitchedDelaunay.scala
- pointcloud/src/main/scala/geotrellis/pointcloud/spark/triangulation/TinToDem.scala
- raster/src/main/scala/geotrellis/raster/triangulation/DelaunayRasterizer.scala
- vector/src/main/scala/geotrellis/vector/triangulation/DelaunayStitcher.scala
There was an error in StitchedDelauay.rasterize() that resulted in only stitch triangles being displayed.  This is now fixed.
> Fixup StitchedDelaunay rasterizer

- spark/src/main/scala/geotrellis/spark/io/avro/codecs/ExtentCodec.scala
- spark/src/main/scala/geotrellis/spark/io/avro/codecs/Implicits.scala
- spark/src/main/scala/geotrellis/spark/io/avro/codecs/ProjectedExtentCodec.scala
- spark/src/main/scala/geotrellis/spark/io/avro/codecs/TemporalProjectedExtentCodec.scala
- spark/src/test/scala/geotrellis/spark/io/avro/ExtentCodecsSpec.scala
This PR adds two new codecs that can be encode/decoded in GeoTrellis: `ProjectedExtent` and `TemporalProjectedExtent`. The main reason for adding these two codecs is to allow for backend support between GeoTrellis and GeoPySpark.
> Avro Schema Creation for ProjectedExtent and TemporalProjectedExtent

- raster/src/main/scala/geotrellis/raster/io/geotiff/SinglebandGeoTiff.scala
This PR resolves issue #1975 by making it so that the new, cropped `SinglebandGeoTiff` will retain its predecessor's `Tag`s and `GeoTiffOptions` information.
> SinglebandGeoTiff's Crop Methods Fix

- docs/guide/core-concepts.md
The images in our 'guide' section of the docs which have titles are not being rendered properly at the moment. It appears as though we forgot to add quotes around the relevant text - this PR addresses that issue.
Fixes #1968
> Surround img titles with quotes

- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/TiffTags.scala
The data is available for computing `CellSize` from data available on tiff tags. This PR adds such a method. Are there any other methods which might be handy on a `TiffTags` instance?
> Compute cellsize from tifftags

- s3/src/main/scala/geotrellis/spark/io/s3/util/S3RangeReader.scala
A very common use case when using S3 is having to account for URIs and strings. We can use the structure of S3 URIs to make the API for grabbing an `S3RangeReader` a little less imposing.
> Add apply methods to s3rangereader

- raster/src/main/scala/geotrellis/raster/CellType.scala
Signed-off-by: Simeon H.K. fitch <fitch@astraea.io>
I have run into a number of situations where I'd like to enable the default ConstantNoData value for a DataType when the specific type isn't known at runtime. This PR is a draft implementation for the purposes of getting feedback. If this feature and implementation pass muster, I'll add unit tests.
> Added `withDefaultNoData` for all `DataType`s.

- pointcloud/src/main/scala/geotrellis/pointcloud/spark/dem/PointCloudToDem.scala
- pointcloud/src/main/scala/geotrellis/pointcloud/spark/triangulation/BoundaryDelaunay.scala
This allows users to put in the tile dimensions for a tile coming out of PointCloudToDem, so that if for example you require 256 x 256, you don't get a different dimension caused by the cellSize computing a different set of dimensions. Useful for ingest.
> Allow for tile dimensions to be set into PointCloudToDem

- .travis/hbase-install.sh
- build.sbt
- project/Dependencies.scala
- project/Environment.scala
- project/Version.scala
- project/plugins.sbt
- slick/build.sbt
- vector-test/build.sbt
Includes #2018 and #2019. 
Doesn't include scalapb update (as it has some api changes, that may be siginficant).
Doesn't include geowave updates (as it can be sensitive to deps).
Doesn't include Accumulo update (as it includes API changes).
Fixes https://github.com/locationtech/geotrellis/issues/2014
```
[info] No dependency updates found for geotrellis-proj4
[info] No dependency updates found for geotrellis
[info] No dependency updates found for geotrellis-vector
[info] Found 1 dependency update for geotrellis-vectortile
[info]   com.trueaccord.scalapb:scalapb-runtime : 0.5.46 -> 0.5.47
[info] No dependency updates found for geotrellis-slick
[info] No dependency updates found for geotrellis-vector-test
[info] No dependency updates found for geotrellis-raster
[info] No dependency updates …
```
> Deps update and cleanup

- raster/src/main/scala/geotrellis/raster/GridExtent.scala
These round to zero values cause zero column tiles in a LatLng to WebMercator reproject.  I could not figure out the root cause.  It looked to me like reasonable values were used, and that rounding was the issue.  An alternative fix might be to clip the data to the maximum extent of WebMercator in the projection.
> Tile columns cannot be zero when rounding

- vectortile/build.sbt
- vectortile/src/main/scala/geotrellis/vectortile/protobuf/internal/vector_tile/Tile.scala
- vectortile/src/main/scala/geotrellis/vectortile/protobuf/internal/vector_tile/VectorTileProto.scala
Bumping the dep wasn't enough, the IO code had to be regenerated as well.
Note: The generated code, while marked `DO NOT EDIT!`, has to be edited to include the license headers and the correct package name, namely `geotrellis.vectortile.protobuf.internal.vector_tile`.
> VectorTile: Use latest ScalaPB

- s3/src/main/scala/geotrellis/spark/io/s3/S3Client.scala
During failed ingests, metadata will often be written out despite no data having been written for the layer that metadata specifies. The trace such an attempted deletion causes: `Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: The XML you provided was not well-formed or did not validate against our published schema`.
By ensuring that S3 deletion requests are only generated for non-empty listings, we avoid this Exception.
> Avoid malformed XML in S3 layer deletion

- project/Version.scala
The master version should have been updated to 1.1.0 after the 1.0 branch was created. This PR fixes that.
Fixes #2032
> Corrected version to 1.1.0

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloAttributeStore.scala
- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloLayerDeleter.scala
- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraAttributeStore.scala
- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraLayerDeleter.scala
- hbase/src/main/scala/geotrellis/spark/io/hbase/HBaseAttributeStore.scala
- hbase/src/main/scala/geotrellis/spark/io/hbase/HBaseLayerDeleter.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3AttributeStore.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3LayerDeleter.scala
- spark/src/main/scala/geotrellis/spark/io/file/FileAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/file/FileLayerDeleter.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopLayerDeleter.scala
- spark/src/test/scala/geotrellis/spark/io/PersistenceSpec.scala
Prior to this change, `delete` methods threw in any case where the reference to a layer happened to be faulty. This is based on metadata which, though always present in case of tile data (and necessary for its deletion), might not be present. Lacking this metadata, we should log information about the failure and delete any `_attribute` data we can.
> Relax safeguards on delete methods

- spark/src/main/scala/geotrellis/spark/io/avro/AvroRecordCodec.scala
Allows `AvroRecordCodec[Tile]` instead of `implicitly[AvroRecordCodec[Tile]]`, a pattern used a lot in the avro2spark PoC.
> A dash of API sugar to simplify summoning of implicit codec.

- raster/src/main/scala/geotrellis/raster/mapalgebra/focal/hillshade/SurfacePointCalculation.scala
> Optimization to avoid unspecialized Function3 usage

- proj4/src/main/scala/geotrellis/proj4/mgrs/MGRS.scala
- proj4/src/test/scala/geotrellis/proj4/mgrs/MGRSSpec.scala
Fixes #1650 after locationtech move.
> Add MGRS encode/decode support to proj4

- README.md
- docs/tutorials/etl-tutorial.rst
Fixes #1940 - mailing list link in README
Fixes #1817 - inconsistencies with the JSON paths in ETL tutorial
> Docs: Tweak ETL tutorial example paths

- spark/src/main/scala/geotrellis/spark/tiling/MapKeyTransform.scala
- spark/src/test/scala/geotrellis/spark/tiling/MapKeyTransformSpec.scala
Previously, `MapKeyTransform(Extent(0, 0, 1, 1), 2, 2).apply(-0.1,1.0)` erroneously yielded `SpatialKey(0, 0)`.  The relevant code has been fixed, and the above now correctly produces `SpatialKey(-1, 0)`.
> Allow MapKeyTransform to deal with points north and west of extent

- s3-test/src/test/scala/geotrellis/spark/io/s3/S3GeoTiffRDDSpec.scala
- s3-testkit/src/main/scala/geotrellis/spark/io/s3/testkit/MockS3Client.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffRDD.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3InputFormat.scala
Also added ability for test to check last ListObjectRequest on MockS3Client.
Fixes #2044
> Added delimiter option to S3InputFormat and S3GeoTiffRDD.

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReaderSpec.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/TiffTags.scala
Fixes #1574
When dealing with GeoTiffs that use ModelTiepointTag and ModelPixelScaleTag to define their coordinate transform, one must take into account whether the raster is considered `PixelIsPoint`. If this is the case, the tie point references the center of the cell, and the extent needs to be adjusted.
This approach is taken by GDAL, see here: https://github.com/OSGeo/gdal/blob/7480b720aa74c87d63d1fbf563373dc7c24fa191/gdal/frmts/gtiff/gt_wkt_srs.cpp#L2722
> Fixed geotiff reading for tie point and PixelIsPoint

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReaderSpec.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/LazySegmentBytes.scala
Fixes #1959
The problem here was that we were using the same ByteReader extension method that we use for TiffTag reading to read the segment bytes. The TiffTag bytes have a property that if the length is less than 4 bytes, the value is stored inside the offset field. This property does not apply to segment bytes, so I refactored LazySegmentBytes so that it uses it's own straightforward byte reading code. ArraySegmentBytes delegates to LazySegmentBytes, so this fixes both streaming and non-streaming cases.
> LazySegmentBytes fix: always read bytes at the offset

- s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffRDD.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffRDD.scala
- spark/src/test/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffRDDSpec.scala
Fixes #1958 without a significant API changes. This PR introduces a `keyTransform: (URI, I) => K` function to have ability to read necessary metadata from files paths, and to modify `Input key`.
> HadoopGeoTiffRDD and S3GeoTiffRDD add overloads to use file names in keys

- s3/src/main/scala/geotrellis/spark/io/s3/S3LayerDeleter.scala
S3LayerDeleter can incorrectly delete keys since it is based on a wildcard pattern.
For example:
If you have multiple keys like 
```
1/files
10/files
```
and you delete an entry with the key `1` then it will also delete `10/files` Appending the extra `/` will perform the task as expected
> Fix issue with S3LayerDeleter deleting files outside of layer

- raster-test/src/test/scala/geotrellis/raster/render/ColorMapSpec.scala
- raster/src/main/scala/geotrellis/raster/render/ColorMap.scala
- raster/src/main/scala/geotrellis/raster/render/png/PngColorEncoding.scala
`IntCachedColorMap` implementation was not covered by unit tests and turned out to be incorrect.
This PR adds unit tests for its usage and changes the behavior to something that works.
It looks like this class fell through some cracks in the refactors. In reality it leans on implementation of `FastMapHistogram` to convert pixels directly to colors, which uses a hash table lookup.
In effect we get `eC` color encoding instead of `Log` which is provided by `IntColorMap`
> Fix usage of IntCachedColorMap in Indexed PNG encoding

- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraRDDWriter.scala
Ensure keyspace exists, that could cause problems in case of different attribute store and catalog key spaces.
> Ensure keyspace exists in CassandraRDDWriter

- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffRDD.scala
- spark/src/test/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffRDDSpec.scala
Currently, `HadoopGeoTiffRDD` has an issue where setting both `maxTileSize` and `numPartitions` causes the reading to fail. This is due to a serialization problem where the default serializer cannot serialize/deserialize `org.apache.hadoop.fs.Path`. To fix this problem, the `Path`s were converted to `URI`s during the transformation of the input key.
This resolves #2103
> Resolved Path java serialization issue in HadoopGeoTiffRDD

- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopAttributeStore.scala
Fixes #2113 
What was happening is, because the attributePath was being stored as a local path, the `attributePath` method returned the relative path as well; when being compared to listed paths in `layerExists`, it would always fail the match. This didn't surface itself beforehand because we would always use absolute paths with HadoopLayer types; this prevents a problem if a user decides to user a relative path when the default filesystem is local.
This was a bit tough to capture in a unit test, but I did test this manually against geotrellis-landsat-tutorial.
> Get absolute path for attributePath

- .travis/build-and-test-set-2.sh
- publish/publish-to-sonatype.sh
- scripts/geowaveTestDB.sh
This contains GeoWave-related updates.
Tests pass locally:
```
Script started on Tue 04 Apr 2017 01:14:52 PM EDT
[1m[3m%[23m[1m[0m                                                                                                                                                                                                                                              
[0m[23m[24m[Jsrc/geotrellis% [K[?1h=HHOSTALIASES=/tmp/hostaliases ./sbt -J-Xmx2G "project geowave" test[?1l>
[0m[[0minfo[0m] [0mLoading project definition from /home/likewise-open/AZVA-INT/jmcclain/local/src/geotrellis/project[0m
[0m[[0minfo[0m] [0mResolving key references (15816 settings) ...[0m
[0m[[0minfo[0m] [0mSet current project to geotrellis (in build …
```
> GeoWave Update

- s3-test/src/test/scala/geotrellis/spark/io/s3/S3InputFormatSpec.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3InputFormat.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/config/json/ConfigFormats.scala
> S3InputFormat - bucket names support period and dashes

- CONTRIBUTING.md
We need a contributing doc in the root folder as per the Eclipse guidelines; looks like it was removed and placed into the docs; so this readds it.
> Added back CONTRIBUTING.md

- s3-test/src/test/scala/geotrellis/spark/io/s3/S3AttributeStoreSpec.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3AttributeStore.scala
Signed-off-by: lossyrob <rdemanuele@gmail.com>
> S3AttributeStore now handles ending slashes in prefix.

- raster-test/src/test/scala/geotrellis/raster/CellTypeSpec.scala
- raster/src/main/scala/geotrellis/raster/CellType.scala
to make it the authoritative representation of cell type, over `toString`.
Moved `name` resolution to companion object to make it symmetric with `fromName` implementation.
In the previous implementation, inheritance was used as the means of having different values of `name` per type. That caused problems when trying to come up with a general solution based on calling `super` to generate derivatives, since self-types were used over direct inheritance. Having the to/from name handling in the companion also keeps coupled implementations closer to each other.
cc: @moradology 
Signed-off-by: Simeon H.K. fitch <fitch@astraea.io>
> Reorganized handling of `CellType.name`

- spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/config/Output.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/SpatialRenderOutput.scala
- spark/src/main/scala/geotrellis/spark/KeyBounds.scala
- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
- spark/src/main/scala/geotrellis/spark/tiling/CutTiles.scala
- util/src/main/scala/geotrellis/util/LazyLogging.scala
During ETL process there are two ways in which the job specification can cause increase in resolution:
- When `maxZoom` parameter forces a higher than necessary level using `ZoomedLayoutScheme`
- When `LayoutDefinition` is provided that has higher resolution than source imagery
This is possible both in per-tile reprojected and buffered reproject methods.
If the increase in resolution is significant it will dramatically increase the size of the partitions, which were originally mapped to source imagery. Past certain point the partitions become too large to be processed.
For per-tile reproject this PR handles the logic in `geotrellis.spark.etl.Etl` class by inspecting the difference in resolutions of pre-tiled metadata and post-tiled metadata.
However in buffered reproject the check must …
> Repartition in ETL when re-tiling increases layer resolution

- pointcloud/src/main/scala/geotrellis/pointcloud/spark/triangulation/BoundaryDelaunay.scala
- pointcloud/src/main/scala/geotrellis/pointcloud/spark/triangulation/CoordinatePredicates.scala
- pointcloud/src/main/scala/geotrellis/pointcloud/spark/triangulation/StitchedDelaunay.scala
- pointcloud/src/test/scala/geotrellis/pointcloud/spark/triangulation/BoundaryDelaunaySpec.scala
- pointcloud/src/test/scala/geotrellis/pointcloud/spark/triangulation/StitchedDelaunaySpec.scala
- vector-test/src/test/scala/spec/geotrellis/vector/triangulation/DelaunayTriangulationSpec.scala
- vector/src/main/java/geotrellis/vector/ShewchuksDeterminant.java
- vector/src/main/scala/geotrellis/vector/RobustPredicates.scala
- vector/src/main/scala/geotrellis/vector/triangulation/DelaunayStitcher.scala
- vector/src/main/scala/geotrellis/vector/triangulation/DelaunayTriangulation.scala
- vector/src/main/scala/geotrellis/vector/triangulation/TriangulationPredicates.scala
In order to enable distributed Delaunay triangulations, we opted to allow triangulations defined over non-overlapping extents to be "stitched" together.  This requires, for each extent, the eight neighboring triangulations to be made available to the process.  Given that triangulations are actually rather heavy in terms of memory consumption, this can lead to large volumes of shuffle traffic in practice.  For example, when dealing with 3GB of pointcloud input (.LAS files), the stitch observes on the order of a terabyte of shuffle reads/writes.
This is unnecessary.  During the stitch, only a thin layer of triangles around the boundary are actually used.  We have had an implementation of the stitching algorithm using BoundaryDelaunay objects in the codebase for some time; however, the …
> Fix errors in StitchedDelaunay when used with BoundaryDelaunay extracts

- spark/src/main/scala/geotrellis/spark/KeyBounds.scala
Resolves: https://github.com/locationtech/geotrellis/issues/2160
@metasim This should provide enough context to discuss validity further. Looking through the code it looks like the usage from `map` and `flatMap` is gone, so there may be a discussion if they have a useful shape at all. 
The original reasoning was that `Bounds` captures the idea of optionality where our version of `None`, which is `EmptyBounds` can still be used as valid arguments for `include`, `combine` and `intersect` removing the need to do these case checks at call sites since they all follow the same pattern.
Given that `map` and `flatMap` should expose the contents of `Some` case, which is really a tuple of `minKey` and `maxKey` providing them as `KeyBounds` instead of `Tuple2` is more descriptive and allows for …
> Documentation for KeyBounds

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloLayerReader.scala
Detects an "all the things" (full key bounds) query, eliminating a problem with heavy memory footprint when large number of key ranges are generated and then converted into one large query string.
Alternative to #2163
> Added conditional to key bounds decomposition to detect full bounds query in Acccumulo.

- vector/src/main/scala/geotrellis/vector/Geometry.scala
Patchy patch!
Calling down to JTS's `isEmpty` is faster than doing, say:
```scala
val mp: MultiPoint = ...
mp.points.isEmpty
```
> Expose `isEmpty` for Geometries

- raster-test/src/test/scala/geotrellis/raster/io/json/CellSizeJsonSpec.scala
- raster/src/main/scala/geotrellis/raster/io/json/Implicits.scala
> [BACKPORT 1.1] CellSize values should not be truncated to integer when parsing from Json.

- raster/src/main/scala/geotrellis/raster/ArrayTile.scala
> [Backport 1.1] In ArrayTile.convert, debug instead of warn against floating point data loss.

- raster/src/main/scala/geotrellis/raster/distance/EuclideanDistanceTile.scala
- raster/src/main/scala/geotrellis/raster/distance/EuclideanDistanceTileMethods.scala
- raster/src/main/scala/geotrellis/raster/distance/Implicits.scala
- spark/src/main/scala/geotrellis/spark/distance/EuclideanDistanceRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/distance/Implicits.scala
- vector/src/main/scala/geotrellis/vector/triangulation/DelaunayTriangulationMethods.scala
- vector/src/main/scala/geotrellis/vector/triangulation/Implicits.scala
- vector/src/main/scala/geotrellis/vector/voronoi/Implicits.scala
- vector/src/main/scala/geotrellis/vector/voronoi/VoronoiDiagram.scala
- vector/src/main/scala/geotrellis/vector/voronoi/VoronoiMethods.scala
Method extensions existed in the Delaunay interface for working with `Coordinates`.  This isn't always the most useful interface.  This PR adds other modes of interaction including `Double` pairs and triples and `MultiPoint`s.
> Extend Delaunay/Voronoi/EuclideanDistance interfaces to work with other types

- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraRDDReader.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3RDDReader.scala
- spark-testkit/src/main/scala/geotrellis/spark/testkit/TestEnvironment.scala
- spark/src/main/scala/geotrellis/spark/io/file/FileRDDReader.scala
This nasty bug was caused by some unfortunate variable naming and a bad merge; tiles were being read in for these to backends per-partition. Our unit tests had only 1 partition per RDD so it was never caught.
Fixes #2140
> Fix issue with duplicate tiles being read for File and Cassandra backends

- spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala
* Fixes incorrect metadata update in a `per-tile` reprojection case
* Always `nearest-neighbor` resample method was used
> ETL typos fix

- vector/src/main/scala/geotrellis/vector/voronoi/VoronoiDiagram.scala
Voronoi cells are represented by a collection of line segments and rays.  When constructing Voronoi diagrams from linear triangulations, each edge in the triangulaton can be conceived of as generating a pair of opposite and opposing rays emanating from the midpoint of the triangulation edge.  However, when generating a Polygon from a Voronoi cell, the process is to clip a seed region to the boundaries of the Voronoi cell.  The opposite and opposing rays represent the same clipping constraint, which can in practice lead to broken output Polygons. Here we simplify the cell construction process to only include one of the two bounding rays.  This resolves the observed bug in clipping.
> Remove redundant elements in construction of Voronoi from linear triangulations

- raster/src/main/scala/geotrellis/raster/distance/EuclideanDistanceTile.scala
- spark/src/main/scala/geotrellis/spark/distance/EuclideanDistance.scala
- spark/src/test/scala/geotrellis/spark/distance/EuclideanDistanceSpec.scala
This PR offers two minor updates to the Euclidean distance interface: (1) allow the cell types of the output rasters to be specified, and (2) do not produce tiles in the spark implementation for cells which do not contain any meaningful information (these were formerly explicit NoData tiles).
> Small updates to Euclidean distance

- doc-examples/src/main/scala/geotrellis/doc/examples/spark/EuclideanDistanceExamples.scala
- spark/src/main/scala/geotrellis/spark/distance/EuclideanDistance.scala
- spark/src/test/scala/geotrellis/spark/distance/EuclideanDistanceSpec.scala
The EuclideanDistance operation provided in the spark package is intended for use with very large, dense point sets (namely LiDAR point clouds).  These have the problem of being too large to triangulate as a whole.  This PR adds the SparseEuclideanDistance object, which allows ED tiles to be generated when the input point set is small and/or sparse.  This will handle regions in the tiling with contiguous regions of empty tiles without error.  An example is also included in doc-examples which demonstrates the failure mode of the dense EuclideanDistance operator.
> Added broadcasting version of EuclideanDistance

- project/Dependencies.scala
- spark-etl/build.sbt
- spark-etl/src/main/resources/input-schema.json
- spark-etl/src/main/scala/geotrellis/spark/etl/config/BaseEtlConf.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/config/ConfigParse.scala
A lightweight https://github.com/networknt/json-schema-validator is used instead of https://github.com/java-json-tools/json-schema-validator.
Were applied some changes into the input schema definition (it was incorrect). 
Some changes into printing validation error messages were added (logger used, error messages are red)
A source with tests for different json schema validators in different languages:
https://github.com/json-schema-org/JSON-Schema-Test-Suite
> Move to a different Json Schema validator

- .travis/hbase-install.sh
HBase update in a separate PR, as https://github.com/locationtech/geotrellis/pull/2226 is blocked by CQs.
> Bump up HBase test DB

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloLayerReader.scala
Fixes #2218
Slightly different than the fix suggested in the issue; in that this checks to see that the query bounds covers the layer bounds, instead of checking to see if it's equivalent to the key index bounds.
> Fixed logic in decompose function

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/MultibandGeoTiff.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/package.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/TiffTags.scala
Ass reported by @stevekuo on Gitter:
> I'm seeing GeoTiffOptions(DeflateCompression) being correctly observed with SinglebandGeoTiff, but ignored with MultibandGeoTiff.
> Roughly my code is
```scala
val geotiff = SinglebandGeoTiff(tile, extent, crs, Tags.empty, GeoTiffOptions(DeflateCompression))
// OR
val geotiff = MultibandGeoTiff(tile, extent, crs, Tags.empty, GeoTiffOptions(DeflateCompression))
val geotiffArray = GeoTiffWriter.write(geotiff)
val stream = new ByteArrayInputStream(geotiffArray)
```
> I then write out to a file. Using gdalinfo, the single band is COMPRESSION=DEFLATE, where as the multi band is not compressed.
This fixes the oversight that was causing the GeoTiff to be written as uncompressed.
> Fix writing multiband GeoTiff with compression

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/BigTiffSpec.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReader.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/TiffTagsReader.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/util/ByteReaderExtensions.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/util/TiffTagOffsetSize.scala
Fixes #2241 
The TIFF Spec has a condition that is an optimization, but has caused a lot of issues.
A TIFF-tag is structured like `[code, type, length, offset]`. The `code` determines what tag it is, the `type` is the datatype such as Byte or Double, the `length` is the number of elements in the array of values, and the `offset` is the offset in the file where the values live.
If the value of the data is a small size, the value can be packed into the space that stores the offset. In this way, the tiff tag reads as `[code, type, length, value]` instead. This only happens if the byte size of `type`, multiplied by the `length` of the data, is less than the byte size of the `offset` value. In the regular TIFF case, the offset is a 4-byte wide `Int`, so any value that can be stored in 4 or …
> Fixed issue with BigTiff vs non-BigTiff offset value packing

- build.sbt
Do not add Credentials SBT Setting if file doesn't exist.
Removes the `[warn] Credentials file /Users/eugene/.ivy2/.credentials does not exist` during `compile`
> Remove missing credentials warning during compile

- s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffRDD.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3InputFormat.scala
This is a partial backport of #2233
> [BACKPORT 1.1] Fixes to #2231 and #2232

- vector-test/src/test/scala/spec/geotrellis/vector/voronoi/VoronoiDiagramSpec.scala
- vector/src/main/scala/geotrellis/vector/voronoi/VoronoiDiagram.scala
Voronoi cells are constructed by creating a boundary representation in terms of half planes which are then used to clip the extent polygon.  We were previously including half planes for degenerate cell boundaries which were introducing duplicate vertices to the clipped polygons that were causing problems for the rasterizer and negatively affecting EuclideanDistanceTile.  
This PR adjusts numerical tolerances to make sure that degenerate edges are not included.  We use a more conservative value for the tolerance that may interpret valid edges as degenerate.  This might result in losing some edges, but the failure mode will be to have corners where the desired result should have been a very slightly truncated corner.  A mild problem that should only appear very rarely.
Signed-off-by: …
> Fixed problematic polygons in Voronoi diagram generation

- spark/src/main/scala/geotrellis/spark/io/LayerFilter.scala
- spark/src/test/scala/geotrellis/spark/io/LayerQuerySpec.scala
This PR adds the ability to query a GeoTrellis layer by Line and MultiLine, much like we can already query by Polygon and MultiPolygon.
For instance,
```scala
val poly: Polygon = ???
val rdd = 
layerReader
.query[SpatialKey, Tile, TileLayerMetadata[SpatialKey]](Layer("name", zoom))
.where(Intersects(poly))
.result
```
will give you all tiles that intersect with the polygon, where as now
```scala
val poly: Polygon = ???
val rdd = 
layerReader
.query[SpatialKey, Tile, TileLayerMetadata[SpatialKey]](Layer("name", zoom))
.where(Intersects(poly.exterior))
.result
```
will give you all tiles that intersect just the exterior of the polygon.
> Added Intersction by Line and MultiLine capability to LayerFilters

- raster/src/main/scala/geotrellis/raster/io/geotiff/util/ByteReaderExtensions.scala
This PR makes it so that `getSignedByteArray` does not reset to its old position after reading.
Resolves #2268
> getSignedByteArray BugFix

- raster/src/main/scala/geotrellis/raster/io/geotiff/StorageMethod.scala
This PR makes it so that `StorageMethod` and its sub-classes now extend `Serializable`. This is needed as not having it be serializable causes errors when trying to create `MultibandGeoTiff`s in GeoPySpark.
Error output:
```
E                   Caused by: java.io.NotSerializableException: geotrellis.raster.io.geotiff.Striped
E                   Serialization stack:
E                   	- object not serializable (class: geotrellis.raster.io.geotiff.Striped, value: geotrellis.raster.io.geotiff.Striped@3049fd69)
E                   	- field (class: geotrellis.raster.io.geotiff.GeoTiffOptions, name: storageMethod, type: class geotrellis.raster.io.geotiff.StorageMethod)
E                   	- object (class geotrellis.raster.io.geotiff.GeoTiffOptions, …
```
> StorageMethod is Now Serializable

- raster/src/main/scala/geotrellis/raster/io/geotiff/compression/Compression.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/compression/DeflateCompression.scala
This PR makes `DeflateCompression` serializable. This is needed as trying to use this form of compression in GeoPySpark fails.
```
Caused by: java.io.NotSerializableException: geotrellis.raster.io.geotiff.compression.DeflateCompression$
E                   Serialization stack:
E                   	- object not serializable (class: geotrellis.raster.io.geotiff.compression.DeflateCompression$, value: geotrellis.raster.io.geotiff.compression.DeflateCompression$@5a2b1895)
E                   	- field (class: geotrellis.raster.io.geotiff.GeoTiffOptions, name: compression, type: interface geotrellis.raster.io.geotiff.compression.Compression)
E                   	- object (class geotrellis.raster.io.geotiff.GeoTiffOptions, GeoTiffOptions(Tiled(256,256),geotrellis.raster.io.geotiff.compression.Def …
```
> DeflateCompression is Now Serializable

- raster/src/main/scala/geotrellis/raster/summary/polygonal/DoubleHistogramSummary.scala
Fixes polygonal summarization of double-valued tiles
> Use getDouble instead of get in DoubleHistogramSummary

- docs/CHANGELOG.rst
- raster-test/src/test/scala/geotrellis/raster/GridBoundsSpec.scala
- raster/src/main/scala/geotrellis/raster/GridBounds.scala
- s3-test/src/test/scala/geotrellis/spark/io/s3/S3GeoTiffRDDSpec.scala
- spark-testkit/src/main/scala/geotrellis/spark/testkit/TileLayerRDDBuilders.scala
- spark/src/main/scala/geotrellis/spark/density/RDDKernelDensity.scala
- spark/src/main/scala/geotrellis/spark/merge/RDDLayoutMerge.scala
- spark/src/main/scala/geotrellis/spark/resample/ZoomResample.scala
- spark/src/main/scala/geotrellis/spark/tiling/CutTiles.scala
- `size` returning a `Long` instead of `Int` is likely backwards incompatible.
- I wanted to make `coords` return an `Iterator` instead of a `Stream`, but one single function (`RDDKernelDensity.pointFeatureToSpatialKey`) in GT requires the output of a `for` over `coords`
to be a `Seq`, which `Array` can be cast to and `Iterator` cannot.
- I ingested a 60k-by-60k GeoTiff after making this change, and while the ingest itself was very strange (took forever to process, was all single core, no I didn't mess up the Spark config), it did succeed. 
Closes #2265 .
> Don't constrain GridBounds size to IntMax x IntMax

- accumulo/src/main/resources/META-INF/services/geotrellis.spark.io.ValueReaderProvider
- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloLayerProvider.scala
- accumulo/src/test/scala/geotrellis/spark/io/accumulo/AccumuloLayerProviderSpec.scala
- cassandra/src/main/resources/META-INF/services/geotrellis.spark.io.ValueReaderProvider
- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraLayerProvider.scala
- cassandra/src/test/scala/geotrellis/spark/io/cassandra/CassandraLayerProviderSpec.scala
- docs/guide/tile-backends.rst
- hbase/src/main/resources/META-INF/services/geotrellis.spark.io.ValueReaderProvider
- hbase/src/main/scala/geotrellis/spark/io/hbase/HBaseLayerProvider.scala
- hbase/src/test/scala/geotrellis/spark/io/hbase/HBaseLayerProviderSpec.scala
- s3-test/src/test/scala/geotrellis/spark/io/s3/S3LayerProviderSpec.scala
- s3/src/main/resources/META-INF/services/geotrellis.spark.io.ValueReaderProvider
- s3/src/main/scala/geotrellis/spark/io/s3/S3LayerProvider.scala
- spark-etl/build.sbt
- spark/src/main/resources/META-INF/services/geotrellis.spark.io.ValueReaderProvider
- spark/src/main/scala/geotrellis/spark/io/ValueReader.scala
- spark/src/main/scala/geotrellis/spark/io/ValueReaderProvider.scala
- spark/src/main/scala/geotrellis/spark/io/file/FileLayerProvider.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopLayerProvider.scala
- spark/src/test/scala/geotrellis/spark/io/file/FileLayerProviderSpec.scala
- spark/src/test/scala/geotrellis/spark/io/hadoop/HadoopLayerProviderSpec.scala
Closes: https://github.com/locationtech/geotrellis/issues/2281
> ValueReaderProvier

- docs/guide/spark.rst
This PR fixes two typos I encountered in the ReadTheDocs docs.
"Decedent" turns out to be a real word but unless it's a term of art wrt Spark it seemed not to be the right one here.
Trivial change, but:
* verify that these fixes are correct
* verify that the docs still build?
> Fix two typos in ReadTheDocs docs

- spark/src/main/scala/geotrellis/spark/pyramid/Pyramid.scala
The main objective of this PR is to ensure that pyramid operation provides `Partitioner` if one is provided. This was not the case because final operation performed an `RDD.map`.
The related refactor is to merge pixels into target pyramid tile in the combine functions, rather than accumulating them in a list. This will any tiles that share a source partition will be resampled and merged on the map side, possibly reducing the shuffle volume.
> Pyramid operation preserves partitioning

- s3-test/src/test/scala/geotrellis/spark/io/s3/S3GeoTiffRDDSpec.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffRDD.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3InputFormat.scala
Fixed incorrect S3GeoTiffRDD behavior when both partitionBytes & numPattition options set.
Fixes #2307
> Fix S3GeoTiffRDD behavior with some options. 

- s3-test/src/test/scala/geotrellis/spark/io/s3/S3LayerProviderSpec.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3LayerProvider.scala
This was causing null errors when trying to read from a catalog like `s3://some-catalog-bucket`
> Fixed issue with S3 URI not having a key prefix

- spark/src/main/scala/geotrellis/spark/io/ValueReader.scala
Following the change to the SPI-based ValueReader URI construction method, it became clear that the attributeStore kept by each ValueReader implementation should be made accessible through the ValueReader interface, as we are now no longer sure what type of ValueReader we've constructed.  This PR makes that change to the interface.
> Make attributeStore accessible through ValueReader

- spark/src/main/scala/geotrellis/spark/io/LayerFilter.scala
- spark/src/test/scala/geotrellis/spark/io/LayerQuerySpec.scala
The non-overlapping check took upwards of 2 minutes in a case where I was querying a zoom 12 512x512 GlobalLayout for the state of Nevada. This is a nice thing to ensure, but not at that price. Make a note in the scaladocs for the implementor's responsibility to ensure non-overlapping KeyBounds.
> Removed inefficient LayerFilter check

- raster-test/src/test/scala/geotrellis/raster/GridBoundsSpec.scala
- raster/src/main/scala/geotrellis/raster/GridBounds.scala
This PR adds two new methods to `GridBounds`: `buffer` and `offset`. These will allow the user to create a new `GridBounds` by buffering around a preexisting one and to transpose a `GridBounds` to a new location, respectively.
> New GridBounds Methods: buffer and offset

- README.md
This PR adds the "Using GeoTrellis in Other Languages" section to the `README`. The purpose of this new section is to inform users that an alternative to GeoTrellis, GeoPySpark, exists if they are unable to use Scala.
> Added New Section to README

- raster-test/src/test/scala/geotrellis/raster/rasterize/RasterizerSpec.scala
- raster/src/main/scala/geotrellis/raster/rasterize/Rasterizer.scala
This adds 4-connected line drawing capability.
The API is "broken" in the sense that the line drawing subroutine now takes and pays attention to a potential `options` parameter whereas it did not before.  `Options.DEFAULT` preserves the original (8-connected) behavior, whereas 4-connected drawing is done when `options.sampleType == PixelIsArea`.
In terms of the API, it seemed as though the choice were
- This
- Awkwardly add something along side the existing API
- Extend the `Options` case class (in terms of invasiveness, seems >= the approach taken here)
This PR should probably either be closed or given the "2.0" label.
Also, while typing this PR I realized that it does not solve the [vector rasterization problem](https://github.com/locationtech/geotrellis/pull/2266) for which it was …
> 4-Connected Line Drawing

- spark/src/main/scala/geotrellis/spark/io/json/KeyFormats.scala
This PR fixes a typo in `SpaceTimeKey`'s deserialization exception message so it now displays the correct type.
This Pr resolves #2310
> Deserialization Exception Message Typo Fix

- s3/src/main/scala/geotrellis/spark/io/s3/package.scala
Fixes writing to an "empty named" folder, if s3 URI is with a trailing slash.
> Improve S3 makePath function

- proj4/src/main/scala/geotrellis/proj4/CRS.scala
- proj4/src/main/scala/geotrellis/proj4/ConusAlbers.scala
- proj4/src/main/scala/geotrellis/proj4/LatLng.scala
- proj4/src/main/scala/geotrellis/proj4/Sinusoidal.scala
- proj4/src/main/scala/geotrellis/proj4/WebMercator.scala
- proj4/src/main/scala/geotrellis/proj4/io/wkt/WKT.scala
- proj4/src/test/scala/geotrellis/proj4/CRSTest.scala
Added implementations for anonymous CRS implementations and singletons.
> Added requirement for `CRS` implementations to provide a readable `toString` representation.

- raster-test/src/test/scala/geotrellis/raster/GridBoundsSpec.scala
- raster/src/main/scala/geotrellis/raster/GridBounds.scala
- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
- spark/src/test/scala/geotrellis/spark/io/AllOnesTestTileFeatureSpec.scala
- spark/src/test/scala/geotrellis/spark/io/AllOnesTestTileSpec.scala
- spark/src/test/scala/geotrellis/spark/io/CoordinateSpaceTimeSpec.scala
- spark/src/test/scala/geotrellis/spark/io/CoordinateSpaceTimeTileFeatureSpec.scala
- spark/src/test/scala/geotrellis/spark/io/LayerQuerySpec.scala
- spark/src/test/scala/geotrellis/spark/resample/ZoomResampleSpec.scala
This PR replaces `size` to `sizeLong` and `coords` to coordsIter` in the GeoTrellis code base. In addition, a bug has been fixed in `sizeLong` so that it will now produce the correct result.
This PR resolves #2314
> sizeLong Bug Fix and Replacement of Deprecated GridBound Methods

- raster-test/src/test/scala/geotrellis/raster/summary/polygonal/HistogramSpec.scala
- raster-test/src/test/scala/geotrellis/raster/summary/polygonal/MaxSpec.scala
- raster-test/src/test/scala/geotrellis/raster/summary/polygonal/MeanSpec.scala
- raster-test/src/test/scala/geotrellis/raster/summary/polygonal/MinSpec.scala
- raster-test/src/test/scala/geotrellis/raster/summary/polygonal/SumSpec.scala
- raster/src/main/scala/geotrellis/raster/package.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/DoubleHistogramSummary.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/Implicits.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/IntHistogramSummary.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/MaxSummary.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/MeanSummary.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/MinSummary.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/MultibandTilePolygonalSummaryHandler.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/MultibandTilePolygonalSummaryMethods.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/SinglebandTilePolygonalSummaryMethods.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/SumSummary.scala
- spark/src/main/scala/geotrellis/spark/summary/polygonal/Implicits.scala
- spark/src/main/scala/geotrellis/spark/summary/polygonal/PolygonalSummaryMultibandTileLayerCollectionMethods.scala
- spark/src/main/scala/geotrellis/spark/summary/polygonal/PolygonalSummaryMultibandTileLayerRDDMethods.scala
- spark/src/test/scala/geotrellis/spark/summary/polygonal/HistogramSpec.scala
- spark/src/test/scala/geotrellis/spark/summary/polygonal/MaxDoubleSpec.scala
- spark/src/test/scala/geotrellis/spark/summary/polygonal/MaxSpec.scala
- spark/src/test/scala/geotrellis/spark/summary/polygonal/MeanSpec.scala
- spark/src/test/scala/geotrellis/spark/summary/polygonal/MinDoubleSpec.scala
- spark/src/test/scala/geotrellis/spark/summary/polygonal/MinSpec.scala
- spark/src/test/scala/geotrellis/spark/summary/polygonal/SumDoubleSpec.scala
- spark/src/test/scala/geotrellis/spark/summary/polygonal/SumSpec.scala
This PR adds the ability to find the polygonal sum of: a `MultibandTile`, an `RDD[(K, MultibandTile)]`, and `Seq[(K, MultibandTile)]`.
This PR resolves #2359
> Polygonal Summaries for MultibandTiles

- raster/src/main/scala/geotrellis/raster/rasterize/CellValue.scala
- spark/src/main/scala/geotrellis/spark/rasterize/RasterizeRDD.scala
- spark/src/test/scala/geotrellis/spark/rasterize/RasterizeRDDSpec.scala
This PR allows rasterization to store values at double precision (which is immediately useful for elevation rasters) and allows the z values to be stored with a provided `CellType`
> Allow rasterizer to store z value at double precision

- spark/src/main/scala/geotrellis/spark/io/LayerFilter.scala
- spark/src/test/scala/geotrellis/spark/io/LayerQuerySpec.scala
This PR makes it so that users can now query a geometry using a projected geometry. Meaning that if the given geometry is in a different projection than the data within the catalog, it will be reprojected to the correct projection.
This PR resolves #2165
> Query Catalog by Projected Geometry

- docs/guide/vectors.rst
- vector/build.sbt
- vector/src/main/resources/reference.conf
- vector/src/main/scala/geotrellis/vector/GeomFactory.scala
Fixes #2219 
Currently, `geotrellis.vector.GeomFactory` defaults to use JTS's floating `PrecisionModel`.  This means that all geometry will naturally be represented with double-precision coordinates.  This can lead to TopologyExceptions.  We want to be able to specify the precision model for numerically robust geometric code.  This PR uses the `com.typesafe.config` mechanisms to allow for an application.conf which specifies the precision model.
The config key `geotrellis.jts.precision.type` can take on one of three string values: "floating", "floating_single", and "fixed".  See the [JTS docs](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/PrecisionModel.html) for details.  In the event of a fixed precision model, the user may also give the scale parameter as …
> Allow specification of JTS precision model in application.conf

- build.sbt
Remove duplicate SCM Info that breaks Maven POMs
Signed-off-by: Austin Heyne <aheyne@ccri.com>
> Remove duplicate SCM Info

- spark/src/main/scala/geotrellis/spark/io/index/MergeQueue.scala
- spark/src/test/scala/geotrellis/spark/io/index/MergeQueueSpec.scala
These changes simplify `MergeQueue` and improve its efficiency.  Thank you to @mteldridge for noticing this issue.
Connects https://github.com/locationtech/geotrellis/issues/2358
> Allow Merge Queue To Handle Larger Inputs

- project/plugins.sbt
- scalastyle-config.xml
This PR adds the three code health plugins, their correct functioning was enabled by https://github.com/locationtech/geotrellis/pull/2389
At this time these tools can be run manually as the first step. 
The next step is to select an initial rule subset and force compliance from the codebase,
at which point they can be added to CI.
Signed-off-by: Eugene Cheipesh <echeipesh@gmail.com>
> Add Scalastyle Scapegoat and JaCoCo plugins

- spark/src/main/scala/geotrellis/spark/tiling/ZoomedLayoutScheme.scala
- spark/src/test/scala/geotrellis/spark/tiling/ZoomedLayoutSchemeSpec.scala
- util/src/main/scala/geotrellis/util/Haversine.scala
- util/src/test/scala/geotrellis/util/HaversineSpec.scala
- vector/src/main/scala/geotrellis/vector/Point.scala
> Haversine formula fix

- project/Version.scala
- project/plugins.sbt
- raster/build.sbt
- s3/build.sbt
- spark/build.sbt
This PR adds [migration-manager](https://github.com/typesafehub/migration-manager) support to the `raster`, `spark`, and `s3` projects. By running `mimaReportBinaryIssues` in `sbt`, a list of potential binary compatibility issues between the current and previous version of the project will be shown.
This is what the output looks like when there are issues found:
```
[info] geotrellis-spark: found 21 potential binary incompatibilities while checking against org.locationtech.geotrellis:geotrellis-spark_2.11:1.1.0 
[error]  * abstract method overwrite(java.lang.Object,org.apache.spark.rdd.RDD,geotrellis.spark.io.avro.AvroRecordCodec,geotrellis.spark.Boundable,spray.json.JsonFormat,scala.reflect.ClassTag,geotrellis.spark.io.avro.AvroRecordCodec,scala.reflect.ClassTag,spray.json.JsonFormat,geot …
```
> migration-manager Support to GeoTrellis

- spark/src/main/scala/geotrellis/spark/CellGridLayoutCollectionMethods.scala
- spark/src/main/scala/geotrellis/spark/CellGridLayoutRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/SpatialKey.scala
- spark/src/main/scala/geotrellis/spark/crop/Crop.scala
- spark/src/main/scala/geotrellis/spark/io/LayerFilter.scala
- spark/src/main/scala/geotrellis/spark/merge/RDDLayoutMerge.scala
- spark/src/main/scala/geotrellis/spark/pyramid/Pyramid.scala
- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
- spark/src/main/scala/geotrellis/spark/resample/ZoomResample.scala
- spark/src/main/scala/geotrellis/spark/tiling/CutTiles.scala
- spark/src/main/scala/geotrellis/spark/tiling/MapKeyTransform.scala
`MapKeyTransform` is a "worker class", it does not itself represent data. It provides mechanisms for transformations involving `SpatialKey`s, namely:
- discovering the key corresponding to some Geometry
- discovering the `Extent` that corresponds to some key
- discovering the set of keys (`GridBounds`) that corresponds to some Geometry envelope (an `Extent`)
Until now, each of these transformations occurred through a very overloaded `.apply` method, making `MapKeyTransform` somewhat of a mysterious black box. This PR adds sensibly named aliases for each of these transformations, like `keyToExtent: SpatialKey => Extent`.
If it's true that reducing API surface area increases discoverability and improves usability, is it necessary to have:
- both `apply: Point => SpatialKey` and `apply: …
> MapKeyTransform method aliases

- spark/src/main/scala/geotrellis/spark/package.scala
- spark/src/main/scala/geotrellis/spark/regrid/Implicits.scala
- spark/src/main/scala/geotrellis/spark/regrid/Regrid.scala
- spark/src/main/scala/geotrellis/spark/regrid/RegridMethods.scala
- spark/src/test/scala/geotrellis/spark/regrid/Regrid.scala
- spark/src/test/scala/geotrellis/spark/regrid/RegridSpec.scala
Fixes #2283 
When presented with a layer containing Tiles of a set resolution, it may be desirable to generate a layer with the same pixel data in a different tile resolution.  This will produce a layer over the same extent with the same cellSize but different KeyBounds.  The exact area of tile coverage may differ (i.e., regridding a 10X10 layout of 32x32 tiles to 100x100 tiles will yield a 4x4 layout, implying a 400x400 overall size—though the tiles on the right and bottom edges will have a large complement of no data cells), but the defined pixels will have the same content (that is, a stitch() of both layers will be the same, modulo the no data cells on the boundary required for padding).
> Apply new grid to existing layer

- docs/guide/examples.rst
- s3/src/main/scala/geotrellis/spark/io/s3/S3AttributeStore.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3ValueReader.scala
The `val s3Client` lines have been changed to `def s3Client` in both `S3ValueReader` and `S3AttributeStore`.  Examples of how to override them have been included, as well.
Connects https://github.com/locationtech/geotrellis/issues/2304
> Make S3 Capability More Configurable

- s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffInfoReader.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffRDD.scala
- s3/src/test/scala/geotrellis/spark/io/s3/S3GeoTiffRDDSpec.scala
- spark/src/main/scala/geotrellis/spark/io/GeoTiffInfoReader.scala
- spark/src/main/scala/geotrellis/spark/io/RasterReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffInfoReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffRDD.scala
- spark/src/test/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffRDDSpec.scala
> Filter GeoTiffRDDs by Geometry

- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTile.scala
This PR optimizes `GeoTiffMultibandTile.toArrayTile` for pixel interleave so that the segments will no longer be reloaded.
This PR resolves #2087
> Optimized toArrayTile for GeoTiffMultibandTile

- .gitignore
- spark/src/main/scala/geotrellis/spark/filter/Implicits.scala
- spark/src/main/scala/geotrellis/spark/filter/SpaceTimeToSpatialMethods.scala
- spark/src/main/scala/geotrellis/spark/filter/ToSpatial.scala
- spark/src/test/scala/geotrellis/spark/filter/TileLayerRDDFilterMethodsSpec.scala
I gave the methods the names `toSpatialEnsureUnique` and `toSpatialNoEnsureUnique` because they had to be put into a different implicit class than the `toSpatial` methods.  The reason that they had to be put into a different implicit class is because `reduceByKey` (needed to ensure unique keys) requires that `K` and `V` are members of the `ClassTag` class.  Adding that requirement to the existing implicit class would have changed the API.
Connects https://github.com/locationtech/geotrellis/issues/2368
> Time-Oblivious toSpatial Methods

- spark/src/main/scala/geotrellis/spark/io/json/KeyFormats.scala
This PR makes the `KeyFormats` serializable. This is needed as serialization issues due to these objects have been encountered when using GeoPySpark EMR.
```
Py4JJavaError: An error occurred while calling o32.tileToLayout.
: org.apache.spark.SparkException: Task not serializable
at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:298)
at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:288)
at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:108)
at org.apache.spark.SparkContext.clean(SparkContext.scala:2094)
at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:370)
at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:369)
at …
```
> KeyFormats are Now Serializable

- s3/src/test/scala/geotrellis/spark/io/s3/S3GeoTiffRDDSpec.scala
- spark/src/main/scala/geotrellis/spark/io/RasterReader.scala
- spark/src/test/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffRDDSpec.scala
@jbouffard found the `GeoTiffRDD` machinery to produce inconveniently-small tiles because tiles are currently no larger than segments (in particular the "all-ones" test image has segments of size 128x4 but he wanted tiles of size 256x256).
If the Hadoop and S3 range readers read only those segments which overlap the given window (and not all segments between the first and last segments that a window touches), then this change safely fixes the problem that Jake noticed.  If the range readers do not have that behavior, then perhaps tiles should be merged before they are returned (or perhaps not).
> Generate Largest-Possible Tiles

- spark/src/main/scala/geotrellis/spark/io/RasterReader.scala
The code was producing tiles of the second-largest possible size when `maxSize` was a factor of the `segment` size.  Now they are of the largest possible size.
@jbouffard please test.
Connects https://github.com/locationtech/geotrellis/issues/2437
> Fix Tile Sizes for maxTileSize < Segment Dimension

- raster/src/main/scala/geotrellis/raster/summary/polygonal/DoubleHistogramSummary.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/IntHistogramSummary.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/MaxSummary.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/MeanSummary.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/MinSummary.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/SumSummary.scala
- spark/src/test/scala/geotrellis/spark/summary/polygonal/HistogramSpec.scala
- spark/src/test/scala/geotrellis/spark/summary/polygonal/MaxDoubleSpec.scala
- spark/src/test/scala/geotrellis/spark/summary/polygonal/MaxSpec.scala
- spark/src/test/scala/geotrellis/spark/summary/polygonal/MeanSpec.scala
- spark/src/test/scala/geotrellis/spark/summary/polygonal/MinDoubleSpec.scala
- spark/src/test/scala/geotrellis/spark/summary/polygonal/MinSpec.scala
- spark/src/test/scala/geotrellis/spark/summary/polygonal/SumDoubleSpec.scala
- spark/src/test/scala/geotrellis/spark/summary/polygonal/SumSpec.scala
This PR fixes a bug that caused polygonal summaries on  `RDD[(K, MultibandTile)]`s and `Seq[(K, MultibandTile)]`s to return the incorrect result. The cause of this issue was in the `combineOp` operation in each `MultibandtTileSummary` object. This line from `MultibandTileSumDoubleSummary` shows the logic in `combineOp` that was the source of the error.
v1 zip v2 map { case (r1, r2) => SumDoubleSummary.combineOp(r1, r2) }
Because `v1` and `v2` can be different sizes, not all of the elements in each `Array` could be zipped together. Thus, leading to an incorrect number of elements being returned. The fix for this problem was to change `zip` to `zipAll`.
> MultibandTile PolygonalSummary Fix

- raster/src/main/scala/geotrellis/raster/rasterize/Rasterizer.scala
Also implicit conversion from to polygon has caused the doc generation to break
> Fix incomplete match warning in Rasterizer

- spark/src/main/scala/geotrellis/spark/regrid/Regrid.scala
- spark/src/test/scala/geotrellis/spark/regrid/RegridSpec.scala
Fixes #2459 
Minor repair of oversight w.r.t. tile layers with SpaceTimeKeys.
> Let spatiotemporal layers be regridded

- spark/src/main/scala/geotrellis/spark/clip/ClipToGrid.scala
- spark/src/main/scala/geotrellis/spark/clip/FeatureClipToGridMethods.scala
- spark/src/main/scala/geotrellis/spark/clip/GeometryClipToGridMethods.scala
- spark/src/main/scala/geotrellis/spark/rasterize/RasterizeRDD.scala
- spark/src/main/scala/geotrellis/spark/tiling/LayoutDefinition.scala
- spark/src/main/scala/geotrellis/spark/tiling/MapKeyTransform.scala
@echeipesh , we had decided that this was to be two PRs, but the changes to `MapKeyTransform` (the `Iterator -> Set` change) broke `ClipToGrid`. 
Closes #2453 .
> ClipToGrid Optimizations - Round 2

- spark/src/main/scala/geotrellis/spark/clip/FeatureClipToGridMethods.scala
- spark/src/main/scala/geotrellis/spark/clip/GeometryClipToGridMethods.scala
There were minor type typos in the injected methods' signatures that prevented them from being used with the built-in clipping functions.
> Fix types in injected ClipToGrid methods

- spark/src/main/scala/geotrellis/spark/buffer/BufferTiles.scala
- spark/src/main/scala/geotrellis/spark/buffer/BufferTilesMethods.scala
- spark/src/main/scala/geotrellis/spark/buffer/Direction.scala
- spark/src/main/scala/geotrellis/spark/buffer/Implicits.scala
- spark/src/test/scala/geotrellis/spark/buffer/BufferTilesSpec.scala
The current version of `BufferTiles` relies on specifying the `BufferSizes` via an `RDD[(K, BufferSizes)]`.  This method requires a `join` that really hams up the works.  This PR proposes an alternative pathway that takes a function of type `K => BufferSizes`.  Presumably, the former RDD method can be converted to this approach in nearly all cases.
> Lightweight BufferTiles operation

- s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffInfoReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffInfoReader.scala
An idea i had during making these changes, probably it makes sense to use in `{Hadoop | S3}GeoTiffInfoReader` `Options` object (from `{Hadoop | S3}GeoTiffRDD`)?
> Filter by extensions in S3GeoTiffInfoReader

- vector/src/main/scala/geotrellis/vector/Line.scala
- vector/src/test/scala/spec/geotrellis/vector/dissolve/DissoveMethodsSpec.scala
- vectortile/src/main/scala/geotrellis/vectortile/internal/package.scala
This PR adds two efficient functions for quickly grabbing either the first or last `Point` in a `Line`.
This lets us skip having to call `Line.points`, which is expensive.
> `Line.head` and `Line.last`

- spark/src/main/scala/geotrellis/spark/viewshed/IterativeViewshed.scala
- spark/src/main/scala/geotrellis/spark/viewshed/RDDViewshedMethods.scala
- spark/src/test/scala/geotrellis/spark/viewshed/IterativeViewshedSpec.scala
Hidden inside of `IterativeViewshed`, it wouldn't appear in Scaladocs and was a pain to import.
Ping @echeipesh .
> Make `Point6D` a top-level type

- raster/src/main/scala/geotrellis/raster/GridBounds.scala
- raster/src/main/scala/geotrellis/raster/io/ascii/ReadState.scala
- raster/src/main/scala/geotrellis/raster/reproject/SinglebandRasterReprojectMethods.scala
- raster/src/test/scala/geotrellis/raster/GridBoundsSpec.scala
- spark/src/main/scala/geotrellis/spark/io/AttributeCaching.scala
- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
Connects https://github.com/locationtech/geotrellis/issues/2294
Connects https://github.com/locationtech/geotrellis/issues/2315
Supersedes  https://github.com/locationtech/geotrellis/pull/2300
In the RDD reproject step instead of projecting tiles to their raster extent, re-projecting and collecting the metadata from the results, use the key bounds and the source layout to perform the the reproject on raster extent as a side compute operation. Because every pixel covered by the `RasterExtent` is in the data source we do not have to consider buffer sizes.
Tracking the changes in the pixel count on per-tile basis allows to get more accurate track of possible increase in raster layer memory footprint. The final tileToLayout operation is going to use the most resolute cellSize for the whole …
> Optimize TileRDDReproject

- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
Resolves: https://github.com/locationtech/geotrellis/issues/2484
Type-o caused using the source layout definition rather than target layout definition when generating reprojected metadata
> Fix TileRDDMetadata generation

- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReader.scala
- spark/src/main/scala/geotrellis/spark/io/RasterReader.scala
- spark/src/main/scala/geotrellis/spark/io/package.scala
MapKeyTransform is intended to provide context for tile layouts, not pixels.
Also replacing its current usage with RasterExtent
Connects: https://github.com/locationtech/geotrellis/issues/2486
(Discovered during investigation)
> Fix mapTransform on GeoTiffSegmentLayout

- spark/src/main/scala/geotrellis/spark/io/RasterReader.scala
Clipping the window extent in `RasterReader` to the raster extent would distort the cell size because it is allowed for the windows to be only intersect the GeoTiff being read, rather than being fully contained by it.
> Fix Extent Clamping in RasterReader

- project/Version.scala
Update master to 2.0.0, now that the 1.2 release branch is created.
__NOTE__ Now `master` and `1.2` will diverge. From now on, all changes that need to be backported to 1.2 must be merged into master first, and then cherry-picked from master to the 1.2 release branch.
> Updated version to 2.0.0

- raster/src/main/scala/geotrellis/raster/ArrayTile.scala
This PR fixes a bug where certain local operations between `ArrayTile`s and `ConstantTile`s won't produce the correct result.
This PR resolves #2494
> ArrayTile and ConstantTile Local Operations

- raster/src/main/scala/geotrellis/raster/ConstantTile.scala
This PR makes it so that the `CellType` is retained when converting a `ConstantTile` to an `ArrayTile`.
This PR resolves #2493
> ConstantTile to ArrayTile CellType Fix

- s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffRDD.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffRDD.scala
This PR updates the docstrings for the `Options` case class found in `S3GeoTiffRDD` and `HadoopGeoTiffRDD`. With these being up-to-date, it should now be easier to understand the behavior of both readers.
> Docstrings Update For S3GeoTiffRDD.Options and HadoopGeoTiffRDD.Options

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloInstance.scala
Please consider this pull request for inclusion in version 1.2.0, it allows people with a kerberized accumulo to use geopyspark.
> #2506 use KerberosToken if accumulo client is configured to use it

- raster/src/main/scala/geotrellis/raster/ConstantTile.scala
This PR changes the return type of `ConstantTile.map` from `IntConstantTile` to whatever instance of `ConstantTile` the caller is.
This PR resolves #2495
> ConstantTile.map Return Type

- raster/src/main/scala/geotrellis/raster/render/package.scala
We have simple tools for creating RGB(A) colors, but nothing comparable for the HSV color space.  HSV is a convenient space for building color maps for things like aspect, where the current stable of ramps doesn't make total sense.  This PR adds some simple HSV tools that allow for the production of RGB colors from HSV coordinates.
Note that the reverse translation from RGB to HSV is not provided.  If there is user demand, it can be quickly added.
> Added some utilities for dealing with HSV color space

- s3/src/main/scala/geotrellis/spark/io/s3/SaveToS3.scala
- s3/src/main/scala/geotrellis/spark/io/s3/SaveToS3Methods.scala
Uses `geotrellis.s3.threads.rdd.write` as default value, same as `S3RDDWriter`
> Add threads parameter to saveToS3 method

- project/Boilerplate.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/BitGeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/BitGeoTiffTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/ByteGeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/Float32GeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/Float64GeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffOptions.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffSegmentCollection.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffSegmentLayout.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/Int16GeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/Int32GeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/InterleaveMethod.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/LazySegmentBytes.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/SegmentTransform.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/UByteGeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/UInt16GeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/UInt32GeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReader.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/TiffTags.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/CroppedWindowedGeoTiffSpec.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/reader/GeoTiffTileSpec.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/reader/SinglebandGeoTiffReaderSpec.scala
- spark/src/main/scala/geotrellis/spark/io/GeoTiffInfoReader.scala
This PR is aimed at allowing subsets of bands to be pulled from GeoTiffs in a way that avoids reading undesired bands in the case that the GeoTiffs is stored with band interleave.
> Streaming band subsetting

- bench/src/main/scala/geotrellis/raster/reproject/RasterizingReprojectBench.scala
- raster/src/main/scala/geotrellis/raster/ProjectedRaster.scala
- raster/src/main/scala/geotrellis/raster/reproject/RasterRegionReproject.scala
- raster/src/test/scala/geotrellis/raster/reproject/RasterizeReprojectSpec.scala
- spark/src/test/scala/geotrellis/spark/reproject/TileRDDReprojectSpec.scala
The last implementation of `RasterRegionReproject` was 50 times slower than the classic raster reprojection code on a per-tile basis.  This PR aims to improve the performance by using the approximate `RowTransform` operations, which reduce the calls to proj4 by roughly an order of magnitude.  As these transforms are the bulk of the execution time, the net result should be a noticeable improvement in performance.
The general approach is to perform vector intersections with the target region, and convert the results into intervals which can be passed to `RowTransform.approximate`.  _[**NOTE:** If the polygon rasterizer had or has a way to generate each scanline separately, then this operation can most likely be sped up by hijacking that code.]_
The long and short of this PR comes down to …
> RasterRegionReproject benchmarks and optimization

- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffTile.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterTests.scala
For GeoTiffTiles with the equivalent of BitCellType, we pack the bits into bytes to write them out. This is the same as having a Byte type in GDAL with the `--co NBITS=1` flag set. We were writing these out in the incorrect order - our BitCellType bytes pack the bits in the reverse order of what a GeoTiff expects them to be. This PR fixes that.
> Fix issue with creating BitCellType GeoTiffs

- spark/src/main/scala/geotrellis/spark/io/GeoTiffInfoReader.scala
Consider `BitCellType` as bytes when deciding on appropriate number of partitions.
Its expected that this "over-estimate" is acceptable in all cases.
> Fix partitioning in a bit CellType case

- raster/src/main/scala/geotrellis/raster/reproject/RasterRegionReproject.scala
- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
This PR attempts to improve TileRDDReproject's performance by eliminating the merge step.  This is accomplished by using a mutable version of RasterRegionReproject to continually burn reprojected tiles into the same buffers.
> Optimize TileRDDReproject using mutable region reprojection

- .github/PULL_REQUEST_TEMPLATE.md
Before each release we have a scramble to udpate the changelog and double check the documentation. This led to a discussion that it would be good to have a reminder in form of a PR template. 
Overall the intent is:
- Help keep ongoing work well documented and easily discoverable
- Encourage thinking about REPL usage of GeoTrellis API
- Provide more clear information for participation in PR review
Possible drawbacks are increasing the burden of accepting community contributions and longer PR times. Soliciting feedback on this general idea and specifics of the template: @metasim @lossyrob @fosskers @moradology @hectcastro @rossbernet @jpolchlo @jamesmcclain 
--------
Brief description of what this PR does, and why it is needed.
Optional. Ancillary topics, caveats, …
> GitHub PR Template

- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/GeoKeyReader.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReaderSpec.scala
This commit makes the reading of GeoKeyDirectory entries more fault tolerant to
cover cases where the `NumberOfKeys` entry in the directory header has an
incorrect number of headers that is actually larger than the number of keys.
This manifested itself when attempting to read a tiff created by a geoprocessing
service from an ArcGIS server. The tiff could be read and parsed by other
tools (GDAL, QGIS) without issue but when attempting to open it with GeoTrellis
a `scala.MatchError` would be thrown in `readGeoKeyEntry`.
The workaround introduced here is that if a geokey is read and fails to match
then it likely means there are no longer any valid geokeys to read. I'm open to
other approaches to the workaround than the one offered here - one option is to
introduce a try/catch and only catch …
> Make GeoKeyDirectory parsing more fault tolerant

- docs/CHANGELOG.rst
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffSegmentLayout.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTileSpec.scala
`GeoTiffSegmentLayout.getIntersectingSegments` did not perform bound checking. 
As a result if `GridBounds` parameter was outside of the bounds of segment layout an out of bounds index would be returned, resulting in failed segment lookup.
This issue was discovered in process of performing buffered window reads: https://github.com/raster-foundry/raster-foundry/pull/2734/commits/49fe952e80bdd9c7d715ee952650a0149feb44be
- [-] ~`docs` guides update, if necessary~
- [-] ~New user API has useful Scaladoc strings~
> Fix out of bound segment index when reading over-buffered GeoTiff window

- raster/src/main/scala/geotrellis/raster/viewshed/R2Viewshed.scala
- spark/src/main/scala/geotrellis/spark/costdistance/IterativeCostDistance.scala
- vector/src/main/scala/geotrellis/vector/triangulation/DelaunayTriangulation.scala
- vectortile/src/main/scala/geotrellis/vectortile/Layer.scala
- vectortile/src/main/scala/geotrellis/vectortile/internal/package.scala
I discovered today that `.prepend` and `.append`, when used repeatedly (in a loop, say), are an order of magnitude slower than their operators, `+=:` and `+=` respectively:
```
[info] ListBufferBench.append10000     avgt    5  664.377 ± 10.276  us/op
[info] ListBufferBench.appendOp10000   avgt    5   58.740 ±  1.557  us/op
[info] ListBufferBench.prepend10000    avgt    5  848.419 ± 20.689  us/op
[info] ListBufferBench.prependOp10000  avgt    5   58.248 ±  1.813  us/op
```
Rule of thumb: Don't trust methods that take `a: A*` when you intend to only give it one thing.
This PR removes usage of these two methods for `ListBuffer` and `ArrayBuffer`.
> Avoid `ListBuffer.prepend` and `ListBuffer.append`

- docs/CHANGELOG.rst
- raster/src/main/scala/geotrellis/raster/transform/TransformTileMethods.scala
Floating point branch of the function performed assignment from target tile to target tile, rather than the from the source tile, resulting in NoData tiles.
- [-] `docs` guides update, if necessary
- [-] New user API has useful Scaladoc strings
- [-] Unit tests added for bug-fix or new feature
Closes #2507
> Fix Tile.flipHorizontal for floating point tiles

- spark/src/main/scala/geotrellis/spark/io/LayerFilter.scala
- spark/src/test/scala/geotrellis/spark/filter/TileLayerRDDFilterMethodsSpec.scala
Allow `Intersects` layer filter to be used with `Point`s, in addition to `Contains`. Allows for more generic handling of geometry in dynamic queries.
> Layer intersects point

- docs/CHANGELOG.rst
- spark/src/main/scala/geotrellis/spark/buffer/BufferTiles.scala
- spark/src/main/scala/geotrellis/spark/buffer/BufferTilesMethods.scala
- spark/src/main/scala/geotrellis/spark/mapalgebra/focal/FocalOperation.scala
- spark/src/main/scala/geotrellis/spark/mapalgebra/focal/FocalTileLayerRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/mapalgebra/focal/hillshade/HillshadeTileLayerRDDMethods.scala
- spark/src/test/scala/geotrellis/spark/mapalgebra/focal/PartitionerSpec.scala
This PR allows the user to set an optional `partitioner` parameter to all `RDD` `focal` methods. By default, no `partitioner` is set and thus the resulting `RDD` will have the same `partitioner` as its parent. If a user were to set a `partitioner`, then the `focal` operation will performed over the designated partitioning scheme.
Closes #2539
> Perserve/Set Partitioner When Performing Focal Operations on RDDs

- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
- spark/src/test/scala/geotrellis/spark/reproject/TileRDDReprojectSpec.scala
This PR makes it so that the resulting `RDD` of a `reproject` will have the same `Partitioner` as the source `RDD`. This is needed as it can help reduce the number of shuffle steps required, and in turn, improve the performance of a job.
> TileRDDReproject Will Now Preserve the Source RDD's Partitioner

- spark/src/main/scala/geotrellis/spark/rasterize/RasterizeRDD.scala
- spark/src/test/scala/geotrellis/spark/rasterize/RasterizeRDDSpec.scala
This PR fixes a bug in `RasterizeRDD.fromFeatureWithZIndex` that caused the resulting `RDD` to have no `Partitioner` regardless if it was set or not. [This](https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/rasterize/RasterizeRDD.scala?utf8=%E2%9C%93#L180) being the offending line that caused the `Partitioner` to be lost.
> Preserve Partitioner in RasterizeRDD.fromFeatureWithZIndex

- accumulo/src/main/resources/META-INF/services/geotrellis.spark.io.CollectionLayerReaderProvider
- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloLayerProvider.scala
- cassandra/src/main/resources/META-INF/services/geotrellis.spark.io.CollectionLayerReaderProvider
- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraLayerProvider.scala
- docs/CHANGELOG.rst
- hbase/src/main/resources/META-INF/services/geotrellis.spark.io.CollectionLayerReaderProvider
- hbase/src/main/scala/geotrellis/spark/io/hbase/HBaseLayerProvider.scala
- s3/src/main/resources/META-INF/services/geotrellis.spark.io.CollectionLayerReaderProvider
- s3/src/main/scala/geotrellis/spark/io/s3/S3LayerProvider.scala
- spark/src/main/resources/META-INF/services/geotrellis.spark.io.CollectionLayerReaderProvider
- spark/src/main/scala/geotrellis/spark/io/CollectionLayerReader.scala
- spark/src/main/scala/geotrellis/spark/io/CollectionLayerReaderProvider.scala
- spark/src/main/scala/geotrellis/spark/io/file/FileLayerProvider.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopLayerProvider.scala
A convenient method to build `ValueReader`s, `AttributeStore`s, and some other IO helper classes from the panoply of backends using a single URI has been a great convenience.  This PR extends this interface to provide access to `CollectionLayerReader`s via the same mechanism.  This is useful when one needs to make concurrent reads in a more conventional concurrency setting.
> Extend IO SPI to offer CollectionLayerReaders

- docs/CHANGELOG.rst
- spark/src/main/scala/geotrellis/spark/resample/Implicits.scala
- spark/src/main/scala/geotrellis/spark/resample/LayerRDDZoomResampleMethods.scala
- spark/src/main/scala/geotrellis/spark/resample/ZoomResample.scala
- spark/src/test/scala/geotrellis/spark/resample/ZoomResampleSpec.scala
This PR makes it so that both `TileLayerRDD`s and `MultibandTileLayerRDD`s can use the `ZoomResample` method.
> ZoomResmaple for MultibandTileLayerRDDs

- util/src/main/scala/geotrellis/util/StreamingByteReader.scala
- util/src/test/scala/geotrellis/util/StreamingByteReaderSpec.scala
When the StreamingByteReader calls `position(x)` it would previously set the buffer position on the chunk which would force loading the data for that chunk.
This change tracks the ByteReader position separately to prevent loading data prematurely.
> Fix issue where data could be loaded prematurely

- util/build.sbt
- util/src/main/scala/geotrellis/util/StreamingByteReader.scala
This PR fixes the missing logic that is required when tracking position independently from buffer position. 
It also adds some logic to:
- re-use existing buffer when incrementing to next read to prevent re-reading the same bytes
- absorb reads that can be satisfied with current buffer
- allow expanding the buffer on both sides and re-using existing bytes 
~- [ ] `docs/CHANGELOG.rst` updated, if necessary~
~- [ ] `docs` guides update, if necessary~
~- [ ] New user API has useful Scaladoc strings~
~- [ ] Unit tests added for bug-fix or new feature~
Connects: https://github.com/locationtech/geotrellis/pull/2564
> Optimize and Fix StreamingByteReader

- util/build.sbt
- util/src/main/scala/geotrellis/util/StreamingByteReader.scala
Unfortunately spark includes spire-math in its class path.
Spark version 2.1.0 depends on `org.spire-math.spire_2.11-0.7.4` and version 2.2.0 depends on `org.spire-math.spire_2.11-0.13.0`.  The implementation of `Interval` differs between the two.
This has already caused binary compatibility woes in GeoPySpark, likely this would keep happening to people. Its easy enough to refactor the `StreamingByteReader` to avoid the `Interval` usage altogether and instead lean on `scala.collection.immutable.NumericRange` as a class that has a `start` and an `end`.
> Refactor StreamingByteReader to avoid spire-math dependency

- docs/CHANGELOG.rst
- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReprojectMethods.scala
- spark/src/test/scala/geotrellis/spark/reproject/TileRDDReprojectSpec.scala
This PR adds an `Option[Partitioner]` parameter to `TileRDDReproject`. This will allow users to specify a `Partitioner` for the resulting `RDD` without having to do a `partitionBy`step afterwards . If no `Partitioner` is specified, then the resulting `RDD` will have the same `Partitioner` as its source.
```scala
val partitioner = new HashPartitioner(16)
rdd.reproject(ZoomedLayoutScheme(LatLng), Some(partitioner))
```
Closes #2554
> Option[Partitioner] Parameter for TileRDDReproject

- .travis/hbase-install.sh
- spark/src/main/scala/geotrellis/spark/io/AttributeCaching.scala
This PR changes code a bit to avoid Spark serialization problems caused by the cache value.
Closes #2591
@jbouffard can you look into it and how it works for you?
> Fix AttributeStore cache serialization issues

- raster/src/main/scala/geotrellis/raster/rasterize/polygon/FractionalRasterizer.scala
- vector/src/main/scala/geotrellis/vector/util/Intersection.scala
- vector/src/test/scala/spec/geotrellis/vector/util/IntersectionSpec.scala
In rare cases, a polygon-polygon intersection will result in a geometry collection.  In that situation, the FractionalRasterizer will fail.  This PR fixes that problem.
This PR also introduces a utility class in the vector library to assist in pulling salient information from intersection results.  This class can most likely be extended in useful ways, considering that intersections can have complicated type semantics and handling the many possible cases is error-prone.
> Fixes to fractional polygon rasterizer

- shapefile/src/main/scala/geotrellis/shapefile/ShapeFileReader.scala
Shapefiles are currently only read in from file paths. This PR allows the specification of a full URL as the source of the file. This covers cases for which a file specifier is not good enough—namely, for reading shapefiles from JAR resources.
> Allow shapefile reader to work from URL sources

- README.md
Moves from a one-off service someone was nice enough to stand up on Heroku to shields.io for our maven badge.
https://github.com/jirutka/maven-badges/issues/22#issuecomment-377363158
> Moved to shields.io for maven badge.

- accumulo/src/test/scala/geotrellis/spark/io/accumulo/AccumuloAttributeStoreSpec.scala
- docs/CHANGELOG.rst
- spark/src/main/scala/geotrellis/spark/io/AttributeCaching.scala
This PR resolves an issue where reading an attribute from the cache will fail if that attribute was read previously as a different type. For example, reading the `LayerHeader` from a layer and then reading an `AccumuloLayerHeader` from the same layer will result in a cast exception from trying to cast a `LayerHeader` as an `AccumuloLayerHeader`.
> Prevent Cast Exceptions When Reading From the Cache

- vector/src/main/scala/geotrellis/vector/Line.scala
Makes improvements to `Line` behavior. This changes `head` / `last` accessors to use JTS convenience functions for readability. More importantly, it removes a redundant `clone` operation when fetching vertices; the JTS `LineString` implementation already uses its `GeometryFactory` to create new `Point` instances from the underlying `Coordinate`s.
> Line memory improvements

- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiff.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffBuilder.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/MultibandGeoTiff.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/SinglebandGeoTiff.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/SinglebandGeoTiffSpec.scala
- spark/src/main/scala/geotrellis/spark/io/cog/COGLayer.scala
This approach avoids numerical differences in partial vs while tile resample.
They were particularly apparently with `NearestNeighbor` resample method.
Another change in this PR is the restriction that overviews will always have the same extent as the underlying raster. This change is to match GDAL behavior. It should be noted that it may cause stretching/squishing of the overview pixels where the overview pixel boundaries do not align with base layer pixel boundaries. This will happen when base raster pixel column/row count is not a multiple of the decimation factor.
In structured COG case however the base tile will always have a pixel count that is power of two and the case above will be avoided.
Additionally we trade memory for performance by forcing the base tile to ArrayTile before …
> Build GeoTiff overviews by resampling the whole base tile

- docs/CHANGELOG.rst
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTile.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTileSpec.scala
This PR fixes an oversight that caused `convert` and `interpretAs` to not work on `GeoTiffMultibandTile`s.
Closes #2616
> Uncompressed MultibandGeoTiffs Will Now Convert to the Correct CellType

- spark/src/main/scala/geotrellis/spark/io/file/cog/FileCOGValueReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/cog/HadoopCOGValueReader.scala
This PR makes it so that `FileCOGValueReader` and `HadoopCOGValueReader` will throw a `ValueNotFoundError` instead of a `java.io.FileNotFoundException` when trying to read a value that doesn't exist.
Closes #2607
> FileCOGValueReader and HadoopCOGValueReader Will Now Throw a ValueNotFoundError

- docs/CHANGELOG.rst
- raster/src/main/scala/geotrellis/raster/io/geotiff/compression/DeflateCompression.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/compression/CompressionSpec.scala
We had concerns about Deflate compression speed. The truth is that it's at least 2 times slower than lzw (gdal numbers). This PR exposes levels of compression into user API
Both things would work:
```scala
COGLayer.fromLayerRDD(
reprojected,
zoom,
compression = DeflateCompression,
maxTileSize = 4096
)
COGLayer.fromLayerRDD(
reprojected,
zoom,
compression = new DeflateCompression(1),
maxTileSize = 4096
)
```
> Expose Deflate compression level into user API

- docs/CHANGELOG.rst
- raster/src/main/scala/geotrellis/raster/mapalgebra/focal/hillshade/SurfacePointCalculation.scala
- raster/src/test/scala/geotrellis/raster/mapalgebra/focal/SlopeSpec.scala
This PR fixes a bug in the `Tile.slope(cellSize, target = TargetCell.Data)` method call where if the first value of a column was `NoData` then all of the values in that row would be set to `NoData`.
Closes #2563
> Tile.slope(cellSize, target = TargetCell.Data) Fix

- docs/CHANGELOG.rst
- spark/src/main/scala/geotrellis/spark/pyramid/Pyramid.scala
In #2505, the attempt was made to reduce shuffle volume by resampling tiles on the map side.  The code introduced was a no-op on the map side, and caused a regression in functionality by hard-coding the resampling method to nearest neighbor.  It was necessary to assume that all pyramiding operations induce a 2-to-1 reduction in tile size.
Closes #2600 
> Fix reprojection bug in Pyramid

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloLayerProvider.scala
- accumulo/src/test/scala/geotrellis/spark/io/accumulo/AccumuloLayerProviderSpec.scala
- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraLayerProvider.scala
- cassandra/src/test/scala/geotrellis/spark/io/cassandra/CassandraLayerProviderSpec.scala
- hbase/src/main/scala/geotrellis/spark/io/hbase/HBaseLayerProvider.scala
- hbase/src/test/scala/geotrellis/spark/io/hbase/HBaseLayerProviderSpec.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3LayerProvider.scala
- s3/src/main/scala/geotrellis/spark/io/s3/cog/S3COGLayerProvider.scala
- s3/src/test/scala/geotrellis/spark/io/s3/S3LayerProviderSpec.scala
- s3/src/test/scala/geotrellis/spark/io/s3/cog/COGS3LayerProviderSpec.scala
- spark/src/main/scala/geotrellis/spark/io/file/FileLayerProvider.scala
- spark/src/main/scala/geotrellis/spark/io/file/cog/FileCOGLayerProvider.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopLayerProvider.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/cog/HadoopCOGLayerProvider.scala
- spark/src/test/scala/geotrellis/spark/io/file/FileLayerProviderSpec.scala
- spark/src/test/scala/geotrellis/spark/io/file/cog/COGFileLayerProviderSpec.scala
- spark/src/test/scala/geotrellis/spark/io/hadoop/HadoopLayerProviderSpec.scala
- spark/src/test/scala/geotrellis/spark/io/hadoop/cog/COGHadoopLayerProviderSpec.scala
This PR makes it so that a `RuntimeException` will be thrown when a user tries to pass in a `URI` to a `LayerProvider` instead of a `NullPointerException`.
Closes #2551
> LayerProviders Can Now Handle a URI That is Missing a Scheme

- docs/CHANGELOG.rst
- spark-testkit/src/main/scala/geotrellis/spark/testkit/io/cog/COGPersistenceSpec.scala
- spark/src/main/scala/geotrellis/spark/io/cog/COGLayer.scala
- spark/src/main/scala/geotrellis/spark/io/cog/COGLayerWriter.scala
This PR adds the `resampleMethod`, `maxTileSize` and moves `compression` parameter to `COGLayerWriter.Options`.
```scala
COGLayer.fromLayerRDD(layerRDD, zoom, options = Bilinear)
```
```scala
val options = COGLayerWriter.Options(1024)
writer.write[K, V](layerId.name, tiles, layerId.zoom, keyIndexMethod, options)
```
This PR is based on another, open PR #2628 which should be merged before this one.
Closes #2605 and #2606
> Specify a resampleMethod and maxTileSize when writing a COGLayer

- docs/CHANGELOG.rst
- geomesa/src/main/scala/geotrellis/geomesa/geotools/GeometryToGeoMesaSimpleFeature.scala
- geotools/src/main/scala/geotrellis/geotools/FeatureToSimpleFeatureMethods.scala
- geotools/src/main/scala/geotrellis/geotools/GeometryToSimpleFeature.scala
- geotools/src/main/scala/geotrellis/geotools/GeometryToSimpleFeatureMethods.scala
- geotools/src/test/scala/geotrellis/geotools/FeatureToSimpleFeatureMethodsSpec.scala
- geotools/src/test/scala/geotrellis/geotools/GeometryToSimpleFeatureMethodsSpec.scala
Simple features were being built with a constant ID field.  This PR allows the user to specify that ID or to accept a randomly generated ID.  We were also storing geometry into the nonstandard field "geometry".  This has been updated to store geometry in the standard "the_geom" field.
Closes #2575
> Fix issues with simple feature building

- docs/CHANGELOG.rst
- slick/src/main/scala/geotrellis/slick/PostGisProjectionSupport.scala
- slick/src/main/scala/geotrellis/slick/PostGisSupport.scala
- slick/src/main/scala/geotrellis/slick/Projected.scala
- slick/src/main/scala/geotrellis/slick/package.scala
- vector/src/main/scala/geotrellis/vector/package.scala
Reverts locationtech/geotrellis#2639
I think it can cause problems in the future merges into 2.0 branch. Reverting to merge this PR into master.
> Revert "Deprecate Slick and move Projected"

- raster/build.sbt
- raster/src/main/scala/geotrellis/raster/TileFeature.scala
- raster/src/main/scala/geotrellis/raster/crop/Implicits.scala
- raster/src/main/scala/geotrellis/raster/crop/TileFeatureCropMethods.scala
- raster/src/main/scala/geotrellis/raster/mask/Implicits.scala
- raster/src/main/scala/geotrellis/raster/mask/TileFeatureMaskMethods.scala
- raster/src/main/scala/geotrellis/raster/merge/Implicits.scala
- raster/src/main/scala/geotrellis/raster/merge/TileFeatureMergeMethods.scala
- raster/src/main/scala/geotrellis/raster/package.scala
- raster/src/main/scala/geotrellis/raster/prototype/Implicits.scala
- raster/src/main/scala/geotrellis/raster/prototype/TileFeaturePrototypeMethods.scala
- raster/src/main/scala/geotrellis/raster/reproject/Implicits.scala
- raster/src/main/scala/geotrellis/raster/reproject/TileFeatureReprojectMethods.scala
- raster/src/main/scala/geotrellis/raster/split/Implicits.scala
- raster/src/main/scala/geotrellis/raster/split/TileFeatureSplitMethods.scala
- raster/src/main/scala/geotrellis/raster/stitch/Stitcher.scala
`TileFeature[T <: CellGrid, D]` instances are essentially Tiles enriched with metadata.  They should be treated as Tiles in most respects, yet no method extensions were provided to allow these features to be manipulated with the same facility as Tiles.  This PR proposes method extensions over TileFeatures so that this first-class status is conferred onto this structure.
I have employed the Cats library here, as it provides all the required features for this proof-of-concept.  To make use of all the features in these method extensions, please
```scala
import cats.{Monoid, Semigroup}
import cats.implicits._
```
prior to using these methods.
This PR fixes #2138 
> TileFeature method extensions

- util/src/main/scala/geotrellis/util/StreamingByteReader.scala
This results in overflow in Integer math for files larger than 2G
Resulting offsets would attempt to read at negative buffer position producing traces like: 
```scala
[info]   java.nio.BufferUnderflowException:
[info]   at java.nio.Buffer.nextGetIndex(Buffer.java:500)
[info]   at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:135)
[info]   at geotrellis.util.StreamingByteReader.get(StreamingByteReader.scala:130)
[info]   at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readGeoTiffInfo(GeoTiffReader.scala:343)
[info]   at geotrellis.spark.io.file.cog.COGSpec$$anonfun$1.apply(COGSpec.scala:39)
[info]   at geotrellis.spark.io.file.cog.COGSpec$$anonfun$1.apply(COGSpec.scala:35)
```
> Avoid casting file position offsets to Int when reading byte ranges

- geomesa/src/main/scala/geotrellis/geomesa/geotools/GeometryToGeoMesaSimpleFeature.scala
- geomesa/src/main/scala/geotrellis/spark/io/geomesa/conf/GeoMesaConfig.scala
- geomesa/src/test/scala/geotrellis/geomesa/geotools/GeoMesaSimpleFeatureType.scala
We depend on `pureconfig`, so we can standardize over the method to access params.
Update for the vector package is in #2619.
> Move GeoTrellis GeoMesa to use pureconfig

- vector/src/main/scala/geotrellis/vector/GeomFactory.scala
- vector/src/main/scala/geotrellis/vector/conf/JtsConfig.scala
When working with JTS geometries directly in client code, it's useful to have access to the same `Geometry` and `CoordinateSequence` factories that GT is using (vs. creating local instances w/ potentially differing settings). All other members remain private to the `geotrellis.vector` package.
More controversially, this switches GT's default `CoordinateSequenceFactory` to `PackedCoordinateSequenceFactory` in order to reduce the number of objects allocated (`double[]` is used rather than `Coordinate[]`) and reduce pressure on the GC.
This shouldn't affect client implementations unless `CoordinateSequence`s are explicitly cast; this shouldn't occur and isn't necessary when the `CoordinateSequences` helper class is used.
> Expose GeomFactory into the user API and move vector project to use pureconfig

- docs/CHANGELOG.rst
- raster/src/main/scala/geotrellis/raster/crop/RasterCropMethods.scala
- spark/src/main/scala/geotrellis/spark/crop/Crop.scala
- spark/src/test/scala/geotrellis/spark/crop/TileLayerRDDCropMethodsSpec.scala
Cropping of RDD tile layers with `clamp=false` caused problems because the cropping region wasn't restricted to the current spatial key, resulting in tiles that have a partial intersection with the crop region producing tiles that span the entire crop region.
Note: This PR is based on #2662 and also resolves part of the problem from issue #2549
> Fix problems with tile layer cropping when `clamp=false`

- s3/src/main/scala/geotrellis/spark/io/s3/S3LayerHeader.scala
This PR fixes a bug that caused some `S3LayerHeader`s to be improperly read.
> S3LayerHeader Reading Fix

- spark-etl/build.sbt
- spark-pipeline/build.sbt
We depend on shapeless at the moment (dep brought by `circe` and `pureconfig`)
This PR shows how to shade shapeless. Shading is necessary as `Spark` itself depends on some old shapeless version.
> Add shapeless shading into GeoTrellis assembly

- docs/CHANGELOG.rst
- spark/src/main/scala/geotrellis/spark/io/LayerReader.scala
- spark/src/main/scala/geotrellis/spark/pyramid/Pyramid.scala
- spark/src/test/scala/geotrellis/spark/pyramid/PyramidSpec.scala
GeoTrellis creates, as one of its core functions, multi-resolution, hierarchical level-of-detail structures that we commonly call pyramids.  Despite their frequent appearance in our workflows, we have been representing them as `List[(Int, RDD[(K, V)] with Metadata[M])]`.  This PR aims to grant pyramids first-class citizenship by creating a wrapper class that streamlines common operations on those structures.
Closes #2654 
> Introduce Pyramid class

- .travis.yml
Right now travis doesn't publish scaladocs and snapshots because of a typo in a `.travis.yml`.
> Fix deployment script launch

- docs/CHANGELOG.rst
- s3/src/main/scala/geotrellis/spark/io/s3/S3RDDReader.scala
- spark/src/main/scala/geotrellis/spark/io/LayerReader.scala
Sometimes `S3` throws exceptions during reads. We already created a workaround for `S3` writes. This PR adds exponential backoffs for reads.
Closes #2574
> Use exponential backoff function in S3LayerReader

- docs/CHANGELOG.rst
- spark-etl/src/main/resources/input-schema.json
- spark-etl/src/main/resources/output-schema.json
- spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/config/Input.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/config/Output.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/config/json/ConfigFormats.scala
This PR adds a couple of `spark-etl` parameters, as we are still in process of moving to our `spark-pipeline` package.
Docs would be done in a separate PR.
Related to #2681
> Introduce unspecified options into Spark ETL package

- project/Environment.scala
Upgrades the spark dependency to 2.3.0.
Driving reason aside from keeping current is to use improved ORC file support from Spark 2.3.0 in https://github.com/geotrellis/vectorpipe/pull/54
> Spark Version 2.3.0

- docs/CHANGELOG.rst
- raster/data/data/aspect.json
- raster/src/main/scala/geotrellis/raster/mapalgebra/focal/Aspect.scala
- raster/src/main/scala/geotrellis/raster/mapalgebra/focal/hillshade/Hillshade.scala
- raster/src/main/scala/geotrellis/raster/mapalgebra/focal/hillshade/SurfacePointCalculation.scala
- raster/src/test/scala/geotrellis/raster/mapalgebra/focal/AspectSpec.scala
Change aspect result to azimuth, i.e. start from due north and be clockwise. So that it will match the API description in `raster.mapalgebra.focal.Aspect`.
Closes #2580
> Change aspect result to azimuth

- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraValueReader.scala
Signed-off-by: Andrew Polack <polack.andy@gmail.com> // <andrew.polack@navy.mil>
Fixes issue #2695 
In short, prevents the re-preparing of an already prepared statement which is a Cassandra anti-pattern. 
- [N/A] `docs/CHANGELOG.rst` updated, if necessary
- [N/A] `docs` guides update, if necessary
- [N/A] New user API has useful Scaladoc strings
- [?] Unit tests added for bug-fix or new feature
I could use some help figuring out how to test this... generally the symptom is a warning that appears in the log emitted from the Cassandra Datastax Java Driver if a query is re-prepared. 
I ran the `cassandra` SBT project test suite and all tests passed so... ¯\_(ツ)_/¯
If the Session object is somehow pooled and a different Session is provided than the one originally used to prepare the statement …
> Prevent re-preparing already prepared statement in CassandraLayerReader

- doc-examples/src/main/scala/geotrellis/doc/examples/raster/RasterExamples.scala
Edited a single line to fix the index calculation in doc-examples/src/main/scala/geotrellis/doc/examples/raster/RasterExamples.scala/RasterExample.scala
- [ x] `docs/CHANGELOG.rst` updated, if necessary
- [ x] `docs` guides update, if necessary
- [ x] New user API has useful Scaladoc strings
- [ x] Unit tests added for bug-fix or new feature
Closes #XXX
> Fix index calculation in RasterExample

- doc-examples/src/main/scala/geotrellis/doc/examples/raster/RasterExamples.scala
This adds an example of rasterizing a set of polygon features, where the feature data represents a set of class IDs from 0 - 4. The resulting multiband raster  has 5 bands, each for class 0 - 4, and contains counts of how many polygons of that class overlapped that cell.
> Added example of rasterizing polygons with count

- raster/src/main/scala/geotrellis/raster/io/geotiff/BandTypes.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/SegmentBytes.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/compression/Predictor.scala
- spark/src/main/scala/geotrellis/spark/costdistance/IterativeCostDistance.scala
- spark/src/main/scala/geotrellis/spark/io/RasterReader.scala
- spark/src/test/scala/geotrellis/spark/io/slippy/HadoopSlippyTileWriterSpec.scala
- spark/src/test/scala/geotrellis/spark/render/SpatialTileLayerRDDRenderMethodsSpec.scala
- spark/src/test/scala/geotrellis/spark/reproject/TileRDDReprojectSpec.scala
- vector/src/main/scala/geotrellis/vector/mesh/IndexedPointSet.scala
The following tests were not passing with kryo serialization disabled. Only a part of them were related to a default tiff readers behavior change. 
Closes #2721
> Make all tests Java Serialization compatible

- proj4/src/main/scala/geotrellis/proj4/mgrs/MGRS.scala
- proj4/src/test/scala/geotrellis/proj4/mgrs/MGRSSpec.scala
The initial implementation of MGRS failed to zero-pad UTM northing and easting values in the event of small values.  This caused too few digits to be returned in some cases.  (This may also have been the source of the intermittent CI errors generated by `MGRSSpec`.)  This PR fixes this error.
Closes #2725
> Repair errors in MGRS conversion

- docs/CHANGELOG.rst
- spark/src/main/scala/geotrellis/spark/io/cog/COGLayer.scala
This PR fixes a bug where the `ResampleMethod` passed into `COGLayer.fromLayerRDD` would be ignored when creating the COG overviews. Now, the COG overview creation will use the passed in `ResampleMethod`.
Closes #2718
> ResampleMethod for COGLayer.fromLayerRDD

- docs/CHANGELOG.rst
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeoWaveAttributeStore.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeoWaveLayerReader.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeoWaveLayerWriter.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeoWaveUtil.scala
- geowave/src/main/scala/geotrellis/spark/io/kryo/GeoWaveKryoRegistrator.scala
- geowave/src/test/scala/geotrellis/spark/GeoWaveTestEnvironment.scala
- geowave/src/test/scala/geotrellis/spark/io/geowave/GeoWaveAttributeStoreSpec.scala
- geowave/src/test/scala/geotrellis/spark/io/geowave/GeoWaveFeatureRDDReaderSpec.scala
- geowave/src/test/scala/geotrellis/spark/io/geowave/GeoWaveSpatialSpec.scala
This PR standardizes the spelling of `GeoWave` in the `geowave` package. Before, classes and objects in the project used either the `Geowave` or the `GeoWave` spelling in their names. Now will they all have the same spelling of: `GeoWave`.
> Standardized the Spelling of GeoWave

- docs/CHANGELOG.rst
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReader.scala
This PR fixes a bug where reading large GeoTiffs (>= 25 GB) with `streaming` would fail. The cause of this bug was because we were using a `FileInputStream` when streaming in GeoTiffs which has a max size of `Int.MAX_VALUE`. This was resolved by using a `StreamingByteReader` instead.
Closes #2711
> Reading Big GeoTiffs With streaming Fix

- spark/src/main/scala/geotrellis/spark/io/cog/COGLayerMetadata.scala
- spark/src/test/scala/geotrellis/spark/io/cog/COGLayerMetadataSpec.scala
This PR changes COGLayerMetadata construction to include fitting min zoom level partial pyramid, even if it's not its low zoom level.
Closes #2707
> Change COGLayerMetadata creation behavior

- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/codes/InterleaveType
Currently, the `InterleaveType` file in GeoTrellis isn't a `.scala`, and thus, is not used at all. Because it's not being used, it'd be best to remove it from the library.
> Removed InterleaveType

- .travis.yml
- .travis/build-and-test-set-1.sh
- .travis/build-and-test-set-2.sh
- .travis/build-and-test-set-3.sh
- .travis/build-and-test.sh
- .travis/unzip-rasters.sh
This PR splits GeoTrellis tests into three parts and launches everything on both oracle and open jdk.
> Split TravisCI tests and make them more consistent

- spark/src/main/scala/geotrellis/spark/io/cog/COGLayerReader.scala
When `gdal_translate` is applied to a COGs written by GeoTrellis it will apparently encode tags with HTML special characters. 
This will change `GT_KEY` from `{ "col": 162, "row": 230 }`  to `{ &quot;col&quot;: 161, &quot;row&quot;: 229 }`. `gdalinfo`  will in turn decode the HTML special chars and the tag will display normally.
However when parsing these COGs with GeoTrellis `COGLayerReader` the following exception will be thrown
```scala
Caused by: spray.json.JsonParser$ParsingException: Unexpected character '&' at input index 2 (line 1, position 3), expected '"':
{ &quot;col&quot;: 161, &quot;row&quot;: 229 }
^
at spray.json.JsonParser.fail(JsonParser.scala:213)
at spray.json.JsonParser.string(JsonParser.scala:141)
at spray.json.JsonParser.members$1(JsonParser.scala:77)
at …
```
> Remove possible HTML special chars from GeoTiff tags

- docs/CHANGELOG.rst
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffBuilder.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffSegmentLayout.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/writer/TiffTagFieldValue.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/GeoTiffBuilerSpec.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTileSpec.scala
Enables building multiband GeoTiffs with band interleave storage method.
- [-] `docs` guides update, if necessary
- [-] New user API has useful Scaladoc strings
> GeoTiff Band Interleave Construction

- docs/CHANGELOG.rst
- raster/src/main/scala/geotrellis/raster/crop/MultibandTileCropMethods.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTile.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTileSpec.scala
- spark/src/main/scala/geotrellis/spark/io/cog/COGValueReader.scala
This PR improves the performance of the `readSubsetBands` method by changing how cropping operation is performed. Before, the input GeoTiff was converted to a `GeoTiffMultibandTile` and then cropped, but now it will be pattern matched instead and crop instead. This removes unneeded memory allocation which improves performance with certain backends, mainly S3.
Closes #2761
> readSubsetBands Performance Improvement

- .travis/hbase-install.sh
This PR bumps up `HBase` version used for tests, as `HBase` team again removed the previous database version from their repositories.
> Bump travis HBase version

- docs/CHANGELOG.rst
- raster/src/main/scala/geotrellis/raster/crop/MultibandTileCropMethods.scala
- s3/src/main/scala/geotrellis/spark/io/s3/cog/S3COGLayerReader.scala
- spark-testkit/src/main/scala/geotrellis/spark/testkit/io/cog/COGPersistenceSpec.scala
- spark/src/main/scala/geotrellis/spark/KeyBounds.scala
- spark/src/main/scala/geotrellis/spark/io/cog/COGLayerReader.scala
- spark/src/main/scala/geotrellis/spark/io/file/cog/FileCOGLayerReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/cog/HadoopCOGLayerReader.scala
- spark/src/test/scala/geotrellis/spark/io/file/cog/COGFileSpatialSpec.scala
This PR adds two new methods to `COGLayerReader`: `readSubsetBands` and `querySubsetBands`. These two methods allow the user to specify which bands from the layer should be read in and in what order. This should allow for more performant reads when only some bands are desired. In addition to these new methods, two additional `cropBands` overloads were added to `MultibandTileCropMethods`. 
```scala
val reader: COGLayerReader = ???
val layerId: Layerid = ???
// reads bands 2, 1, and 3 and returns them in that order
reader.readSubsetBands(layerId, Seq(2, 1, 3)
```
The `reader` method in `COGLayerReader` still returns a `Reader` instead of a `COGReader`. I wasn't sure if that change was really needed for this PR, so I left it as a `TODO` for the time being.
> COGLayerReader readSubsetBands and querySubsetBands

- docs/CHANGELOG.rst
- docs/guide/examples.rst
- s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffInfoReader.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffRDD.scala
- spark/src/main/scala/geotrellis/spark/Implicits.scala
- spark/src/main/scala/geotrellis/spark/KeyBounds.scala
- spark/src/main/scala/geotrellis/spark/TileLayerMetadata.scala
- spark/src/main/scala/geotrellis/spark/io/GeoTiffInfoReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffInfoReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffRDD.scala
- spark/src/main/scala/geotrellis/spark/pyramid/Pyramid.scala
- spark/src/test/scala/geotrellis/spark/pyramid/PyramidSpec.scala
This PR changes handful of methods that were suffixed with `Rdd` to end with `RDD` to become consistent with the rest of the library and Spark Scala API.
> Consistently use RDD suffix in API

- .travis.yml
- .travis/build-and-test-set-1.sh
- .travis/build-and-test-set-2.sh
- .travis/build-and-test-set-3.sh
- .travis/build-and-test.sh
- .travis/unzip-rasters.sh
- docs/guide/core-concepts.rst
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiff.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/SinglebandGeoTiff.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/SinglebandGeoTiffSpec.scala
Add a short description of COGs and their support in GeoTrellis as well as a helper method to combine overviews with their origin Tiffs (useful for sidecar-based COGs)
We probably can't merge this in without some more work being done to make the GT COG API consistent. We also can't support sidecar metadata, which seems to be necessary
> Document cogs + add `withOverviews` overload

- vector/src/main/scala/geotrellis/vector/package.scala
This PR allows code to compile against Scala 2.12
Back port of code changes from this PR: https://github.com/locationtech/geotrellis/pull/2727
A part of https://github.com/locationtech/geotrellis/issues/1751
> Add covariance into type aliases to support Scala 2.12

- raster/src/main/scala/geotrellis/raster/ArrayTile.scala
- raster/src/main/scala/geotrellis/raster/DelegatingTile.scala
- raster/src/test/scala/geotrellis/raster/ArrayTileSpec.scala
- raster/src/test/scala/geotrellis/raster/CellTypeSpec.scala
Also:
Adds new utility `DelegatingTile`.
Fixes compiler warning in CellTypeSpec.
Signed-off-by: Simeon H.K. Fitch <fitch@astraea.io>
Closes #2792.
> Fixes #2792.

- proj4/src/test/scala/geotrellis/proj4/io/wkt/WKTParserTest.scala
This PR adds an extra test, as @wsf1990 experienced some issues with parsing an ordinary WKT string. The [original code that didn't work was](https://gitter.im/geotrellis/geotrellis?at=5b7d07d24be56c59187b7645):
```scala
WKTParser(
"""GEOGCS["GCS_WGS_1984",
|  DATUM["D_WGS_1984", SPHEROID["WGS_1984", 6378137.0, 298.257223563]],
|  PRIMEM["Greenwich", 0.0],
|  UNIT["degree", 0.017453292519943295],
|  AXIS["Longitude", "EAST"],
|  AXIS["Latitude", "NORTH"]]""".stripMargin)
```
> Add an extra WKT parser test

- spark-etl/src/main/scala/geotrellis/spark/etl/TemporalIngest.scala
Allows Temporal Ingests from spark-etl to S3
> Allows Temporal Ingests from spark-etl to S3

- docs/CHANGELOG.rst
- raster/src/main/scala/geotrellis/raster/Tile.scala
- raster/src/main/scala/geotrellis/raster/reproject/RasterRegionReproject.scala
- raster/src/main/scala/geotrellis/raster/stitch/Stitcher.scala
- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
- spark/src/test/scala/geotrellis/spark/reproject/TileRDDReprojectSpec.scala
Closes https://github.com/locationtech/geotrellis/issues/2799
Mostly this PR reworks the `RasterRegionReproject` to allow composition of instances such that reprojection of `TileFeature` RDD could be supported. Adding a unit test for this revealed another missing implicit which is added here.
The mutability remains an important optimization specifically in the RDD case where it allows using a tile as an accumulator when multiple source tiles contribute pixels during the reproject operation without allocating memory for each intermediate result. Hopefully expanded documentation is enough to steer users in the right direction and use this feature responsibly.
- Changes `RasterRegionReproject` to allow creating an instance for `TileFeature[T, D]`
- Uses optimized reproject logic in …
> RDD Reproject for TileFeatures, RasterRegionReproject

- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/TiffTags.scala
This PR allows to handle properly such kinds of Extents:
```
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,13545.0)
Upper Right (21995.0,    0.0)
Lower Right (21995.0,13545.0)
Center      (10997.5, 6772.5)
```
Closes https://github.com/locationtech/geotrellis/issues/2805
> Fix Inverted Extent

- accumulo/build.sbt
- cassandra/build.sbt
- geomesa/build.sbt
- geowave/build.sbt
- hbase/build.sbt
- project/Dependencies.scala
- s3/build.sbt
- spark-etl/build.sbt
- spark-pipeline/build.sbt
- spark-testkit/build.sbt
- spark-testkit/src/main/scala/geotrellis/spark/testkit/TestEnvironment.scala
- spark/build.sbt
This PR adds spark-sql dependency into `spark-testkit` project and modifies `TestEnvironment` trait to contain `SparkSession`
A new dependency doesn't really hurt as, as it is a dependency into a test sub project.
Closes https://github.com/locationtech/geotrellis/issues/2498
> Add SparkSession into TestEnvironment

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloCollectionReader.scala
- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloWriteStrategy.scala
- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraRDDWriter.scala
- project/Dependencies.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3RDDWriter.scala
- s3/src/main/scala/geotrellis/spark/io/s3/SaveToS3.scala
- spark/src/main/scala/geotrellis/spark/io/AsyncWriter.scala
- spark/src/main/scala/geotrellis/spark/io/LayerReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/geotiff/GeoTiffLayerReader.scala
This brings cats-effect to 1.0, which should be faster and have a more stable API going forward.
> Use Timer as necessary for IO

- spark/src/main/scala/geotrellis/spark/util/TaskUtils.scala
This change makes `IOBackoff` agnostic about the underlying effect engine used by clients at the cost of a slightly more cumbersome `cats-effect` API.
I'm curious - @echeipesh @pomadchin - do you guys think this is even worth it?
> Make IO code agnostic about effects

- .travis/build-set-1.sh
- .travis/build-set-2.sh
- .travis/build-set-3.sh
- build.sbt
- project/Environment.scala
This PR updates Apache Spark dependency.
The following projects are excluded from the 2.12 builds: 
* Slick (as it's deprecated, and requires some code changes to make it work)
* GeoMesa (as it doesn't support Scala 2.12)
* GeoWave (as it doesn't support Scala 2.12)
Closes #1751
> Bump Spark version up to 2.4

- .locationtech/deploy-211.sh
- .locationtech/deploy-212.sh
- .locationtech/deploy.sh
- raster/src/main/scala/geotrellis/raster/reproject/ReprojectRasterExtent.scala
- raster/src/test/scala/geotrellis/raster/reproject/ReprojectRasterExtentSpec.scala
- raster/src/test/scala/geotrellis/raster/reproject/ReprojectSpec.scala
- vector/src/main/scala/geotrellis/vector/Extent.scala
- vector/src/main/scala/geotrellis/vector/reproject/Implicits.scala
- vector/src/main/scala/geotrellis/vector/reproject/Reproject.scala
While investigating a reprojection issue in geotrellis-contrib, it came to my attention that the raster extents produced by `ReprojectRasterExtent` are off.  Consider the following: using https://github.com/geotrellis/geotrellis-contrib/blob/master/vlm/src/test/resources/img/aspect-tiled.tif as the base of this example, the following definitions apply:
```scala
val tiff = GeoTiffReader.readMultiband(getByteReader("aspect-tiled.tif"), streaming = true)
val targetRE = ReprojectRasterExtent(tiff.rasterExtent, tiff.crs, WebMercator)
val region = tiff.projectedExtent.reprojectAsPolygon(WebMercator, 0.001)
```
We then note that `targetRE.extent` and `region.envelope` diverge:
```scala
targetRE.extent: geotrellis.vector.Extent = Extent(-8769150.640916323, 4257706.9716441, -8750638.524926396, …
```
> Fix error in `ReprojectRasterExtent`

- proj4/src/main/java/org/osgeo/proj4j/datum/AxisOrder.java
This PR fixes a scaladoc 2.12 bug: https://github.com/scala/bug/issues/10509
> Fix proj4j publish

- project/Dependencies.scala
- project/Settings.scala
This PR downgrades Avro version down to 1.7.7 to correspond Hadoop version.
> Downgrade Avro version

- raster/src/main/scala/geotrellis/raster/ProjectedRaster.scala
Signed-off-by: Simeon H.K. Fitch <fitch@astraea.io>
Want to say no more to this:
```scala
val pr = someGeotiff.projectedRaster
val tile = pr.tile.interpretAs(UShortConstantNoDataCellType)
val fixedpr = ProjectedRaster(tile, pr.extent, pr.crs)
```
and instead
```scala
val pr = someGeotiff.projectedRaster
val fixedpr = pr.mapTile(_.interpretAs(UShortConstantNoDataCellType))
```
- [NO] `docs/CHANGELOG.rst` updated, if necessary
- [NO] `docs` guides update, if necessary
- [NO] New user API has useful Scaladoc strings
- [NO] Unit tests added for bug-fix or new feature
> Added `mapTile` to `ProjectedRaster`.

- doc-examples/src/main/scala/geotrellis/doc/examples/raster/MatchingRasters.scala
- raster/src/main/scala/geotrellis/raster/ProjectedRaster.scala
- raster/src/main/scala/geotrellis/raster/Raster.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/MultibandTilePolygonalSummaryHandler.scala
- raster/src/main/scala/geotrellis/raster/summary/polygonal/TilePolygonalSummaryHandler.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala
- raster/src/test/scala/geotrellis/raster/reproject/RasterizeReprojectSpec.scala
- raster/src/test/scala/geotrellis/raster/reproject/ReprojectSpec.scala
- spark/src/test/scala/geotrellis/spark/reproject/TileRDDReprojectSpec.scala
- spark/src/test/scala/geotrellis/spark/stitch/RDDStitchMethodsSpec.scala
> Made implicit conversions to/from Raster and ProjectedRaster deprecated.

- raster/src/main/scala/geotrellis/raster/interpolation/InverseDistanceWeighted.scala
- raster/src/test/scala/geotrellis/raster/interpolation/InverseDistanceWieghtedSpec.scala
> Fixed elliptical radius check in IDW algorithm.

- proj4/src/main/scala/geotrellis/proj4/Transform.scala
- spark/src/main/scala/geotrellis/spark/tiling/package.scala
MapTransform can be not that accurate in case `srcCRS == destCRS`. Partially addresses https://github.com/locationtech/geotrellis/issues/2826
> Catch a possible precision loss on reprojection to the same projection

- spark/src/main/scala/geotrellis/spark/ingest/Ingest.scala
- spark/src/main/scala/geotrellis/spark/ingest/MultibandIngest.scala
Without this fix in some cases we can be get into the situation where this cache level (IN_MEMORY) would be assigned for the RDD, making impossible to set the desired cache level from the parameters, causing the following exception:
```
[info]   java.lang.UnsupportedOperationException: Cannot change storage level of an RDD after it was already assigned a level
[info]   at org.apache.spark.rdd.RDD.persist(RDD.scala:170)
[info]   at org.apache.spark.rdd.RDD.persist(RDD.scala:195)
[info]   at geotrellis.spark.ingest.Ingest$.apply(Ingest.scala:96)
```
> Fixe cache level in Ingest objects

- docs/CHANGELOG.rst
Backports https://github.com/locationtech/geotrellis/pull/2866
> Add v2.2.0 changelog [skip ci]

- raster/src/main/scala/geotrellis/raster/mapalgebra/focal/hillshade/SurfacePointCalculation.scala
- raster/src/test/scala/geotrellis/raster/mapalgebra/focal/AspectSpec.scala
Fix a bug about cellType-double-DEM's flat area's aspect  are not '-1'.
Because when the DEM' value are double type, the `dz/dx` and `dz/dy` are very close to '0' but not equal to '0'.So when compare with '0',I set a tolerance which is 1E-10.
And aspect==360 has the same problem.
> fix bug about cellType-double-DEM's flat area's aspect are not '-1'

- raster/src/main/scala/geotrellis/raster/GridExtent.scala
The sad state of affairs before this PR:
```scala
scala> GridExtent(Extent(0,0,3.5,3.5), 1.0, 1.0)
res12: geotrellis.raster.GridExtent = GridExtent(Extent(0.0, 0.0, 3.5, 3.5),1.0,1.0)
scala> res12.createAlignedRasterExtent(res12.extent)
res13: geotrellis.raster.RasterExtent = GridExtent(Extent(0.0, 0.0, 3.5, 3.5),1.0,1.0)
scala> res12.createAlignedRasterExtent(Extent(0,0,3.8,3.8))
res14: geotrellis.raster.RasterExtent = GridExtent(Extent(0.0, 0.0, 4.5, 4.5),1.0,1.0)
```
I fixed it and introduced the possibility that the alignment point (a point at the intersection of the target cell grid) might be specified by the user (in case one wanted the grid to align to a point other than the upper left of the GridExtent's extent):
```scala
scala> GridExtent(Extent(0,0,3.5,3.5), 1.0, 1.0)
res0: …
```
> Make createAlignedGridExtent actually align to GridExtents

- raster/src/main/scala/geotrellis/raster/reproject/RasterRegionReproject.scala
RasterRegionReproject is a touchy algorithm.  Specifically, there is a mock scanline generation algorithm that takes place using a pretty weird geometric intersection algorithm.  It is unfortunately useful for speeding up the computation of sampling points, so we're stuck with it.  The problem is that the determination of bounds for converting these geometric line segments into a pixel range appears to be numerically touchy.  I'm proposing a slight change to the numerical fudge factors that make the process work, but I understand that this is suspicious, and will possibly cause problems depending on the projection of the input points.
We can try to finesse this PR to do something more elegant and more correct through the review process.
> Fixes to RasterRegionReproject

- raster/src/test/scala/geotrellis/raster/interpolation/InverseDistanceWieghtedSpec.scala
- raster/src/test/scala/geotrellis/raster/interpolation/KrigingSpec.scala
- slick/src/main/scala/geotrellis/slick/PostGisProjectionSupport.scala
- slick/src/main/scala/geotrellis/slick/PostGisSupport.scala
- spark/src/test/scala/geotrellis/spark/io/LayerQuerySpec.scala
- spark/src/test/scala/geotrellis/spark/rasterize/RasterizeRDDSpec.scala
- vector/src/main/scala/geotrellis/vector/io/json/FeatureFormats.scala
- vector/src/main/scala/geotrellis/vector/io/json/JsonFeatureCollection.scala
- vector/src/main/scala/geotrellis/vector/io/json/JsonFeatureCollectionMap.scala
- vector/src/main/scala/geotrellis/vector/io/package.scala
- vector/src/main/scala/geotrellis/vector/package.scala
- vector/src/test/scala/spec/geotrellis/vector/dissolve/DissoveMethodsSpec.scala
- vector/src/test/scala/spec/geotrellis/vector/interpolation/KrigingVectorSpec.scala
- vector/src/test/scala/spec/geotrellis/vector/io/json/FeatureFormatsSpec.scala
- vector/src/test/scala/spec/geotrellis/vector/io/json/GeoJsonSpec.scala
- vector/src/test/scala/spec/geotrellis/vector/io/json/StyleSpec.scala
This PR simplifies the imports needed to use certain functionality in the `geotrellis.vector` package. Mainly, `vector.io.wkb.Implicits`, `vector.io.wkt.implicits`, and `vector.io.json.Implicits` are now all imported with `import geotrellis.vector._`.
Before:
```scala
import geotrellis.vector._
import geotrellis.vector.io._
import geotrellis.vector.io.json.JsonFeatureCollection
val path: String = ???
val f = scala.io.Source.fromFile(path)
val collection = f.mkString.parseGeoJson[JsonFeatureCollection]
```
After:
```scala
import geotrellis.vector._
import geotrellis.vector.io.json.JsonFeatureCollection
val path: String = ???
val f = scala.io.Source.fromFile(path)
val collection = f.mkString.parseGeoJson[JsonFeatureCollection]
```
> Easy Importing for the Vector Package

- doc-examples/src/main/scala/geotrellis/doc/examples/spark/ClipToGridExamples.scala
- project/Settings.scala
- raster/src/main/scala/geotrellis/raster/GridExtent.scala
- raster/src/main/scala/geotrellis/raster/package.scala
- raster/src/test/scala/geotrellis/raster/GridExtentSpec.scala
- spark/src/main/scala/geotrellis/spark/tiling/FloatingLayoutScheme.scala
- spark/src/main/scala/geotrellis/spark/tiling/LayoutDefinition.scala
- spark/src/test/scala/geotrellis/spark/costdistance/IterativeCostDistanceSpec.scala
- spark/src/test/scala/geotrellis/spark/costdistance/RDDCostDistanceMethodsSpec.scala
- spark/src/test/scala/geotrellis/spark/regrid/RegridSpec.scala
- spark/src/test/scala/geotrellis/spark/tiling/LayoutDefinitionSpec.scala
- spark/src/test/scala/geotrellis/spark/timeseries/RDDTimeSeriesMethodsSpec.scala
- spark/src/test/scala/geotrellis/spark/timeseries/TimeSeriesSpec.scala
- spark/src/test/scala/geotrellis/spark/viewshed/IterativeViewshedSpec.scala
- Fix bug in conversion from `GridExtent[Long]` to `GridExtent[Int]`, rely on spire checkin
- Add equality methods and toString methods
- Standardize the overloads for GridExtent
Connects https://github.com/locationtech/geotrellis/pull/2886
> GridExtent regressions

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloAttributeStore.scala
- hbase/src/main/scala/geotrellis/spark/io/hbase/HBaseAttributeStore.scala
Closes https://github.com/locationtech/geotrellis/issues/2897
For Cassandra we probably need to think a little bit about the attributeStore table, since partition key columns are not yet supported by SASI and `layerId` is a `partition key` in our case: https://github.com/apache/cassandra/blob/094689acf10bf133637c53aeebd3e8157832a279/src/java/org/apache/cassandra/index/sasi/SASIIndex.java#L148-L149
Mb @ALPSMAC has his opinion about Cassandra `LIKE` queries.
> Fix Accumulo and HBase attributeStore performance issues

- raster-testkit/src/main/scala/geotrellis/raster/testkit/TileBuilders.scala
- raster/src/main/scala/geotrellis/raster/ArrayTile.scala
- raster/src/test/scala/geotrellis/raster/ArrayTileSpec.scala
> Fix for improper handling of values in `ArrayTile.combine{Double}`'s default case

- docs/CHANGELOG.rst
- raster/src/main/scala/geotrellis/raster/GridExtent.scala
- raster/src/test/scala/geotrellis/raster/RasterExtentSpec.scala
In case of negative `Extent` coordinates and because of a floating point errors, in case where the north and west site of the block is very close to the `Int` we could approximate number of cols / rows incorrectly.
Closes #2918
> Fix map{X|Y}ToGrid function behavior that could give a bit incorrect results

- docs/migrating-to-3.rst
This PR adds a guide that goes over the major changes that occurred in the 3.0 release; and how one can update their code to be compatible with 3.0. It should be noted that this PR does not contain the full document. Rather, it has a section just on the simplified imports. Other topics will be added later.
The guide just contains the simplified imports.
> Migrating to GeoTrellis 3.0 Guide - Simplified Imports

- docs/CHANGELOG.rst
- spark/src/main/scala/geotrellis/spark/io/cog/COGLayerMetadata.scala
- spark/src/test/scala/geotrellis/spark/io/cog/COGLayerMetadataSpec.scala
- spark/src/test/scala/geotrellis/spark/io/cog/COGLayerUpdateSpaceTimeTileSpec.scala
Signed-off-by: Andrey Tararaksin <atararaksin@gmail.com>
Fixes bug with binary search on an unsorted `maxZooms` array in COG layer metadata.
Closes #2921
> Fix COG layer update bug related to COGLayerMetadata zoomRanges ordering

- docs/CHANGELOG.rst
- spark/src/main/scala/geotrellis/spark/io/cog/COGLayer.scala
- spark/src/main/scala/geotrellis/spark/io/cog/COGLayerMetadata.scala
- spark/src/main/scala/geotrellis/spark/io/cog/COGLayerWriter.scala
- spark/src/test/scala/geotrellis/spark/io/cog/COGLayerUpdateSpaceTimeTileSpec.scala
This PR changes COG layers update behavior to use ZoomRanges that were generated at the time of initial ingest. This prevents possible mismatch.
The PR adds an overload to `COGLayer.fromLayerRDD()` which constructs a COGLayer with predefined set of ZoomRanges.
Note that this PR is dependent on #2922, because the test won't succeed unless #2921 is fixed.
Closes #2938
> Use original ZoomRanges on COG layer update

- spark-pipeline/src/main/scala/geotrellis/spark/pipeline/ast/Input.scala
- spark-pipeline/src/main/scala/geotrellis/spark/pipeline/ast/Output.scala
- spark-pipeline/src/main/scala/geotrellis/spark/pipeline/ast/Transform.scala
- spark-pipeline/src/main/scala/geotrellis/spark/pipeline/json/PipelineKeyIndexMethod.scala
This PR updates the imports of the `spark-pipeline` package so that they reflect the new split API.
This PR is based on another, open PR: #2960 
This PR addresses the spark-pipeline update in #2934
> Spark-Pipeline Spark Split

- scripts/cassandraTestDB.sh
This PR fixes the name of the cassandra docker image back to `cassandra` after it was incorrectly changed to `cassandra-spark`.
> Cassandra Docker Image Name Fix

- doc-examples/src/main/scala/geotrellis/doc/examples/spark/COGSparkExamples.scala
- doc-examples/src/main/scala/geotrellis/doc/examples/spark/ShardingKeyIndex.scala
- doc-examples/src/main/scala/geotrellis/doc/examples/spark/SparkExamples.scala
- doc-examples/src/main/scala/geotrellis/doc/examples/spark/VoxelKey.scala
- doc-examples/src/test/scala/geotrellis/doc/examples/spark/ShardingKeyIndexSpec.scala
This PR updates the imports of the `doc-examples` package so that they reflect the new split API.
Notes
This PR is based on two open PRs: #2960 and #2961 
This PR addresses the doc-examples update in #2934
> Spark Split Doc-Examples

- util/src/main/scala/geotrellis/util/FileRangeReader.scala
Signed-off-by: Andrey Tararaksin <atararaksin@gmail.com>
This PR changes `FileRangeReader.totalLength` so that the file length is read only once. This significantly improves performance.
I also updated `FileRangeReader` scaladocs a bit because it seemed outdated.
Closes #2992
> Read file length just once

- docs/CHANGELOG.rst
- raster/src/main/scala/geotrellis/raster/io/geotiff/compression/DeflateCompression.scala
This PR fixes an incorrect https://github.com/locationtech/geotrellis/pull/2970
> Fix incorrect Deflate compressor usage

- accumulo-spark/src/main/scala/geotrellis/spark/store/accumulo/AccumuloWriteStrategy.scala
- accumulo/src/main/scala/geotrellis/store/accumulo/AccumuloCollectionReader.scala
- cassandra-spark/src/main/scala/geotrellis/spark/store/cassandra/CassandraRDDWriter.scala
- docs/cassandra/CassandraIndexStrategySpec.scala
- s3-spark/src/main/scala/geotrellis/spark/store/s3/S3RDDWriter.scala
- s3-spark/src/main/scala/geotrellis/spark/store/s3/SaveToS3.scala
- spark/src/main/scala/geotrellis/spark/store/hadoop/geotiff/GeoTiffLayerReader.scala
- store/src/main/scala/geotrellis/store/AsyncWriter.scala
- store/src/main/scala/geotrellis/store/util/IOUtils.scala
IO will simply swallow errors unless `attempt` is called. `attempt` gives an `Either[Throwable, A]` which can be matched against to either return the value or throw. This pattern has been applied throughout the library wherever `unsafeRunSync` gets called.
Closes #2863
> Throw errors inside IO

- proj4/src/test/scala/geotrellis/proj4/mgrs/MGRSSpec.scala
The test of MGRS function has been a bit of a bugaboo.  It fails intermittently owing to its use of a random test site.  Turns out that the MGRS code that was borrowed is less than ideal, and can for some input point, return an MGRS grid cell which does not contain the point.  This is less than ideal, and merits a fix, but MGRS conversion is not something that we often have call for either by us or our users.  I've done some exploration into the MGRS conversion, and realize that it can be written to better employ our proj4 library, which will cut down the size of this particular chunk of code, and give us the opportunity to fix the erroneous code.  If we ever feel the need to fix the problem.
In the meantime, I've fudged the f&$@ out of this test.
The failures come up for points near a …
> Fix intermittently erroring MGRS tests

- accumulo-spark/src/main/scala/geotrellis/spark/store/accumulo/AccumuloLayerWriter.scala
- cassandra-spark/src/main/scala/geotrellis/spark/store/cassandra/CassandraLayerWriter.scala
- docs/CHANGELOG.rst
- hbase-spark/src/main/scala/geotrellis/spark/store/hbase/HBaseLayerWriter.scala
- layer/src/main/scala/geotrellis/layer/TileLayerMetadata.scala
- layer/src/main/scala/geotrellis/layer/merge/Implicits.scala
- layer/src/main/scala/geotrellis/layer/merge/Mergable.scala
- s3-spark/src/main/scala/geotrellis/spark/store/s3/S3LayerWriter.scala
- s3/src/main/scala/geotrellis/store/s3/S3LayerCopier.scala
- spark/src/main/scala/geotrellis/spark/store/LayerWriter.scala
- spark/src/main/scala/geotrellis/spark/store/file/FileLayerWriter.scala
- spark/src/main/scala/geotrellis/spark/store/hadoop/HadoopLayerWriter.scala
The `mergable` trait from GT is just cats' `Semigroup`. As we are now using cats, this PR replaces mergable with Semigroup.
This is pretty straightforward and doesn't attempt to rework any of the patterns (which should be revisited) through which we use `mergable` (and now `Semigroup`)
Closes #2925
> Replace mergable with semigroup

- docs/CHANGELOG.rst
- vectortile/src/main/scala/geotrellis/vectortile/Layer.scala
- vectortile/src/main/scala/geotrellis/vectortile/MVTFeature.scala
- vectortile/src/main/scala/geotrellis/vectortile/VectorTile.scala
- vectortile/src/test/scala/geotrellis/vectortile/MVTFeatureSpec.scala
- vectortile/src/test/scala/geotrellis/vectortile/ProtobufTileSpec.scala
This PR makes two small incremental changes in the absence of much larger sweeping changes to what the meaning of `Feature`s are in GeoTrellis which, due to conflicting opinions, appears best saved for another time. 
The idea here is to include a feature id as a first class citizen for the two major types of features we handle, the generic `geotrellis.vector.Feature` which approximates, but doesn't totally conform to the GeoJson spec, and the more specific `geotrellis.vectortile.MVTFeature` which conforms to the MVT2.0 spec, when before it just used `geotrellis.vector.Feature` and did not, due to the too generic `data: D` parameter and lack of an `id: Option[Long]`. 
The change to use `id: Option[String]` in `Feature` is motivated by `String` being a more "generic" type than  others in …
> Add Feature ids to vector and vectortile packages

- vector/src/main/scala/geotrellis/vector/reproject/Reproject.scala
The standard extent reprojection behavior is not safe for use when there's an underlying grid that must be correctly represented after reprojection (which is generally the case when working with rasters). Nevertheless, the correct behavior isn't available in `vector` alone and without moving methods to `raster` where they don't make sense, a warning is as good as we're going to get.
This PR doesn't fix the dangerous behavior but instead warns about it via docstring
Closes #2990
> Warn about extent reprojection behavior

- docs/CHANGELOG.rst
- layer/src/main/scala/geotrellis/layer/stitch/Implicits.scala
- layer/src/main/scala/geotrellis/layer/stitch/StitchCollectionMethods.scala
- spark-testkit/src/main/scala/geotrellis/spark/testkit/TileLayerRDDBuilders.scala
- spark/src/main/scala/geotrellis/spark/stitch/Implicits.scala
- spark/src/main/scala/geotrellis/spark/stitch/StitchRDDMethods.scala
- spark/src/test/scala/geotrellis/spark/stitch/CollectionStitchMethodsSpec.scala
- spark/src/test/scala/geotrellis/spark/stitch/RDDStitchMethodsSpec.scala
Adds sparseStitch methods to `SpatialTileLayoutCollectionStitchMethods`. The method uses a different algorithm, and therefore it felt more correct to name it differently from the original `stitch(): Raster[V]`. Also added a helper so that users who want to use the collection extent don't have to know how to get it, since this is the most likely default use case.
Opened PR to get tests to run, since there's a breaking change on the type bounds of V. Initial testing in a few key places didn't raise any issues but I want the whole test suite to run. **Edit:** Full test suite passed, but upon further inspection it looks like we might not test stitch anywhere else.
I want to add a unit test or two because there's nothing at all for any of these stitch functions, but that looks like its a bit …
> Add sparse stitch method to StitchCollectionMethods

- docs/CHANGELOG.rst
- s3/src/main/scala/geotrellis/store/s3/util/S3RangeReader.scala
This PR changes how the `totalLength` value of `S3RangeReader` is computed. It will now use a `GetObjectResponse` instead of a `GetHeaderResponse`. This will allow users to read these files even if they don't have permission to access its `HEADER`.
Closes #2889
> S3RangeReader totalLength Improvment

- layer/src/main/scala/geotrellis/layer/TileLayerMetadata.scala
- layer/src/test/scala/geotrellis/layer/TileLayerMetadataSpec.scala
- store/src/main/scala/geotrellis/store/json/Implicits.scala
- store/src/test/scala/geotrellis/store/json/SchemaJsonSpec.scala
So that we properly serialize/deserialize LayoutDefinition
to the "layoutDefinition" key instead of "layout" thus maintaining backwards compatibility for the metadata key of our geotrellis layer metadata.json files.
This also adds a test to help catch backwards compatibility issues
in encoding/decoding TileLayerMetadata
```scala
import geotrellis.layer._
import geotrellis.store._
import geotrellis.store.s3._
val bucket = "ingested-loca-data"
val prefix = "CCSM4"
val store = S3AttributeStore(bucket, prefix)
val id = LayerId("CCSM4_rcp85_r6i1p1", 0)
store.readMetadata[TileLayerMetadata[SpaceTimeKey]](id)
// Before:
io.circe.DecodingFailure$$anon$2: Attempt to decode value on failed cursor: DownField(layout),DownField(metadata)
// After
res0: …
```
> Fix Circe decoders for TileLayerMetadata Schema and Metadata.layoutDefinition

- docs/CHANGELOG.rst
- util/src/main/scala/geotrellis/util/FileRangeReader.scala
- util/src/main/scala/geotrellis/util/FileRangeReaderProvider.scala
- util/src/test/scala/geotrellis/util/FileRangeReaderProviderSpec.scala
This PR fixes a bug in `FileRangeReaderProvider` where it was unable to process certain `URI`s. Looking into the issue, I found the cause of the problem to be with [how we were converting URIs to Files](https://github.com/locationtech/geotrellis/blob/master/util/src/main/scala/geotrellis/util/FileRangeReaderProvider.scala#L31). It turns out that `Paths.get` has [certain restrictions](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Paths.html#get(java.net.URI)) on how the `URI` has to be formatted. These differ from the `URI` specification, and can sometimes cause properly formatted `URI`s to be denied.
What I ended up deciding on was to simply pass in a `String` to `Paths.get` in order to get around the different `URI` requirements. To do that, I first check to see if the given …
> FileRangeReader Improved URI Handeling

- docs/guide/core-concepts.rst
- Some minor typo fixes
- Made section header structure more consistent in some places
> (docs) minor typo and structure fixes in core-concepts.rst

- vector/src/main/scala/geotrellis/vector/JTS.scala
Fixes a whoopsie from #2932.  This will make sure that multi-geometry constructors are available from the `JTS` object.
> Make sure multi-geometry constructors are available in the shell

- README.md
- docs/tutorials/setup.rst
minor README.md tweak to make sure the example also works for scala 2.12
I picked `"geotrellis-raster" % "2.2.0"` because that works for both scala 2.11 and 2.12 by default
> README: updated some "Getting Started" versions

- bench/src/main/scala/geotrellis/bench/package.scala
- bench/src/main/scala/geotrellis/proj4/CRSBench.scala
- bench/src/main/scala/geotrellis/raster/GenericRasterBench.scala
- bench/src/main/scala/geotrellis/raster/render/RenderBench.scala
- bench/src/main/scala/geotrellis/raster/reproject/RasterizingReprojectBench.scala
- bench/src/main/scala/geotrellis/spark/store/index/MergeQueueBench.scala
- build.sbt
- docs/CHANGELOG.rst
- proj4/src/main/scala/geotrellis/proj4/CRS.scala
- proj4/src/main/scala/geotrellis/proj4/ConusAlbers.scala
- proj4/src/main/scala/geotrellis/proj4/LatLng.scala
- proj4/src/main/scala/geotrellis/proj4/WebMercator.scala
- project/Dependencies.scala
- project/Settings.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReaderSpec.scala
This PR updates proj4 version up to https://github.com/locationtech/proj4j/pull/33
[Benchmarking results](https://github.com/locationtech/geotrellis/blob/64903273b4f6532fc2372d7bc0c65a06846c710f/bench/src/main/scala/geotrellis/proj4/CRSBench.scala):
```
/**
* jmh:run -i 3 -wi 3 -f1 -t1 .*CRSBench.*
*
* LazyCRS (rasterframes fix):
* [info] Benchmark                        Mode  Cnt   Score    Error  Units
* [info] CRSBench.logicalEqualsFalse      avgt    3  13.534 ±  6.396  us/op
* [info] CRSBench.logicalEqualsTrue       avgt    3   0.254 ±  0.116  us/op
* [info] CRSBench.logicalLazyEqualsFalse  avgt    3  14.505 ± 10.106  us/op
* [info] CRSBench.logicalLazyEqualsTrue   avgt    3   0.035 ±  0.007  us/op
* [info] CRSBench.resolveCRS              avgt    3   0.069 ±  0.082  us/op
*
* Proj4 …
```
> Bump proj4 version to fix multiple performance issues

- vectortile/src/main/scala/geotrellis/vectortile/internal/package.scala
- vectortile/src/test/scala/geotrellis/vectortile/ProjectionSpec.scala
This PR fixes an error that can sometimes cause geometries to be dropped and/or shifted when reading them from a `VectorTile` and then writing them back. The issue was caused by using the top left corner of the pixel of the tile as the reference for the projected coordinates; as this would cause some projected points to either move, or fall outside of the tile when converting those projected coordinates back to VectorTile coordinates.
The solution was then to change the reference point from being in the corner of the pixel to being in the center.
I think I will need to talk with someone more before I can remove the `[WIP]` from this PR. Because right now the changes introduced causes other tests to fail, and I'm not sure if that behavior is okay or not. Also, I've not been able to …
> VectorTile Geometry Recentering

- docs/CHANGELOG.rst
- spark/src/main/scala/geotrellis/spark/store/http/util/HttpRangeReader.scala
- spark/src/test/scala/geotrellis/spark/store/http/util/HttpRangeReaderSpec.scala
HttpRangeReader now throws with an HttpStatusException if the server responds with any 4xx or 5xx status code.
This is a bit more of an expansive fix than specifically just catching 404s, but as far as I can tell, it's correct to catch and throw a helpful error here for any 4xx or 5xx series HTTP error so that the client can handle them properly.
Closes #2791
> Fix #2791: HttpRangeReader swallows 404s

- docs/CHANGELOG.rst
- proj4/src/main/scala/geotrellis/proj4/CRS.scala
- proj4/src/main/scala/geotrellis/proj4/io/wkt/WKT.scala
- proj4/src/main/scala/geotrellis/proj4/io/wkt/WKTParser.scala
- proj4/src/test/scala/geotrellis/proj4/CRSTest.scala
- proj4/src/test/scala/geotrellis/proj4/io/wkt/WKTParserTest.scala
- proj4/src/test/scala/geotrellis/proj4/io/wkt/WKTTest.scala
This PR cleans up the conversion methods on the `WKT` object to:
- All operations now return `Option`s. Before, we would silently unwrap results within the method calls, leading to thrown errors. It's now up to the calling code to unwrap and determine what to do in case of conversion failure, as it always should have been.
- Methods that convert from EPSG code to WKT string are consistently prefixed with `fromEpsg`
- Methods that convert from WKT string to EPSG code are consistently prefixed with `getEpsg`
It also updates `CRS.fromWKT` to return an `Option[CRS]` instead of just `CRS`. Same issue as above, the method would silently unwrap an optional result internally, which could lead to errors.
I was a bit surprised that we don't utilize any of these methods in other GeoTrellis modules. …
> Clean up WKT <--> EPSG conversion methods

- s3/src/main/scala/geotrellis/store/s3/util/S3RangeReader.scala
On the `InputStream.close` call it was downloading the entire resource on release. To avoid it, we need explicitly to call the `abort` method.
Closes #3078
> Fix full stream read on the input stream close

- docs/CHANGELOG.rst
- layer/src/main/scala/geotrellis/layer/filter/Implicits.scala
- layer/src/main/scala/geotrellis/layer/filter/SpaceTimeToSpatialMethods.scala
- layer/src/main/scala/geotrellis/layer/filter/ToSpatial.scala
- layer/src/main/scala/geotrellis/layer/filter/package.scala
Closes https://github.com/locationtech/geotrellis/issues/3043
> Add a toSpatial operation to our collections API

- docs/CHANGELOG.rst
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/TiffTagsReader.scala
Our GeoTIFF Reader supports not all the tiff tags types, this PR adds an ability to skip unknown tags. This PR partially covers https://github.com/locationtech/geotrellis/issues/3085 but doesn't introduce `TIFFTAG_EXIFIFD` tag support.
> Fix TIFFTagsReader to skip unsupported tags

- docs/CHANGELOG.rst
- vector/src/main/scala/geotrellis/vector/reproject/Reproject.scala
- vector/src/test/scala/spec/geotrellis/vector/reproject/ReprojectSpec.scala
This PR resolves the division by zero unhandled case in the `reprojectExtentAsPolygon` function,
Closes https://github.com/locationtech/geotrellis/issues/3023
> reprojectExtentAsPolygon should be more deterministic

- s3-spark/src/main/scala/geotrellis/spark/store/s3/cog/S3COGLayerReader.scala
- s3-spark/src/main/scala/geotrellis/spark/store/s3/geotiff/S3GeoTiffLayerReader.scala
- s3/src/main/scala/geotrellis/store/s3/cog/S3COGCollectionLayerReader.scala
- s3/src/main/scala/geotrellis/store/s3/cog/S3COGValueReader.scala
- spark/src/main/scala/geotrellis/spark/store/cog/COGLayerReader.scala
- spark/src/main/scala/geotrellis/spark/store/file/cog/FileCOGLayerReader.scala
- spark/src/main/scala/geotrellis/spark/store/file/cog/FileCOGLayerWriter.scala
- spark/src/main/scala/geotrellis/spark/store/file/geotiff/FileGeoTiffLayerReader.scala
- spark/src/main/scala/geotrellis/spark/store/hadoop/cog/HadoopCOGLayerReader.scala
- spark/src/main/scala/geotrellis/spark/store/hadoop/cog/HadoopCOGLayerWriter.scala
- spark/src/main/scala/geotrellis/spark/store/hadoop/geotiff/GeoTiffLayerReader.scala
- spark/src/main/scala/geotrellis/spark/store/hadoop/geotiff/HadoopGeoTiffLayerReader.scala
- spark/src/main/scala/geotrellis/spark/store/http/util/HttpRangeReaderProvider.scala
- spark/src/test/scala/geotrellis/spark/store/http/util/HttpRangeReaderProviderSpec.scala
- store/src/main/scala/geotrellis/store/cog/COGCollectionLayerReader.scala
- store/src/main/scala/geotrellis/store/cog/COGValueReader.scala
- store/src/main/scala/geotrellis/store/file/cog/FileCOGCollectionLayerReader.scala
- store/src/main/scala/geotrellis/store/file/cog/FileCOGValueReader.scala
- store/src/main/scala/geotrellis/store/hadoop/cog/HadoopCOGCollectionLayerReader.scala
- store/src/main/scala/geotrellis/store/hadoop/cog/HadoopCOGValueReader.scala
- util/src/test/scala/geotrellis/util/FileRangeReaderProviderSpec.scala
Replace getByteReader interfaces with direct calls to RangeReader, using the new SPI.
Didn't update docs, but I did create a new issue #3092 to address the out of date docs in S3Streaming.md
No update to CHANGELOG since this is an entirely internal change. Can make a note of it though if desired.
Pending tests passing...
Closes #3013
> Use RangeReader SPI in Layer[Reader|Writer] classes

- raster/src/main/scala/geotrellis/raster/reproject/RasterReprojectMethods.scala
- raster/src/test/scala/geotrellis/raster/reproject/ReprojectSpec.scala
Windowed raster reprojection formerly constructed its window via `extentFor`, which by default has clamp set to true. Quoting the docstring, "If true, the returned extent will be contained by this RasterExtent's extent". This is fine, in most cases, but it means we can't assume that the output `RasterExtent` it produces can meaningfully be used along with `GridBounds.height`/`width` to reconstruct a RasterExtent (as the output `RasterExtent` might not have the same number of columns/rows as the `GridBounds` from which it is derived).
We can avoid this problem by simply using `CellSize` rather than cols/rows.
This change required slightly widened tolerances for comparing `CellSize` values (0.05 -> 0.08)
> Fix windowed reproject bug

- raster/src/main/scala/geotrellis/raster/resample/TileResampleMethods.scala
- raster/src/main/scala/geotrellis/raster/stitch/Stitcher.scala
- s3-spark/src/main/scala/geotrellis/spark/store/s3/cog/S3COGLayerWriter.scala
- spark/src/main/scala/geotrellis/spark/merge/TileRDDMerge.scala
- spark/src/main/scala/geotrellis/spark/merge/TileRDDMergeMethods.scala
- spark/src/main/scala/geotrellis/spark/regrid/Implicits.scala
- spark/src/main/scala/geotrellis/spark/regrid/Regrid.scala
- spark/src/main/scala/geotrellis/spark/regrid/RegridMethods.scala
- spark/src/main/scala/geotrellis/spark/resample/ZoomResample.scala
While working on refactors around CellGrid I noticed that in lots of places we're constraining `V` eagerly on this trait, this PR tries to minimize that.
This should not have any effect on the user aside from usual bin compatibility breakage. The caller always knows either the full type of `V` or is free to constrain the type to the point that is useful.
Since this is code hygiene looking for a +1 before morning this.
> Remove unnecessary CellGrid constraints

- docs/CHANGELOG.rst
- s3-spark/src/test/scala/geotrellis/spark/store/s3/S3NoPrefixSpec.scala
- s3/src/main/java/geotrellis/store/s3/AmazonS3URI.java
- s3/src/main/scala/geotrellis/store/s3/S3AttributeStore.scala
- scripts/runTestS3.sh
AmazonS3URI will have a null `key` if the user passes a uri that doesn't contain one, such as `s3://foo`. This gets passed down into the various S3 reader/writer classes in GeoTrellis, and is converted to an empty string in some cases but not others.
In some cases, an S3LayerWriter will be constructed using the attached S3AttributeStore bucket + keyPrefix, if we know we're getting an S3AttributeStore. Otherwise the S3LayerWriter will be constructed using passed in bucket/keyPath values which can come from anywhere, including the nullable `AmazonS3URI.key`.
The quickest, least disruptive, and most comprehensive method seemed to be to fixup the `AmazonS3URI.getKey` method to return `""` instead of `null` and also add an additional error check in the `S3AttributeStore` apply method that …
> Fix S3LayerWriter NullPointerException

- docs/CHANGELOG.rst
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffSegment.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/BitGeoTiffTileSpec.scala
This PR fixes `GeoTIffTile` `CellType` conversion, in particular `GeoTiffSegment` `CellType` conversions. During the work on this fix, it became obvious that our TIFF API doesn't support a proper work with `striped` `BitTiffs` (this fact made this issue debugging a bit more tricky), that is why this PR at least covers `Tiled` tiffs support.
Fixes https://github.com/locationtech/geotrellis/issues/3055 
This issue indeed closes #3055 in any case, since COGs are Tiled TIFFs. If this PR won't cover `Striped` TIFFs support, I will create a separate issue to address it. This PR blocks a 3.0 release, a complete striped bit TIFFs support does not.
> Fix Tiled TIFF BitCellType Segments conversion

- docs/CHANGELOG.rst
- spark/src/main/scala/geotrellis/spark/costdistance/IterativeCostDistance.scala
- spark/src/main/scala/geotrellis/spark/viewshed/IterativeViewshed.scala
- spark/src/test/scala/geotrellis/spark/costdistance/IterativeCostDistanceSpec.scala
The compute resolution method in Iterative Cost Distance was calcultating the
cell size based on the length of a degree at the equator without scaling for
the current latitude. This introduces an error as you move away from the
equator. The same method in Iterative Viewshed compensates for this and
maintains greater spatial accuracy.
See issue https://github.com/locationtech/geotrellis/issues/3103
Signed-off-by: jmtaysom <james.taysom@gmail.com>
The compute resolution method in Iterative Cost Distance was calcultating the
cell size based on the length of a degree at the equator without scaling for
the current latitude. This introduces an error as you move away from the
equator. The same method in Iterative Viewshed compensates for this and
maintains greater spatial accuracy.
Closes #3103
> updated computeResolution in IterativeCostDistance to match Iterative Viewshed

- gdal/src/main/scala/geotrellis/raster/gdal/GDALRasterSource.scala
- gdal/src/main/scala/geotrellis/raster/gdal/GDALWarpOptions.scala
- gdal/src/test/scala/geotrellis/raster/gdal/GDALWarpOptionsSpec.scala
- raster/src/main/scala/geotrellis/raster/MosaicRasterSource.scala
- raster/src/main/scala/geotrellis/raster/RasterSource.scala
- raster/src/main/scala/geotrellis/raster/ResampleTarget.scala
- raster/src/main/scala/geotrellis/raster/geotiff/GeoTiffRasterSource.scala
- raster/src/main/scala/geotrellis/raster/geotiff/GeoTiffReprojectRasterSource.scala
- raster/src/main/scala/geotrellis/raster/geotiff/GeoTiffResampleRasterSource.scala
- spark/src/main/scala/geotrellis/spark/RasterSummary.scala
- spark/src/test/scala/geotrellis/spark/RasterSummarySpec.scala
- store/src/main/scala/geotrellis/store/GeoTrellisRasterSource.scala
- store/src/main/scala/geotrellis/store/GeoTrellisReprojectRasterSource.scala
- store/src/main/scala/geotrellis/store/GeoTrellisResampleRasterSource.scala
We want to avoid type parameters from being propagated throughout the library when they aren't absolutely necessary. This PR hides the [N: Integral] type parameter which was formerly on
each ResampleGrid class. Additionally, it renames `ResampleGrid` to `ResampleTarget` (as the grid is what is produced rather than the case class itself) and renames `Dimensions` as `TargetDimensions` for consistency and renames the `IdentityResampleGrid` as `DefaultTarget` to better reflect its context-dependent nature (the exact operation which is "default" is dependent on which resample/reprojection function is being used.
> Refactor ResampleGrid names and type parameter

- .travis.yml
- .travis/build-and-test.sh
- .travis/scaladocs.sh
- build.sbt
Broken since Oct 2018 in https://github.com/locationtech/geotrellis/commit/389cda41e1163598c8f361d5c097628744c0b30b#diff-354f30a63fb0907d4ad57269548329e3
Since then, a few things "broke" the build:
- new param in build.sbt for passing scaladoc info to the doc generator
- split build with RUN_SET env variable, so now we need to also only deploy in one of those
- swap to conditional deploy on openjdk8
- [-] `docs/CHANGELOG.rst` updated, if necessary
- [-] `docs` guides update, if necessary
- [-] New user API has useful Scaladoc strings
- [-] Unit tests added for bug-fix or new feature
The HEAD commit of geotrellis/scaladocs should have a recent commit: https://github.com/geotrellis/scaladocs/tree/gh-pages/latest
I attempted to use the [Travis gh-pages deployment …
> Fix scaladoc deployment to latest folder on master branch merges

- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffSegment.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/BitGeoTiffTileSpec.scala
This PR allows to read properly single striped tiffs and some other segments sizes that work accidentally.
> The bit segment size should be padded to fit space allocated in bytes

- .travis/build-and-test-set-1.sh
- CHANGELOG.md
- util/src/main/scala/geotrellis/util/StreamingByteReader.scala
Extracts bug fix from https://github.com/locationtech/geotrellis/pull/3135
When reading past end of file `StreamingRangeReader` would allocate array for the site it was intending to read, rather than actual size that was read when requested read range is past EOF.
> Fix StreamingByteReader over-allocation past EOF

- .travis/build-and-test-set-1.sh
- CHANGELOG.md
- build.sbt
- raster/src/main/scala/geotrellis/raster/ArrayTile.scala
- raster/src/main/scala/geotrellis/raster/ConstantTile.scala
- raster/src/main/scala/geotrellis/raster/DelegatingTile.scala
- raster/src/main/scala/geotrellis/raster/MosaicRasterSource.scala
- raster/src/main/scala/geotrellis/raster/MultibandTile.scala
- raster/src/main/scala/geotrellis/raster/MutableArrayTile.scala
- raster/src/main/scala/geotrellis/raster/ProjectedRasterLike.scala
- raster/src/main/scala/geotrellis/raster/RasterRegion.scala
- raster/src/main/scala/geotrellis/raster/RasterSource.scala
- raster/src/main/scala/geotrellis/raster/Tile.scala
- util/src/main/scala/geotrellis/util/StreamingByteReader.scala
This PR makes Tile, ArrayTile and MultibandTile abstract classes. In our types hierarchy `Tile` types extend `CellGrid` and `Grid`. In 2.x both `Tile` and `CellGrid` were `traits`, and in `3.x` `CellGrid` became an abstract class, so we had a not very usual case, where `traits` extended abstract `classes`. This is not possible in Java and creates problems on Spark, for more details looks into https://github.com/locationtech/geotrellis/issues/3134
This is the idea suggested by @echeipesh and it is probably the best solution.
```scala
scala> :javap geotrellis.raster.Tile
Size 11433 bytes
MD5 checksum 973688ee6c0ddfd43788d33a6cee0989
Compiled from "Tile.scala"
public abstract class geotrellis.raster.Tile extends geotrellis.raster.CellGrid<java.lang.Object> implements …
```
> All traits that inherit CellGrid and Grid should be abstract classes

- spark/src/main/scala/geotrellis/spark/Implicits.scala
Signed-off-by: Frank Dekervel <frank@kapernikov.com>
without this, trying to do getBounds on a RDD will result in a serialisation error on spark 2.4.4.
with this trivial change applied, getBounds works without error.
I did not update any other code as this change is completely trivial and in line with the rest of the classes in the same file.
> make withGetBoundsMethod serializable

- raster/src/main/scala/geotrellis/raster/mapalgebra/focal/hillshade/Hillshade.scala
remove unnecessary slope and aspect calculations.
Two questions:
1. In terms of `zFactor`, should it be better to put this parameter to `SurfacePointCalculation` class?
in method `calcSurface` like this:
```scala
s.`dz/dx` = zFactor * (neValue + 2*eValue + seValue - nwValue - 2*wValue - swValue) / (8 * cellWidth)
s.`dz/dy` = zFactor * (swValue + 2*sValue + seValue - nwValue - 2*nValue - neValue) / (8 * cellHeight)
```
2. in the expression `resultTile.set(x, y, round(127.0 * max(0.0, v)).toInt)` of the commited file, why `127.0` is set here while it is `255.0` in [https://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/how-hillshade-works.htm](https://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/how-hillshade-works.htm)
> Remove unnecessary calculations in Hillshade

- raster/src/main/scala/geotrellis/raster/ArrayTile.scala
- raster/src/test/scala/geotrellis/raster/ArrayTileSpec.scala
As evidenced by the test, `DelegatingTile` is not able to provide commutative assurances with operations using the `combine`/`combineDouble` mechanism.
~- [ ] [docs/CHANGELOG.rst](https://github.com/locationtech/geotrellis/blob/master/CHANGELOG.md) updated, if necessary~
~- [ ] [Module Hierarcy](https://github.com/locationtech/geotrellis/blob/master/docs/guide/module-hierarchy.rst) updated, if necessary~
~- [ ] `docs` guides update, if necessary~
~- [ ] New user API has useful Scaladoc strings~
See unit test
Closes #3153
> Fixes fallback implementation of `ArrayTile.combine` for `DelegatingTile`

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/rasterize/polygon/PolygonRasterizer.scala
- raster/src/test/scala/geotrellis/raster/rasterize/polygon/PolygonRasterizerSpec.scala
Signed-off-by: Andrey Tararaksin <atararaksin@gmail.com>
This PR fixes `PolygonRasterizer` crash described in #3160. Consider a scanline crossing two edges of a polygon in two separate (non-vertex) points. If x-coords of these points are calculated as identical Doubles (due to a Double-related error), the crash occurs.
This PR fixes this issue by recalculating such coordinates using precise `spire.math.Rational`. This recalculation is performed for a given row if it contains two or more matching Double x-coords. It is a very rare case and for a typical polygon occurs zero to little times, so the general-case performance is not affected.
Closes #3160
> Fix polygon rasterizer crash

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/TiffTags.scala
- raster/src/main/scala/geotrellis/raster/io/json/Implicits.scala
- spark-pipeline/src/main/scala/geotrellis/spark/pipeline/json/Implicits.scala
This removes a duplicate codec for `TileLayout` - there is already one [here](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/io/json/Implicits.scala) and it is really easy to get in a situation where both are available and hit an ambiguous implicit error.
> Remove duplicate circe json codec

- .travis/hbase-install.sh
- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffSegment.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/UInt16GeoTiffTileSpec.scala
This PR fixes a wrong `TIFF` segments conversion into the `Byte` and `UByte` `CellType`s and also adds a test case.
Thanks @santocp94 for reproting about it.
> Fix GeoTiff Byte and UByte CellType conversions

- CHANGELOG.md
- store/src/main/scala/geotrellis/store/GeoTrellisPath.scala
- store/src/test/scala/geotrellis/store/GeoTrellisPathSpec.scala
Parsing of url authority was bad. This should fix that. This PR also opened a discussion around whether absolute and relative urls without scheme should be valid as well so there's tests for those here that currently fail. If we want to support this, I can add a fix for that here as well, where scheme-less urls assume `file://`.
Before fix, 7 of new tests fail. After, only the scheme-less tests fail.
> Fix GeoTrellisPath parsing

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/mapalgebra/focal/ZFactor.scala
This PR fixes a typo in the ZFactor constants. Thanks @Frophie for the report.
> Fix the length of one degree at the equator in metres

- CHANGELOG.md
- gdal/src/main/scala/geotrellis/raster/gdal/GDALRasterSource.scala
- gdal/src/test/scala/geotrellis/raster/gdal/GDALRasterSourceSpec.scala
- project/Dependencies.scala
- project/Settings.scala
- raster/src/main/scala/geotrellis/raster/RasterMetadata.scala
- raster/src/test/scala/geotrellis/raster/geotiff/GeoTiffRasterSourceSpec.scala
- spark/src/test/scala/geotrellis/store/GeoTrellisRasterSourceSpec.scala
- store/src/main/scala/geotrellis/store/GeoTrellisReprojectRasterSource.scala
This PR: 
This issues makes `GDALRasterSource`, `GeoTiffRasterSource` and `DEMRasterSource` to behave more consistent.
Related to #3210
Closes #3212
> Make GDALRasterSource behavior consistent with other RasterSources

- README.md
- gdal/src/main/scala/geotrellis/raster/gdal/GDALRasterSource.scala
- gdal/src/test/scala/geotrellis/raster/gdal/GDALRasterSourceSpec.scala
- gdal/src/test/scala/geotrellis/raster/gdal/GDALReprojectRasterSourceSpec.scala
- layer/src/test/scala/geotrellis/raster/geotiff/GeoTiffReprojectRasterSourceSpec.scala
- project/Settings.scala
- raster/src/main/scala/geotrellis/raster/RasterMetadata.scala
- spark/src/test/scala/geotrellis/store/GeoTrellisRasterSourceSpec.scala
This PR makes `GDALRasterSource` behave like all other RasterSources.
It also adds extra tests to test that `GeoTrellisReprojectRasterSource` behaves similar to other `RasterSources`.
Closes #3210
> GDALRasterSource should behave consistent across other RasterSources

- .gitignore
- .travis/hbase-install.sh
- CHANGELOG.md
- layer/src/main/scala/geotrellis/layer/LayoutDefinition.scala
- layer/src/main/scala/geotrellis/layer/ZoomedLayoutScheme.scala
- raster/src/main/scala/geotrellis/raster/ArrayMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/ArrayTile.scala
- raster/src/main/scala/geotrellis/raster/DelayedConversionMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/DelayedConversionTile.scala
- raster/src/main/scala/geotrellis/raster/DelegatingTile.scala
- raster/src/main/scala/geotrellis/raster/geotiff/GeoTiffRasterSource.scala
- raster/src/main/scala/geotrellis/raster/geotiff/GeoTiffReprojectRasterSource.scala
- raster/src/main/scala/geotrellis/raster/geotiff/GeoTiffResampleRasterSource.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffTile.scala
Added some `toString` overrides to commonly used classes that make the REPL output more readable.
```scala
scala> val source = GeoTiffRasterSource("/tmp/aspect.tif")
source: geotrellis.raster.geotiff.GeoTiffRasterSource = GeoTiffRasterSource(/tmp/aspect.tif)
scala> val wm = source.reproject(WebMercator)
wm: geotrellis.raster.RasterSource = GeoTiffReprojectRasterSource(/tmp/aspect.tif,WebMercator,DefaultTarget,NearestNeighbor)
scala> val raster = wm.read(GridBounds(0L,0L,255L,255L)).get
raster: geotrellis.raster.Raster[geotrellis.raster.MultibandTile] = Raster(ArrayMultibandTile(256,256,1,float32ud-9999.0),Extent(-8769150.640916323, 4271288.442457698, -8765983.641700394, 4274455.441673627))
scala> raster.tile.band(0)
res0: geotrellis.raster.Tile = ArrayTile(256,256,float32ud-9999.0)
```
> Add toString and comments

- CHANGELOG.md
- spark/src/main/scala/geotrellis/spark/partition/PartitionerIndex.scala
- spark/src/main/scala/geotrellis/spark/partition/ReorderedRDD.scala
- spark/src/main/scala/geotrellis/spark/partition/SpacePartitioner.scala
- spark/src/test/scala/geotrellis/spark/join/SpatialJoinRDDSpec.scala
- spark/src/test/scala/geotrellis/spark/partition/ReorderedRDDSpec.scala
- spark/src/test/scala/geotrellis/spark/partition/TestImplicits.scala
Fixes issue described at #3168 
The original implementation blindly assumed same partition indexing, causing empty join when using custom partitioning with one of the RDDs being joined.
This PR adds tests for this use case and fixes the issue by adding an additional check that same PartitionIndexer is used, so that reshuffle is triggered when that is not the case.
PR also fixed some inactive asserts in same file.
It also addresses partitioning mismatch in ReorderedSpaceRDD
-  <del>[Module Hierarcy](https://github.com/locationtech/geotrellis/blob/master/docs/guide/module-hierarchy.rst) updated, if necessary </del>
-  <del>`docs` guides update, if necessary</del>
-  <del>New user API has useful Scaladoc strings</del>
Closes #3168
> Fix spatial join when left and right rdd have different PartitionerIndex

- raster/src/main/scala/geotrellis/raster/RasterMetadata.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala
Improves documentation regarding the resolutions list provided by `RasterMetadata` and consumed by `OverviewStrategy`.
> Clarify docstrings about resolution lists

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/summary/polygonal/PolygonalSummaryResult.scala
This PR fixes the implementation of the Monad instance to avoid self-recursion
```scala
scala> val s: PolygonalSummaryResult[Int] = Summary(3)
s: geotrellis.raster.summary.polygonal.PolygonalSummaryResult[Int] = Summary(3)
scala> s.map(x => x.toString)
java.lang.StackOverflowError
at cats.Monad$$Lambda$6830/427965418.<init>(Unknown Source)
at cats.Monad$$Lambda$6830/427965418.get$Lambda(Unknown Source)
at cats.Monad.map(Monad.scala:16)
at cats.Monad.map$(Monad.scala:14)
at geotrellis.raster.summary.polygonal.PolygonalSummaryResult$$anon$1.map(PolygonalSummaryResult.scala:42)
at geotrellis.raster.summary.polygonal.PolygonalSummaryResult$$anon$1.flatMap(PolygonalSummaryResult.scala:45)
at geotrellis.raster.summary.polygonal.PolygonalSummaryResult$$anon$1.flatMap(PolygonalSummaryResult.scala: …
```
> Fix Monad instance for PolygonalSummaryResult

- CHANGELOG.md
- gdal/src/main/scala/geotrellis/raster/gdal/GDALRasterSource.scala
- raster/src/main/scala/geotrellis/raster/MosaicRasterSource.scala
- raster/src/main/scala/geotrellis/raster/RasterMetadata.scala
- raster/src/main/scala/geotrellis/raster/RasterSource.scala
- raster/src/main/scala/geotrellis/raster/geotiff/GeoTiffRasterSource.scala
- raster/src/main/scala/geotrellis/raster/geotiff/GeoTiffReprojectRasterSource.scala
- raster/src/main/scala/geotrellis/raster/geotiff/GeoTiffResampleRasterSource.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala
- store/src/main/scala/geotrellis/store/AttributeStore.scala
- store/src/main/scala/geotrellis/store/GeoTrellisRasterSource.scala
- store/src/main/scala/geotrellis/store/GeoTrellisReprojectRasterSource.scala
- store/src/main/scala/geotrellis/store/GeoTrellisResampleRasterSource.scala
- store/src/main/scala/geotrellis/store/Implicits.scala
This PR updates GeoTrellisRasterSource to work with GeoTrellis legacy (1.x and 2.x) layers
and with temporal layers.
https://github.com/geotrellis/geotrellis-server#191
https://github.com/locationtech/geotrellis/pull/3180
Closes #3179
> Backport GeoTrellisRasterSource updates from the GeoTrellis server

- CHANGELOG.md
- store/src/main/scala/geotrellis/store/GeoTrellisRasterSource.scala
- store/src/main/scala/geotrellis/store/GeoTrellisReprojectRasterSource.scala
- store/src/main/scala/geotrellis/store/GeoTrellisResampleRasterSource.scala
We had a broken GeoTrellisRasterSources temporal support that was revelaed in terms of https://github.com/geotrellis/geotrellis-server/issues/248
This PR fixes the bad GeoTrellisRasterSoruces behavior.
Brief description of what this PR does, and why it is needed. The issue https://github.com/locationtech/geotrellis/issues/3225 is still valid. 
However, because GeoTrellisRasterSources work only with a single temporal slice. index overflows during the query ranges generation should never happen.
Addresses https://github.com/geotrellis/geotrellis-server/issues/248
> Fix GeoTrellisRasterSources to properly pass time though all the internal functions

- CHANGELOG.md
- gdal/src/main/scala/geotrellis/raster/gdal/GDALUtils.scala
- gdal/src/test/resources/log4j.properties
- raster/src/main/scala/geotrellis/raster/io/geotiff/OverviewStrategy.scala
This PR makes overview selection methods a bit more silent.
> Move GDAL overview strategy logger to debug level

- CHANGELOG.md
- s3-spark/src/main/scala/geotrellis/spark/store/s3/S3LayerReader.scala
Partitions never got used and for some reason are locked to `3`.
> Fix S3RDDLayerReader partitioning

- CHANGELOG.md
- gdal/src/main/scala/geotrellis/raster/gdal/GDALDataset.scala
- gdal/src/main/scala/geotrellis/raster/gdal/GDALUtils.scala
- gdal/src/test/scala/geotrellis/raster/gdal/GDALRasterSourceSpec.scala
- project/Dependencies.scala
This PR simplifies GDAL CellType derivation function and adds consistency specs
Closes #3232
> GDALRasterSource should work consistent with BitCellType and ByteCellType

- CHANGELOG.md
- gdal/src/main/scala/geotrellis/raster/gdal/GDALDataset.scala
- store/src/main/scala/geotrellis/store/hadoop/package.scala
- store/src/main/scala/geotrellis/store/hadoop/util/HdfsRangeReader.scala
This PR adds `gs://` into the list of supported URI by the HdfsRangeReaderLayerProvider
> Add GS in the list of supported URI schemes

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/rasterize/Rasterizer.scala
This PR fixes rasterize function to behave like rasterizeWithValue function
> Rasterizer.rasterize should be consistent with rasterizeWithValue

- CHANGELOG.md
- layer/src/main/scala/geotrellis/layer/stitch/StitchCollectionMethods.scala
- spark/src/main/scala/geotrellis/spark/stitch/StitchRDDMethods.scala
- spark/src/test/scala/geotrellis/spark/stitch/CollectionStitchMethodsSpec.scala
- store/src/main/scala/geotrellis/store/GeoTrellisRasterSource.scala
This PR removes a duplicate `GeoTrellisRasterSource.sparseStitch` function that also was not safe enough and could work (incorrectly) with empty inputs.
This bug was revelaed during [this issue](https://github.com/geotrellis/geotrellis-server/issues/258) investigation.
> GeoTrellisRasterSource should return None on empty reads

- .circleci/scaladocs.sh
- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/ArrayTile.scala
- raster/src/test/scala/geotrellis/raster/ArrayTileSpec.scala
This PR Fixes the bad comparison method
Closes #3242
> Fix bad ArrayTile equals

- CHANGELOG.md
- proj4/src/main/scala/geotrellis/proj4/CRS.scala
- proj4/src/main/scala/geotrellis/proj4/io/wkt/WKT.scala
- proj4/src/main/scala/geotrellis/proj4/io/wkt/WKTParser.scala
- proj4/src/main/scala/geotrellis/proj4/io/wkt/WktCS.scala
- proj4/src/test/scala/geotrellis/proj4/io/wkt/WKTParserTest.scala
- proj4/src/test/scala/geotrellis/proj4/io/wkt/WKTTest.scala
> WKTParser extension support

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/io/geotiff/compression/JpegDecompression.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/compression/JpegCompressionSpec.scala
This PR fixes an issue with resource handling in JPEG compressed GeoTiffs.
Reading JPEGs with ImageIO is [known to cause issues](https://info.michael-simons.eu/2012/01/25/the-dangers-of-javas-imageio/). The way the JPEG decompression works does not close down resources sufficiently and can cause an error like this
```
Cause: java.nio.file.FileSystemException: /var/folders/sv/zr8j0t4j1f726nhlt3vb8c300000gn/T/imageio8791917777763522780.tmp: Too many open files in system
```
The first commit in this PR adds a unit test downloads a JPEG-compressed GeoTiff from OpenAerialMap. It then performs many parallel reads in a loop, causing a "too many files opened" exception with the current code.
The second commit modifies the `JpegDecompression` to always create and close the `ImageReader` resources …
> Fix issue with resource management in Jpeg compressed GeoTiffs

- CHANGELOG.md
- project/Settings.scala
- spark/src/main/resources/META-INF/services/geotrellis.util.RangeReaderProvider
- store/src/main/resources/META-INF/services/geotrellis.util.RangeReaderProvider
- store/src/main/scala/geotrellis/store/http/util/HttpRangeReader.scala
- store/src/main/scala/geotrellis/store/http/util/HttpRangeReaderProvider.scala
- store/src/test/scala/geotrellis/store/http/util/HttpRangeReaderProviderSpec.scala
- store/src/test/scala/geotrellis/store/http/util/HttpRangeReaderSpec.scala
This PR moves HttpRangeReader into the store pacakge.
Closes https://github.com/locationtech/geotrellis/issues/3254
> Move HttpRangeReader out of the spark package

- CHANGELOG.md
- docs/guide/module-hierarchy.rst
- project/Settings.scala
- store/src/main/resources/META-INF/services/geotrellis.util.RangeReaderProvider
- util/src/main/resources/META-INF/services/geotrellis.util.RangeReaderProvider
- util/src/main/scala/geotrellis/util/HttpRangeReader.scala
- util/src/main/scala/geotrellis/util/HttpRangeReaderProvider.scala
- util/src/test/scala/geotrellis/util/HttpRangeReaderProviderSpec.scala
- util/src/test/scala/geotrellis/util/HttpRangeReaderSpec.scala
A post-standup discussion made the decision
to move this class to geotrellis.util because:
- It's a generic enough util to be part of the
base set of RangeReaders
- Allows users of geotrellis.raster.RasterSource
to read remote public rasters without
geotrellis.store
- Moves scalaj dep as far up the tree as possible
making it easier to remove in the future for
a more widely used lib
Closes #3256
> Move HttpRangeReader to geotrellis.util

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/GridExtent.scala
- raster/src/test/scala/geotrellis/raster/GridExtentSpec.scala
~~Still waiting on an edge case test that allows us to consistently reproduce this issue~~, but as part of some other bugfixing/testing I updated GridExtent to use the tolerance methods consistently everywhere. This appears to have resolved the issue in the withResolution calls that caused mismatched grid extents.
They are _not_ used in `GridExtent.alignTargetPixels` because that method provides
a GDAL specific operation copied from GDAL source.
The tolerance in GridExtent is 1e-7, in QGIS its 1e-6 and GDAL its 1e-5. Should we update our value to match one of the other projects? This could have the consequence of subtly breaking projects that rely on the current behavior for correctness. 
Take a look at the first commit's CI build: …
> Use [ceil|floor]WithTolerance methods in GridExtent

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/geotiff/GeoTiffReprojectRasterSource.scala
- raster/src/main/scala/geotrellis/raster/geotiff/GeoTiffResampleRasterSource.scala
Lock should happen on a tiff object in GeoTiffRasterSources
GeoTreslli server STAC catalog reads only
I could not implement a unit test that would reproduce that bad behavior.
Closes https://github.com/azavea/geotrellis/issues/272
> GeoTiffRasterSource is not threadsafe enough

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/release.md
For:
- Bug Reports
- Feature Requests
- New Releases
Mostly this was a way to document our release process and capture
it in issues, similar to other Azavea OSS projects, until we are able to
address https://github.com/locationtech/geotrellis/issues/3140
Bonus that we can begin iterating on a few other common issue
template types.
@pomadchin pay particular attention to the steps in the new release.md issue template. Please double-check that I didn't miss any of the key release steps.
> Add GitHub Issue Templates

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/ShortArrayTile.scala
- raster/src/main/scala/geotrellis/raster/mapalgebra/focal/FocalCalculation.scala
This PR fixes an incorrect result array tile that is used i.e. in the FocalHillshade operation. 
Before (nodata around the scene is (0, 0, 0)):
After (nodata around the scene is valid):
> Fix ShortArrayTileResult result ArrayTile fulfillment

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/io/geotiff/NewSubfileType.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/GeoTiffInfo.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/GeoKeyDirectory.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/reader/SinglebandGeoTiffReaderSpec.scala
With this PR GeoTiff reader will skip all IFDs that are not a `ReducedImage`.
Closes https://github.com/locationtech/geotrellis/issues/3269
> Fix Overviews Read Incorrectly when Per Dataset Masks Present bug

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/io/geotiff/writer/CoordinateSystemParser.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala
This PR fixes GeoTiff.write logic when the CRS is web mercator but it had no the EPSG code data.
Closes https://github.com/locationtech/geotrellis/issues/3281
> Fix WebMercator projection TIFF CoordinateSystemParser logic

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/CompositeTile.scala
- raster/src/main/scala/geotrellis/raster/CroppedTile.scala
- raster/src/main/scala/geotrellis/raster/PaddedTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffTile.scala
- raster/src/test/scala/geotrellis/raster/ArrayTileSpec.scala
- raster/src/test/scala/geotrellis/raster/CompositeTileSpec.scala
- raster/src/test/scala/geotrellis/raster/ConstantTileSpec.scala
- raster/src/test/scala/geotrellis/raster/CroppedTileSpec.scala
- raster/src/test/scala/geotrellis/raster/PaddedTileSpec.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/reader/GeoTiffTileSpec.scala
This PR fixes an inconsistent API behavior and forces all combine function to behave like [ArrayTile.combine](https://github.com/locationtech/geotrellis/blob/v3.4.1/raster/src/main/scala/geotrellis/raster/ArrayTile.scala#L201)
Closes #3170
> Tile combine should union cellTypes

- CHANGELOG.md
- proj4/src/main/scala/geotrellis/proj4/CRS.scala
- proj4/src/main/scala/geotrellis/proj4/io/wkt/WKT.scala
- proj4/src/main/scala/geotrellis/proj4/io/wkt/WKTParser.scala
- proj4/src/test/scala/geotrellis/proj4/CRSTest.scala
This PR fixes the `CRS.fromWKT` function behavior. It could throw, however, acording to its signature, it should handle the incorrect input.
Closes https://github.com/locationtech/geotrellis/issues/3209
> Add a safe WKTParser.parse function

- CHANGELOG.md
- vector/src/main/scala/geotrellis/vector/io/json/GeometryFormats.scala
- vector/src/test/scala/spec/geotrellis/vector/io/json/GeometryFormatsSpec.scala
Encoding a GeometryCollection with a Multipolygon/MultiPoint/MultiLineString should serialize those geometries once
Current behavior encodes them in geometries as both `type: MultiX` and `type: GeometryCollection`
Closes #3167
> Fix Encoder[GeometryCollection]

- CHANGELOG.md
- vector/src/main/scala/geotrellis/vector/methods/GeometryCollectionMethods.scala
- vector/src/test/scala/spec/geotrellis/vector/GeometryCollectionSpec.scala
As noted in #3289, we have some problems dealing with `GeometryCollection`s.  This bug was traced to the implementation of `getAll` which used reflection to extract the contained geometries that matched a desired type.  This was intended to be used to extract specific types or subclasses (`gc.getAll[Geometry]` would be useful).  The problem was with `gc.getAll(GeometryCollection)`, since `MultiPoint`, `MultiLineString`, and `MultiPolygon` are subclasses of `GeometryCollection`.  Therefore, `gc.getAll[GeometryCollection]` would return all `Multi*` and `GeometryCollection` entities.  This caused problems for methods like `reproject`, which would duplicate `Multi*` elements.
This PR, in it's first form, is for discussion purposes.  The simple solution presented here is that `getAll` loses …
> Fix GeometryCollection::getAll extension method

- CHANGELOG.md
- project/Dependencies.scala
Updates gdal-warp-bindings to the newly released 1.1.1 to address MacOS dylib issues.
> Update gdal-warp-bindings v1.1.1

- CHANGELOG.md
- build.sbt
- project/Settings.scala
We need to review dependecnies usage in the project modules. A great example of an unused dependency is SCaffeine which is definitely not used in `geotrellis-proj4`.
> Remove explicit unused Scaffeine dependency from projects

- build.sbt
Fixes an erroneous commit in #3317 that wasn't caught by the PR build because the issue was in the scaladoc `unidoc` build.
Here's a local run of `./sbt unidoc` moving past the error in the [CI build](https://app.circleci.com/pipelines/github/locationtech/geotrellis/150/workflows/d0a3c510-45a3-4218-837a-0c22c183e413/jobs/1601) where it couldn't find the `unidoc` task:
Run `./sbt unidoc` on `master` -- it should fail with the error in CI. Switch to this branch and run `./sbt unidoc`. It should succeed.
> Fix sbt unidoc build

- build.sbt
- project/Settings.scala
- sbt
This PR fixes the project unidoc generation. It is interesting that the message generated by SBT is so confusing though.
It is a follow up to #3320. It looks like during the #3320 test no one could wait until the successful exit.
`./sbt unidoc` -- it should not fail locally or in CI. It is not a fast command to test.
> Exclude mdoc project from the unidoc generation

- .gitignore
- build.sbt
- project/Dependencies.scala
- project/Settings.scala
- project/build.properties
- s3/src/main/scala/geotrellis/store/s3/S3LayerCopier.scala
This PR performs the review and cleanup of the entire build.sbt. It also ddresses `jai_core` resolution ordering by defining a strict dependencies resolution ordering.
P.S. These deps added into the build are not new, but just explicit for visibility.
Closes #3322
Closes #3315
The local couriser folder is located under `~/Library/Caches/Coursier/v1` on MacOS and under `~/.cache/coursier/v1` on linux, [see docs](https://get-coursier.io/docs/cache.html#default-location).
> Review and cleanup build.sbt

- CHANGELOG.md
- README.md
- s3/src/main/scala/geotrellis/store/s3/util/S3RangeReader.scala
This PR addresses the issue that happens on newer JVMs (it happened to me after upgrading up to `AdoptOpenJDK 1.8.0_275` from `1.8.0_265`). I'm surprised that this issue is JVM specific. This PR finishes https://github.com/locationtech/geotrellis/pull/3079 and adds explanations of the `abort()` function behavior.
This PR also converts https://github.com/locationtech/geotrellis/issues/3239 into a less pressing issue.
```scala
import geotrellis.raster.geotiff._
val rs = GeoTiffRasterSource(
"s3://geotrellis-test/daunnc/tiledb-benchmark/lc8-utm-1.tif"
)
rs.read() // should not fail
```
Without this PR the code snippet above fails with the following error:
```scala
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 168,110; received: …
```
> Remove an excessive close after the abort call in S3RangeReader

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/sigmoidal/SigmoidalContrast.scala
A backport of #3327 with an updated CHANGELOG and added comment strings
Closes #3326
> Fix sigmoidal contrast calculation

- CHANGELOG.md
- gdal/src/main/scala/geotrellis/raster/gdal/GDALDataset.scala
This PR cleanups GDALDataset and adds initial GDAL Transform rotation support
Related to https://github.com/locationtech/geotrellis/issues/3332
> Add initial GDAL Transform rotation support

- CHANGELOG.md
- s3/src/main/scala/geotrellis/store/s3/S3RasterMethods.scala
- s3/src/main/scala/geotrellis/store/s3/package.scala
This PR adds a specific to s3 overload that doesn't require having a hadoop dependency in the classpath.
```scala
val tiff: MultibandGeoTiff = ???
tiff.write(new AmazonS3URI("s3://test/destination.tiff"))
```
> Add rasters S3 write methods

- bench/src/main/scala/geotrellis/bench/GeotrellisFlightRecordingProfiler.scala
- bench/src/main/scala/geotrellis/raster/GenericRasterBench.scala
- bench/src/main/scala/geotrellis/raster/resample/ResampleBench.scala
- bench/src/main/scala/geotrellis/spark/store/index/MergeQueueBench.scala
- docs/architecture/004-spark-streaming.rst
- proj4/src/main/scala/geotrellis/proj4/CRS.scala
- proj4/src/test/scala/geotrellis/proj4/CRSTest.scala
- proj4/src/test/scala/geotrellis/proj4/MetaCRSTest.scala
- project/GTBenchmarkPlugin.scala
- raster-testkit/src/main/scala/geotrellis/raster/testkit/TileBuilders.scala
- raster/src/main/scala/geotrellis/raster/CellTypeEncoding.scala
- raster/src/main/scala/geotrellis/raster/DelegatingTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/writer/CoordinateSystemParser.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/writer/TiffTagFieldValue.scala
- raster/src/main/scala/geotrellis/raster/render/ColorMap.scala
- raster/src/main/scala/geotrellis/raster/render/ColorRamps.scala
- raster/src/main/scala/geotrellis/raster/split/TileFeatureSplitMethods.scala
- raster/src/main/scala/geotrellis/raster/stitch/Stitcher.scala
- raster/src/test/scala/geotrellis/raster/ArrayTileSpec.scala
- raster/src/test/scala/geotrellis/raster/CellTypeSpec.scala
- raster/src/test/scala/geotrellis/raster/histogram/HistogramSpec.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala
- raster/src/test/scala/geotrellis/raster/render/ascii/RenderAsciiTests.scala
- store/src/main/scala/geotrellis/store/avro/codecs/package.scala
- vector/src/main/scala/geotrellis/vector/triangulation/DelaunayStitcher.scala
replace all unicode arrow operators with equivalent ascii (deprecated in 2.13)
Unicode arrow operators are deprecated in 2.13, so replacing them with ascii is one small step towards 2.13 support, as there will be fewer warnings.
> replace all unicode arrow operators with equivalent ascii (deprecated in 2.13)

- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffSegmentLayout.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/LazySegmentBytes.scala
- s3-spark/src/main/scala/geotrellis/spark/store/s3/S3GeoTiffRDD.scala
- scalastyle-config.xml
- spark/src/main/scala/geotrellis/spark/RasterSourceRDD.scala
- spark/src/main/scala/geotrellis/spark/store/hadoop/HadoopGeoTiffRDD.scala
- spark/src/main/scala/geotrellis/spark/store/hadoop/HadoopRDDWriter.scala
- spark/src/test/scala/geotrellis/spark/filter/TileLayerRDDFilterMethodsSpec.scala
- store/src/main/scala/geotrellis/store/index/IndexRanges.scala
- util/src/main/scala/geotrellis/util/StreamingByteReader.scala
1. change all long literals to use uppercase `L` instead of lowercase `l` . This was outputting a warning during compilation (at least in 2.13)
2. change scalastyle config to make this an error instead of a warning
> change all long literals to use uppercase L instead of lowercase l

- proj4/src/main/scala/geotrellis/proj4/CRS.scala
- raster/src/main/scala/geotrellis/raster/CompositeTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/GeoTiffCSParser.scala
- util/src/main/scala/geotrellis/util/ByteReader.scala
- util/src/main/scala/geotrellis/util/StreamingByteReader.scala
- vectortile/src/main/scala/geotrellis/vectortile/Layer.scala
1. fix regex literal missing `.` before r
2. replace use of type Unit with instance `()`
3. replace use of replaceAllLiterally with replace
4. fix several ambiguous nullary arg references that no longer compile in 2.13
none
none
> minor fixes for compilation errors under 2.13 (backwards-compatible with 2.11 and 2.12)

- CHANGELOG.md
- vector/src/main/scala/geotrellis/vector/SpatialIndex.scala
In `SpatialIndex`, the method `traversePointsInExtent` returns a Traversable. Traversable is being phased out in favor of Iterable. This method is only used within GT in the `pointsInExtent` method and has no direct unit tests, so it probably should have been a protected/private method. 
This change does the following:
1. Adds `pointsInExtentAsIterable` (named so as not to conflict with `pointsInExtent(...): Vector`) that returns an Iterable and uses this method in `pointsInExtent`
2. deprecates `traversePointsInExtent` in favor of `pointsInExtentAsIterable` (named so as not to conflict with `pointsInExtent(...): Vector`)
3. implements method `iterator` in Traversable as required by 2.13. This is backwards-compatible with 2.11 and 2.12. …
> SpatialIndex use of Traversable

- proj4/src/test/scala/geotrellis/proj4/GenerateTestCases.scala
- raster/src/main/scala/geotrellis/raster/CompositeTile.scala
- raster/src/main/scala/geotrellis/raster/histogram/StreamingHistogram.scala
- spark/src/main/scala/geotrellis/spark/costdistance/IterativeCostDistance.scala
- spark/src/main/scala/geotrellis/spark/util/GroupIterator.scala
- spark/src/main/scala/geotrellis/spark/viewshed/IterativeViewshed.scala
- store/src/main/scala/geotrellis/store/hadoop/util/HdfsUtils.scala
1. In 2.13, it is a compile error if a parent class method has a set of empty parens on it and an overriding method in a child class does **not** also have empty parens.  In 2.11 & 2.12, these are equivalent, so there's no change in behavior.
2. In 2.13, the `.r` syntax no longer works on StringBuilder, so an intermediate toString is required
3. Fix use of getLines without parens that gives an error or warning in 2.13
4. replace several more uses of `Unit` type as a value with `()`
none
none
> fix several issue of non-paren'ed method overrides paren'ed method

- proj4/src/test/scala/geotrellis/proj4/GenerateTestCases.scala
- proj4/src/test/scala/geotrellis/proj4/MetaCRSTestFileReader.scala
- vector/src/main/scala/geotrellis/vector/SpatialIndex.scala
There are two uses of `to[T]` methods in the proj4 module -- a `to[List]` and a ``to[Vector]`. These methods won't compile in 2.13, as to[Collection] method was replaced by the to(Collection) method, which is in the scala-collection-compat library. However, replacing these with `toList` and `toVector` is the simpler option, so doing that instead. 
none
none
> replace two uses of to[T] with equivalent toT

- CHANGELOG.md
- gdal/src/main/scala/geotrellis/raster/gdal/GDALDataset.scala
- gdal/src/test/scala/geotrellis/raster/gdal/GDALRasterSourceSpec.scala
This PR addresses #3300 and allows reads of BitCellType TIFFs.
Closes #3300
> Fix GDALRasterSources BitCellType reads

- CHANGELOG.md
- project/build.properties
- sbt
- vector/src/main/scala/geotrellis/vector/GeomFactory.scala
This PR fixes the JTS config loading ordering. That could cause bad JTS factories init, since sometimes the `reference.conf` file could be loaded into memory _after_ the call to the config. That could cause following errors:
```scala
Caused by: pureconfig.error.ConfigReaderException: Cannot convert configuration to a geotrellis.vector.conf.JtsConfig. Failures are:
at the root:
- (merge of system properties,reference.conf @ jar:file:/.../sbt/1.4.9/ssl-config-core_2.12-0.4.0.jar!/reference.conf: 1) Key not found: 'geotrellis'.
``` 
For the context: this could only happen in runs through SBT. 
I did a little bit of tracing down the history of this bug and it turned out that it appeared in `1.4.0` and all `1.4.x` versions are affected. However, in `1.5.x` (checked with `RC2`) this issue is …
> Make JTSConfig load lazy

- s3/src/main/scala/geotrellis/store/s3/S3LayerDeleter.scala
Very straightforward fix to deal with the delete request limit of the AWS SDK.
Simply chunks the `objectIdentifiers` list into lists of length smaller than the `requestLimit` and iteratively makes the delete call to the AWS SDK. 
TODO
Unsure of the testing strategies favored for S3 and if the changes should be included in the changelog.
Closes #3371
> Update S3LayerDeleter to consider AWS SDK request limit

- raster/src/main/scala/geotrellis/raster/Implicits.scala
- raster/src/main/scala/geotrellis/raster/render/ColorMap.scala
- raster/src/main/scala/geotrellis/raster/render/JpgRenderMethods.scala
- spark/src/main/scala/geotrellis/spark/Implicits.scala
- spark/src/main/scala/geotrellis/spark/mapalgebra/local/temporal/package.scala
- spark/src/main/scala/geotrellis/spark/package.scala
First off, this doesn't actually have anything to do with implicits -- it just happens to be a problem with spark and raster Implicits class and how it references all the other classes it extends.
The core of this is that prior to 2.13, the resolution between local identifiers (in this case, a relative reference to a class) and imported identifiers did not conform to the spec. The references to several classes resolved to the local package rather than an imported package. This was fixed in 2.13, so these two files no longer compile because the class identifiers resolve differently now.
For example, `interpolation.Implicits` resolved to the local `geotrellis.raster.interpolation.Implicits` rather than what it should have resolved to according to the spec, which is that the existence of …
> resolve amgiguity in spark and raster Implicits classes with explicit imports shadowing local identifiers

- layer/src/main/scala/geotrellis/layer/buffer/BufferTiles.scala
- proj4/src/main/scala/geotrellis/proj4/io/wkt/WKT.scala
- raster/src/main/scala/geotrellis/raster/GridBounds.scala
- raster/src/main/scala/geotrellis/raster/rasterize/polygon/FractionalRasterizer.scala
- raster/src/main/scala/geotrellis/raster/rasterize/polygon/PolygonRasterizer.scala
- spark/src/main/scala/geotrellis/spark/package.scala
- store/src/main/scala/geotrellis/store/AttributeStore.scala
- store/src/main/scala/geotrellis/store/hadoop/formats/FilterMapFileInputFormat.scala
- vector/src/main/scala/geotrellis/vector/triangulation/DelaunayTriangulation.scala
- vector/src/main/scala/geotrellis/vector/voronoi/VoronoiDiagram.scala
- vectortile/src/main/scala/geotrellis/vectortile/internal/Command.scala
- vectortile/src/main/scala/geotrellis/vectortile/internal/package.scala
These are the changes required to have the mutable/immutable Seq change in 2.13 work with cross-compilation.
**TODO** -- the changelog needs to be updated, since a couple of these involve public method signatures
Closes #XXX
> fixes for non-fqn Seq being immutable in Scala 2.13

- raster/src/main/scala/geotrellis/raster/GridExtent.scala
mapToGrid forced conversion to `Int`, which could be not enough for `GridExtent[Long]`
> Fix mapToGrid for Long

- raster-testkit/src/main/scala/geotrellis/raster/testkit/RasterMatchers.scala
This PR makes GT codebase JDK 11 friendly. In fact this issue was addressed mosltly via https://github.com/locationtech/geotrellis/pull/3294
Connects https://github.com/locationtech/geotrellis/issues/3301
> Fix JDK deprecation to support JDK11 compilation

- .circleci/config.yml
- build.sbt
- project/Settings.scala
- project/build.properties
- sbt
- store/src/main/scala/geotrellis/store/cog/COGValueReader.scala
- vector/src/main/scala/geotrellis/vector/SpatialIndex.scala
This PR bumps the Scala version up as well as the SBT version.
> Update Scala up to 2.13.6 and SBT 1.5.2

- project/Dependencies.scala
Originally the Spark dep was upgraded to follow EMR versions. This month EMR 6.3.0 has been released with the Spark 3.1.1 support, so we're safe to upgrade the dep.
> Upgrade up to Spark 3.1.1

- CHANGELOG.md
- project/Settings.scala
Spark depends on the [old cats.kernel](https://github.com/apache/spark/blob/d5868ebc398c7b69dbaaaa3218bc9b177252a3c8/dev/deps/spark-deps-hadoop-3.2-hive-2.3#L28) which requires us to shade it to avoid [binary incompatability runtime issues](https://github.com/typelevel/cats/issues/3628).
> Add new shading rules to make GT work with Spark 3.x

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/BufferTile.scala
- raster/src/main/scala/geotrellis/raster/mapalgebra/focal/BufferTileFocalMethods.scala
- raster/src/main/scala/geotrellis/raster/mapalgebra/focal/Implicits.scala
- raster/src/test/scala/geotrellis/raster/BufferTileSpec.scala
This PR adds BufferTile type to handle focal ops in RF.
> Add Buffer Tile

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/mapalgebra/focal/Implicits.scala
This PR fixes a possible ambiguity of the to implicit classes
> Disambiguate withBufferTileFocalMethods implicit

- raster/src/main/scala/geotrellis/raster/BufferTile.scala
- raster/src/main/scala/geotrellis/raster/mapalgebra/focal/Implicits.scala
This PR reverts #3421 to preserve bin compatibility.
> Disambiguate withBufferTileFocalMethods implicit preserving bin compatibility

- raster/src/main/scala/geotrellis/raster/GridExtent.scala
We decided to remove it too fast. It is required to unbox values passed into the constructor.
> Return GridExtent specialized constructor

- CHANGELOG.md
- project/Dependencies.scala
- spark-pipeline/src/main/scala/geotrellis/spark/pipeline/json/Implicits.scala
- spark-pipeline/src/main/scala/geotrellis/spark/pipeline/package.scala
- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
- spark/src/main/scala/geotrellis/spark/summary/polygonal/RDDPolygonalSummary.scala
- spark/src/test/scala/geotrellis/spark/mask/TileRDDMaskMethodsSpec.scala
- store/src/main/scala/geotrellis/store/hadoop/util/HdfsUtils.scala
- store/src/main/scala/geotrellis/store/index/hilbert/HilbertSpaceTimeKeyIndex.scala
- store/src/main/scala/geotrellis/store/index/hilbert/HilbertSpatialKeyIndex.scala
- vector/src/main/scala/geotrellis/vector/Results.scala
- vector/src/test/scala/geotrellis/vector/MultiPointSpec.scala
- version.sbt
Version bumps to fantastic OverlayNG
Errors in:
CQs:
Closes #3436
> JTS 1.18, GeoTools 25.0

- CHANGELOG.md
- bench/src/main/scala/geotrellis/raster/GridBoxingBench.scala
- raster/src/main/scala/geotrellis/raster/ArrayTile.scala
- raster/src/main/scala/geotrellis/raster/ConstantTile.scala
- raster/src/main/scala/geotrellis/raster/MutableArrayTile.scala
- raster/src/main/scala/geotrellis/raster/Tile.scala
Since GT 3.x we had a regression where all calls to cols / rows were boxed. This lead to regressions in `MutableArrayTile.{set / update / etc}` functions. For more details see #3427, #3428, #3429 and #3432
This PR clarifies Grid inheritors cols / rows function types to help with the specialized calls dispatch. 
Can be reproduced via:
```bash
$ sbt project bench; benchOnly geotrellis/raster/GridBoxingBench.scala
```
Closes #3427
Closes #3432
> ArrayTile.{cols | rows} calls boxing fix

- CHANGELOG.md
- spark/src/main/scala/geotrellis/spark/RasterSourceRDD.scala
This PR makes the tiling behavior more configurable.
Closes https://github.com/locationtech/geotrellis/issues/3449
> RasterSourceRDD.tiledLayerRDD should have a configurable partition transform function

- build.sbt
- gdal-spark/src/test/scala/geotrellis/spark/gdal/GDALRasterSummarySpec.scala
- project/Dependencies.scala
- project/Settings.scala
- project/build.properties
- project/plugins.sbt
- sbt
We need to update critical deps version up to maintain cross libraries compatability.
Closes https://github.com/locationtech/geotrellis/issues/3451
Closes https://github.com/locationtech/geotrellis/pull/3453
> Bump dependencies up

- CHANGELOG.md
- vector/src/main/scala/geotrellis/vector/io/json/CrsFormats.scala
- vector/src/main/scala/geotrellis/vector/io/json/FeatureFormats.scala
- vector/src/main/scala/geotrellis/vector/io/json/Style.scala
Shapeless 2.3.7 in deps can cause runtime issues in case the codec is created, however, it is possible to work around it in case codecs are lazy.
> Lazy init circe codecs in the vector module

- project/Dependencies.scala
This PR bumps GT Spark version up to be aligned with frameless and rasterframes. We want to cut one patch release before https://github.com/locationtech/geotrellis/pull/3389
> Bump Spark version up to 3.2.0

- CHANGELOG.md
- spark/src/main/scala/geotrellis/spark/RasterSourceRDD.scala
- spark/src/test/scala/geotrellis/spark/RasterSourceRDDSpec.scala
This PR expand the tiledLayerRDD API and makes it possible to tileToLayout within the given AOI without loading rasters into memory outside of it.
Closes https://github.com/locationtech/geotrellis/issues/3473
> Add RasterSourceRDD.tiledLayerRDD within the geometry

- build.sbt
Temporary (?) exclude vectortile from the unidoc generation due to the following error:
```scala
value readStringRequireUtf8 is not a member of com.google.protobuf.CodedInputStream
```
May be linked to: https://github.com/scalapb/ScalaPB/issues/1350
> Exclude vectortile project from the unidoc generation

- CHANGELOG.md
- s3-spark/src/test/resources/reference.conf
- s3-spark/src/test/scala/geotrellis/spark/store/s3/MockS3Client.scala
- s3/src/main/resources/reference.conf
- s3/src/main/scala/geotrellis/store/s3/S3ClientProducer.scala
- s3/src/main/scala/geotrellis/store/s3/conf/S3Config.scala
- s3/src/main/scala/geotrellis/store/s3/package.scala
Closes https://github.com/locationtech/geotrellis/issues/3478
> Expose AWS_REQUEST_PAYER environment variable

- CHANGELOG.md
- vector/src/main/scala/geotrellis/vector/Extent.scala
- vector/src/test/scala/geotrellis/vector/ExtentSpec.scala
Fixes a small typo in Extent.translate
Closes #3444
> Fixed Extent.translate

- CHANGELOG.md
- cassandra/src/main/scala/geotrellis/store/cassandra/package.scala
- store/src/main/scala/geotrellis/store/util/package.scala
This PR fixes the liftCompletableFuture function implementation. It should accept Future as a by name parameter to ensure wrapping happens before the Future is executed.
> liftCompletableFuture function fix

- raster/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala
Add tests to demonstrate respect for `StorageMethod` on `GeoTiff` write options.
Couldn't reproduce bug; simply adding a test to ensure no regression from here
Closes #3335
> Test storage method for tiff writes

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/geotiff/GeoTiffReprojectRasterSource.scala
- raster/src/main/scala/geotrellis/raster/geotiff/GeoTiffResampleRasterSource.scala
- raster/src/test/scala/geotrellis/raster/geotiff/GeoTiffRasterSourceSpec.scala
Before, when calling .convert or .reproject on a resampled GeoTiffRasterSource, a new baseTiff was created from the source path. Now, we preserve the baseTiff (like all other methods already do), avoiding creating a new one (and losing settings in the process)
> Pass baseTiff to new RasterSource on GeoTiffResampleRasterSource.reproject/convert

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/ArrayTile.scala
- raster/src/main/scala/geotrellis/raster/mapalgebra/local/InverseMask.scala
- raster/src/main/scala/geotrellis/raster/mapalgebra/local/Mask.scala
- raster/src/test/scala/geotrellis/raster/mask/SinglebandTileMaskMethodsSpec.scala
`Mask` and `InverseMask` functions used `dualCombine` which used the union of cellTypes between tile and mask for result type. This mostly worked out fine but can produce bad results when either mask or tile had same byte width but different NODATA definitions. The correct behavior for mask operation is to always preserver the cell type of the input tile no matter how silly it or the mask cell type is. It's just better not to ask questions here.
Closes [#3488](https://github.com/locationtech/geotrellis/issues/3488)
> Fix: Mask preserves cell type of the masked tile

- util/src/main/scala/geotrellis/util/FileRangeReaderProvider.scala
Fix the problem that Paths.get cannot be recognized correctly after URI parsing in windows.
Use HadoopCOGLayerReader to read COGLayer and perform first operation on the result RDD.
Before repair:
After repair:
> Fix FileRangeReaderProvider parsing URI in windows

- CHANGELOG.md
- layer/src/main/scala/geotrellis/layer/LayoutTileSource.scala
- raster/src/main/scala/geotrellis/raster/GridExtent.scala
- raster/src/test/scala/geotrellis/raster/GridExtentSpec.scala
In liue of https://github.com/locationtech/geotrellis/pull/3520 to keep things rolling 
cc @jdries and thanks for your contirbution!
Once CI is green I'll merge it in.
Closes https://github.com/locationtech/geotrellis/pull/3520
> Fix rounding errors/numerical instability in GridExtent and LayoutTileSource 

- CHANGELOG.md
- store/src/main/scala/geotrellis/store/GeoTrellisPath.scala
- store/src/test/scala/geotrellis/store/GeoTrellisPathSpec.scala
This PR makes URI parsing more flexible to preserve unrecognized params in the path which is necessary for HBase and Accumulo. 
Closes https://github.com/locationtech/geotrellis/issues/3528
cc @RunBoo
> GeoTrellisPath.parse should preserve unrecognized uri parameters

- store/src/main/scala/geotrellis/store/cog/vrt/VRT.scala
Add `writer.flush()` when writing xml to vrt, fix the problem of writing empty vrt.xml when writing out cog.
> Fixed the issue that the generated vrt.xml is empty when writing out cog

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/reproject/RasterRegionReproject.scala
- raster/src/test/scala/geotrellis/raster/reproject/ReprojectSpec.scala
https://github.com/locationtech/geotrellis/issues/3541
Proposed fix for a very important bug in reprojecting to lower resolution.
I think it's better (more correct) than previous behaviour, but not sure yet if it is 100% accurate.
It seems to me that the downsampling now happens in the original projection system, and then it is warping to the new CRS. This will work fine if the low resolution pixel is rectangular in both projection systems.
Closes #XXX
> potential fix for resamplemethod in reproject

- raster/src/main/scala/geotrellis/raster/reproject/RasterRegionReproject.scala
- raster/src/main/scala/geotrellis/raster/resample/Resample.scala
- raster/src/test/scala/geotrellis/raster/reproject/ReprojectSpec.scala
This PR slightly cleans up the Resample code.
> Resample code cleanup

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/merge/MultibandTileMergeMethods.scala
- raster/src/main/scala/geotrellis/raster/merge/RasterMergeMethods.scala
- raster/src/main/scala/geotrellis/raster/merge/RasterTileFeatureMergeMethods.scala
- raster/src/main/scala/geotrellis/raster/merge/SinglebandTileMergeMethods.scala
- raster/src/main/scala/geotrellis/raster/merge/TileFeatureMergeMethods.scala
- raster/src/main/scala/geotrellis/raster/merge/TileMergeMethods.scala
- raster/src/test/scala/geotrellis/raster/merge/TileUnionMethodsSpec.scala
This PR adds a tile merging function, `union` which combines two input tiles so as to preserve all non-overlapping regions.
Union of two tiles; tile 1 with extent 0,0,1,1 and tile2 with extent 2,2,2.2,2.2. Output tile with extent of 0,0,2.2,2.2:
Union of overlapping tiles with a function applied to average overlapping cell values:
Closes #3365
> Add union to merge methods

- CHANGELOG.md
- project/build.properties
- raster/src/main/scala/geotrellis/raster/ConstantTile.scala
- raster/src/test/scala/geotrellis/raster/ConstantTileSpec.scala
This PR fixes ConstantCellType conversions of the Byte and Short CellTypes as well as adds the ConstantTile.empty constructor.
Fixes https://github.com/locationtech/geotrellis/issues/3525
Supersedes & closes https://github.com/locationtech/geotrellis/pull/3552
cc @jdries
> ConstantTile with NoData: support idempotent CellType conversions

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/TiffTags.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReaderSpec.scala
This PR fixes the GeoTiffReader implementing a proper unknown TiffTags skip logic.
Closes #3556
Fixes #3088
> GeoTiffReader Unknown tags skip fix

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/render/Implicits.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/compression/JpegCompressionSpec.scala
- store/src/main/scala/geotrellis/store/avro/AvroRecordCodec.scala
This PR renames and outdated implicitNotFound error and renames RGBA implicit class Methods to avoid issues when using in Scala 3
Linked https://github.com/locationtech/geotrellis/issues/3562
> Fix implicitNotFound error and rename RGBAMethods implicit class

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/io/geotiff/Tags.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala
https://github.com/locationtech/geotrellis/issues/3496
Certain tags in GDAL are standardized, but this requires a 'role' attribute to be set.
In this PR, I take the approach of simply having a static list of such 'well-known' tags that seem to be part of the GDAL standard.
Caveat: if gdal invents new roles, we need to update the list.
Closes #3496
> set gdal roles for well known tags

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/reproject/ReprojectRasterExtent.scala
- raster/src/test/scala/geotrellis/raster/reproject/ReprojectRasterExtentSpec.scala
Closes https://github.com/locationtech/geotrellis/pull/3561 
Closes https://github.com/locationtech/geotrellis/issues/3559
All credits to @jdries, this PR is to clean it up before merge and add the CHANGELOG.md
> ReprojectRasterExtent: support single pixel input

- CHANGELOG.md
- project/Dependencies.scala
- project/Settings.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/compression/Decompressor.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/compression/ZStdCompression.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/codes/CompressionType.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/compression/ZStdCompressionSpec.scala
Add ZStd compression support for GTiff
Closes #3579
> Add ZStd compression support for GTiff

- spark/src/main/scala/geotrellis/spark/join/FilteredCartesianRDD.scala
https://github.com/locationtech/geotrellis/issues/3585
Removes use of Spark private API. This avoids issues when sealing is enabled.
This PR simply imports code that was used from Spark, without trying to modify or optimize it further.
Closes #3585
> Do not depend on private Spark API, avoids sealing violation

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/io/geotiff/compression/Compression.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/compression/Compressor.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/compression/Decompressor.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/compression/FloatingPointPredictor.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/compression/HorizontalPredictor.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/compression/NoCompression.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/compression/Predictor.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/GeoTiffInfo.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/compression/PredictorSpec.scala
- This PR adds predictor 2&3 support for writing compressed GTiff files
cfr. https://github.com/locationtech/geotrellis/issues/3587
Closes #3587
> Add predictor 2 (integer) and predictor 3 (float) support for writing compressed GTiff files

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/IntArrayTile.scala
- raster/src/main/scala/geotrellis/raster/resample/MaxResample.scala
- raster/src/main/scala/geotrellis/raster/resample/MinResample.scala
- raster/src/test/scala/geotrellis/raster/resample/MaxResampleSpec.scala
- raster/src/test/scala/geotrellis/raster/resample/MinResampleSpec.scala
This PR addresses the incorrect MinResampling for the non floating point Tiles.
Closes #3589
> MinResample should ignore Int NODATA values
