locationtech/geotrellis

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReaderSpec.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReader.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/ImageDirectory.scala
Also added a test case for this.
> Added so the geotiff reader now can read geotiffs with no geokey directory

- project/Build.scala
- spark/src/main/scala/geotrellis/spark/ingest/Pyramid.scala
- spark/src/main/scala/geotrellis/spark/io/accumulo/TimeRasterAccumuloDriver.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/KryoRegistrator.scala
- spark/src/test/scala/geotrellis/spark/RasterRDDBuilders.scala
- spark/src/test/scala/geotrellis/spark/ingest/PyramidSpec.scala
Also, added a Kryo serializer for jodatime DateTime, which should fix our JodaTime woes.
> Fix to Pyramid to work with RasterRDD[SpaceTimeKey]

- buildall.sh
- index/README.md
- index/src/main/scala/geotrellis/index/zcurve/MergeQueue.scala
- index/src/main/scala/geotrellis/index/zcurve/Z2.scala
- index/src/main/scala/geotrellis/index/zcurve/Z2Range.scala
- index/src/main/scala/geotrellis/index/zcurve/Z3.scala
- index/src/main/scala/geotrellis/index/zcurve/Z3Range.scala
- index/src/main/scala/geotrellis/index/zcurve/package.scala
- index/src/test/scala/geotrellis/index/zcurve/Z2IteratorSpec.scala
- index/src/test/scala/geotrellis/index/zcurve/Z2Spec.scala
- index/src/test/scala/geotrellis/index/zcurve/Z3RangeSpec.scala
- index/src/test/scala/geotrellis/index/zcurve/Z3Spec.scala
- project/Build.scala
geotrellis-index subproject will contain different methods of indexing and querying multi-dimentional data.
Currently it contains z-order curve functions to encode/decode data, generate z-ranges for an arbitrary multi-dimentional query range and z-divide function that can be used to implement binary search algorithm on multi-diemntional tree described here: http://www.vision-tools.com/h-tropf/multidimensionalrangequery.pdf
> Z-Order space filling curve encoding/decoding/search

- raster-test/src/test/resources/application.conf
- testkit/src/main/scala/geotrellis/testkit/TestEngine.scala
Fixes intermittent test failures by creating unique engine and catalog for each test.
> Fix test failures due to shared fixture

- spark/src/main/scala/geotrellis/spark/io/hadoop/HdfsUtils.scala
- spark/src/test/scala/geotrellis/spark/io/hadoop/HdfsUtilsSpec.scala
> Add helpful error message for invalid directory

- .travis.yml
- README.md
- engine-test/src/test/scala/geotrellis/engine/error.scala
- engine/src/main/scala/geotrellis/engine/Literal.scala
- engine/src/main/scala/geotrellis/engine/Operation.scala
- engine/src/main/scala/geotrellis/engine/io/LoadFile.scala
- engine/src/main/scala/geotrellis/engine/io/LoadRaster.scala
- engine/src/main/scala/geotrellis/engine/io/LoadRasterDefinition.scala
- engine/src/main/scala/geotrellis/engine/io/LoadRasterExtentFromFile.scala
- engine/src/main/scala/geotrellis/engine/io/LoadRasterLayer.scala
- engine/src/main/scala/geotrellis/engine/io/LoadRasterLayerInfo.scala
- engine/src/main/scala/geotrellis/engine/io/LoadRasterUrl.scala
- engine/src/main/scala/geotrellis/engine/io/LoadTile.scala
- engine/src/main/scala/geotrellis/engine/logic/Collect.scala
- engine/src/main/scala/geotrellis/engine/logic/If.scala
- engine/src/main/scala/geotrellis/engine/logic/MapOp.scala
- engine/src/main/scala/geotrellis/engine/logic/WithResult.scala
- engine/src/main/scala/geotrellis/engine/package.scala
- macros/src/main/scala/geotrellis/macros.scala
- project/Build.scala
- project/Dependencies.scala
- project/Version.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/extensions/GdalNoDataParser.scala
- spark/src/main/scala/geotrellis/spark/io/s3/S3InputFormat.scala
- spark/src/main/scala/geotrellis/spark/io/s3/S3RecordReader.scala
- testkit/src/main/scala/geotrellis/testkit/TileBuilders.scala
Also added cross-compilation for Scala 2.10.
ref: https://github.com/geotrellis/geotrellis/issues/946
> Scala 2.11

- spark/src/main/scala/geotrellis/spark/op/stats/StatsRasterRDDMethods.scala
- spark/src/test/scala/geotrellis/spark/op/stats/StatsRasterRDDMethodsSpec.scala
> Add class breaks to stats raster rdd methods

- gdal/src/main/scala/geotrellis/gdal/RasterDataSet.scala
- gdal/src/test/scala/geotrellis/gdal/GdalReaderSpec.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/formats/GdalInputFormat.scala
> Read PROJ.4 string when reading NetCDF layers

- vector-test/src/test/scala/geotrellis/vector/spec/json/GeoJsonSpec.scala
- vector/src/main/scala/geotrellis/vector/json/package.scala
> Add implicit conversion from extent to geojson polygon

- raster/src/main/scala/geotrellis/raster/op/local/LocalTileComparatorOp.scala
- raster/src/main/scala/geotrellis/raster/op/local/Majority.scala
- raster/src/main/scala/geotrellis/raster/op/local/Max.scala
- raster/src/main/scala/geotrellis/raster/op/local/MaxN.scala
- raster/src/main/scala/geotrellis/raster/op/local/Min.scala
- raster/src/main/scala/geotrellis/raster/op/local/MinN.scala
- raster/src/main/scala/geotrellis/raster/op/local/Minority.scala
- raster/src/main/scala/geotrellis/raster/op/local/Multiply.scala
- raster/src/main/scala/geotrellis/raster/op/local/Or.scala
- raster/src/main/scala/geotrellis/raster/op/local/Pow.scala
- raster/src/main/scala/geotrellis/raster/op/local/Subtract.scala
- raster/src/main/scala/geotrellis/raster/op/local/Xor.scala
- spark/src/main/scala/geotrellis/spark/RasterRDD.scala
- spark/src/main/scala/geotrellis/spark/op/local/LocalRasterRDDSeqMethods.scala
- spark/src/main/scala/geotrellis/spark/package.scala
- spark/src/test/scala/geotrellis/spark/RDDMatchers.scala
- spark/src/test/scala/geotrellis/spark/io/hadoop/HadoopCatalogSpec.scala
> Add combinePairs for Traversable

- vector-benchmark/src/main/scala/geotrellis/vector/benchmark/GeneratorBenchmarks.scala
- vector-benchmark/src/main/scala/geotrellis/vector/benchmark/GeometrySequenceOps.scala
- vector-test/src/test/scala/geotrellis/vector/op/SeqMethodsSpec.scala
- vector/src/main/scala/geotrellis/vector/MultiLine.scala
- vector/src/main/scala/geotrellis/vector/MultiPoint.scala
- vector/src/main/scala/geotrellis/vector/MultiPolygon.scala
- vector/src/main/scala/geotrellis/vector/Results.scala
- vector/src/main/scala/geotrellis/vector/op/SeqMethods.scala
Adds implicit classes for Geometry sequences. Fixes #893.
> Added sequence unions for lines, points, polygons and multis

- vector/src/main/scala/geotrellis/vector/Geometry.scala
> Add geotrellis.vector.Geometry.isValid method

- vector-test/src/test/scala/geotrellis/vector/spec/json/GeoJsonSpec.scala
- vector/src/main/scala/geotrellis/vector/json/FeatureFormats.scala
- vector/src/main/scala/geotrellis/vector/json/JsonFeatureCollectionMap.scala
- vector/src/main/scala/geotrellis/vector/json/README.md
> Read/Write Indexed GeoJson  FeatureCollection

- spark/src/main/scala/geotrellis/spark/RasterRDD.scala
- spark/src/main/scala/geotrellis/spark/op/local/AddRasterRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/op/local/AndRasterRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/op/local/DivideRasterRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/op/local/EqualRasterRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/op/local/GreaterOrEqualRasterRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/op/local/GreaterRasterRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/op/local/LessOrEqualRasterRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/op/local/LessRasterRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/op/local/MaxRasterRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/op/local/MinRasterRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/op/local/MultiplyRasterRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/op/local/OrRasterRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/op/local/PowRasterRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/op/local/SubtractRasterRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/op/local/UnequalRasterRDDMethods.scala
- spark/src/main/scala/geotrellis/spark/op/local/XorRasterRDDMethods.scala
Uses new implementation in localAdd()
> WIP: Adds combineTiles() method for a single additional tile

- vector-test/src/test/scala/spec/geotrellis/vector/LineSpec.scala
- vector-test/src/test/scala/spec/geotrellis/vector/MultiLineSpec.scala
- vector-test/src/test/scala/spec/geotrellis/vector/MultiPointSpec.scala
- vector-test/src/test/scala/spec/geotrellis/vector/PolygonSpec.scala
- vector-test/src/test/scala/spec/geotrellis/vector/op/LineDissolveSpec.scala
- vector/src/main/scala/geotrellis/vector/GeometryCollection.scala
- vector/src/main/scala/geotrellis/vector/Line.scala
- vector/src/main/scala/geotrellis/vector/MultiLine.scala
- vector/src/main/scala/geotrellis/vector/MultiPoint.scala
- vector/src/main/scala/geotrellis/vector/MultiPolygon.scala
- vector/src/main/scala/geotrellis/vector/Polygon.scala
- vector/src/main/scala/geotrellis/vector/op/LineDissolve.scala
Fixed merge conflicts for #1015 and opened a new PR per @lossyrob's request. Fixes #890.
> Immutability test merge conflict fix

- vector-test/src/test/scala/spec/geotrellis/vector/affine/GeometryCollectionTransformationMethodsSpec.scala
- vector/src/main/scala/geotrellis/vector/Geometry.scala
- vector/src/main/scala/geotrellis/vector/GeometryCollection.scala
- vector/src/main/scala/geotrellis/vector/affine/AffineTransformation.scala
- vector/src/main/scala/geotrellis/vector/affine/GoemetryCollectionTransformationMethods.scala
- vector/src/main/scala/geotrellis/vector/affine/LineTransformationMethods.scala
- vector/src/main/scala/geotrellis/vector/affine/MultiLineTransformationMethods.scala
- vector/src/main/scala/geotrellis/vector/affine/MultiPointTransformationMethods.scala
- vector/src/main/scala/geotrellis/vector/affine/MultiPolygonTransformationMethods.scala
- vector/src/main/scala/geotrellis/vector/affine/PointTransformationMethods.scala
- vector/src/main/scala/geotrellis/vector/affine/PolygonTransformationMethods.scala
- vector/src/main/scala/geotrellis/vector/affine/package.scala
- vector/src/main/scala/geotrellis/vector/io/WKB/WKB.scala
- vector/src/main/scala/geotrellis/vector/io/WKT/WKT.scala
Updates to the geotrellis.vector.affine package.
> Added GeometryCollection transformations, changed api a bit.

- project/Build.scala
- project/Environment.scala
- project/Version.scala
- spark/src/test/scala/geotrellis/spark/OnlyIfGdalInstalled.scala
- spark/src/test/scala/geotrellis/spark/ingest/IngestSpec.scala
This commit adds a check before running tests that
require Java bindings for GDAL. Additionally, this
commit adds the ability to get the path for the
for the Java bindings from an environment variable
> Add check for gdal

- spark/src/main/scala/geotrellis/spark/ingest/CassandraIngestCommand.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/CassandraAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/CassandraInstance.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/CassandraLayerMetaDataCatalog.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/CassandraRasterCatalog.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/RasterRDDReaderProvider.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/RasterRDDWriterProvider.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/TileReaderProvider.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/spacetime/SpaceTimeRasterRDDReaderProvider.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/spacetime/SpaceTimeRasterRDDWriterProvider.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/spacetime/SpaceTimeTileReaderProvider.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/spatial/SpatialRasterRDDReaderProvider.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/spatial/SpatialRasterRDDWriterProvider.scala
- spark/src/main/scala/geotrellis/spark/io/cassandra/spatial/SpatialTileReaderProvider.scala
See CassandraIngestCommand for new API look.
> Modified Cassandra API.

- spark/src/test/scala/geotrellis/spark/io/hadoop/HadoopRasterCatalogSpec.scala
Something about HadoopCatalogSpec is breaking Travis out. Trying to trouble shoot that.
> Travis Troubleshooting

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiff.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriter.scala
Signed-off-by: lossyrob <rdemanuele@gmail.com>
> Added GeoTiff.toByteArray

- vector-test/src/test/scala/spec/geotrellis/vector/io/json/GeoJsonSpec.scala
- vector/src/main/scala/geotrellis/vector/io/json/JsonFeatureCollection.scala
- vector/src/main/scala/geotrellis/vector/io/json/JsonFeatureCollectionMap.scala
- vector/src/main/scala/geotrellis/vector/io/json/package.scala
#1142 
tested with points and polygons for val json = Seq(p1, p2).toGeoJson and json.parseGeoJson[GeometryCollection] and json.parseGeoJson[GeometryCollection].polygons
> #1142 changed to GeometryCollection, fix vector-test

- raster-test/src/test/scala/geotrellis/raster/op/focal/MaxSpec.scala
- vector-test/src/test/scala/spec/geotrellis/vector/ExtentSpec.scala
- vector-test/src/test/scala/spec/geotrellis/vector/io/json/GeoJsonSpec.scala
- vector/src/main/scala/geotrellis/vector/Geometry.scala
- vector/src/main/scala/geotrellis/vector/GeometryCollection.scala
- vector/src/main/scala/geotrellis/vector/Line.scala
- vector/src/main/scala/geotrellis/vector/MultiGeometry.scala
- vector/src/main/scala/geotrellis/vector/Polygon.scala
- vector/src/main/scala/geotrellis/vector/io/json/JsonFeatureCollection.scala
- vector/src/main/scala/geotrellis/vector/io/json/package.scala
> Put `.envelope` on Geometry #1148

- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopSparkContextMethods.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HdfsUtils.scala
Hadoop filesystem now matches on one or more specified extensions.
> Hadoop also handle ".tiff" extension

- raster/src/main/scala/geotrellis/raster/resample/BilinearResample.scala
I was seeing weird pixels on the edges of images that had NoData borders. This fixes them.
Some tests fail. @moradology since you most recently touched those tests can you take a look and let me know if those are the tests fault or that they should be passing?
> WIP Fixes to bilinear

- spark-etl/README.md
- spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/EtlConf.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/package.scala
- spark-etl/src/test/scala/geotrellis/spark/etl/EtlSpec.scala
Simplified the construction to avoid ambiguous overloading errors and updated the README to reflect new features and syntax.
> Updates to ETL subproject

- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopRasterCatalog.scala
I've just run into this compiler error (needing a `Path` instead of just taking a `String`) multiple times, this will save future headaches.
> Adding applys to HadoopRasterCatalog

- geotools/src/main/scala/geotrellis/geotools/ShapeFileReader.scala
- geotools/src/test/scala/geotrellis/raster/io/ShapeFileReaderSpec.scala
- vector/src/main/scala/geotrellis/vector/Feature.scala
Added generic unapply functions to `Feature` objects (vector project). Fixed geotools project test.
> Fixed geotools test.

- gdal/build.sbt
- gdal/src/test/scala/geotrellis/gdal/GdalReaderSpec.scala
it is now available on maven central
> GDAL 1.11.1

- INDEX.md
- README.md
This adds a simple index of extant docs and some pointers for people on the root README.md
> Add index.md at root of project

- README.md
Correction for documentation typo
> Repetition in frontpage readme

- README.md
Moved contact and readme index higher on the page and added notes about each Readme item in the index; other minor style edits
> Reorganized and edited main Readme

- spark/src/main/scala/geotrellis/spark/io/RDDFilter.scala
RDDFilter now returns a Seq[KeyBound] instead of an Option[KeyBound].
Tests for the `spark` project all passed locally except for `geotrellis.spark.op.local.spatial.LocalSpatialSpec`.
> Change Return Type of RDDFilter

- raster-test/src/test/scala/geotrellis/raster/op/stats/StatsMethodsSpec.scala
- raster-test/src/test/scala/geotrellis/raster/op/zonal/ZonalStatisticsSpec.scala
- raster/src/main/scala/geotrellis/raster/histogram/Histogram.scala
- raster/src/main/scala/geotrellis/raster/op/focal/Moran.scala
- raster/src/main/scala/geotrellis/raster/op/stats/Statistics.scala
- raster/src/main/scala/geotrellis/raster/op/stats/StatsMethods.scala
- raster/src/main/scala/geotrellis/raster/op/zonal/ZonalMethods.scala
1. Implement a zonalStatistics method
2. Remove no-op loop inside the statistics generating code
3. Add a data count on the Statistics object
> Add zonal stats and implement count for Statistics methods

- .travis.yml
- spark/src/main/scala/geotrellis/spark/io/accumulo/AccumuloLayerReader.scala
- spark/src/main/scala/geotrellis/spark/io/accumulo/AccumuloLayerWriter.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopLayerReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopLayerWriter.scala
- spark/src/main/scala/geotrellis/spark/io/s3/S3LayerReader.scala
- spark/src/main/scala/geotrellis/spark/io/s3/S3LayerWriter.scala
Resolves: https://github.com/geotrellis/geotrellis/issues/1193
> Add convenience constructors for layer io readers/writers

- raster-test/src/test/scala/geotrellis/raster/rasterize/polygon/PolygonRasterizerSpec.scala
- raster/src/main/scala/geotrellis/raster/rasterize/polygon/PolygonRasterizer.scala
Caveats:
* Work in progress:
* ~~The `includeExterior` functionality is not present~~
* ~~The implementation is not algorithmically efficient (in particular in the calculation of the active edges on each row)~~
* ~~The implementation may not be efficient from an engineering standpoint (it is written in a functional style, I don't know whether the Scala compiler is good enough to optimize-away some/all of the unnecessary consing that could take place).~~
* ~~The `rasterizer-tests` tests (except for the `includeExterior` test that I commented) all pass, but I have not done any other testing.~~
All tests are now passing for me locally.
> New Rasterizer

- raster/src/main/scala/geotrellis/raster/MethodExtensions.scala
- raster/src/main/scala/geotrellis/raster/crop/Implicits.scala
- spark/src/main/scala/geotrellis/spark/reproject/Implicits.scala
See https://issues.scala-lang.org/browse/SI-1127
> Add type params to extended implicits object wrappers that extent another class w/ type classes.

- spark/src/main/scala/geotrellis/spark/io/RDDFilter.scala
The SynchronizedSet data structure has been deperecated in Scala 2.11.  The [docs](http://www.scala-lang.org/api/current/index.html#scala.collection.mutable.SynchronizedSet) recommend using `java.util.concurrent.ConcurrentHashMap[A,Unit]` instead, so that is done here.
The `RDDQuerySpec` tests in the `spark` project continue to pass locally after this change.
Closes #1281
> Replace Deprecated Data Structure

- raster-test/src/test/scala/geotrellis/raster/resample/MaxResampleSpec.scala
- raster-test/src/test/scala/geotrellis/raster/resample/MinResampleSpec.scala
- raster/src/main/scala/geotrellis/raster/resample/MaxResample.scala
- raster/src/main/scala/geotrellis/raster/resample/MinResample.scala
- raster/src/main/scala/geotrellis/raster/resample/Resample.scala
This adds minimum and maximum resample methods geotrellis.raster.resample
> Add Minimum and Maximum resample methods

- spark/src/main/scala/geotrellis/spark/io/index/hilbert/HilbertSpatialKeyIndex.scala
- spark/src/test/scala/geotrellis/spark/io/index/hilbert/HilbertSpatialKeyIndexSpec.scala
This mirrors the changes in space-time hilbert index made in https://github.com/geotrellis/geotrellis/pull/1303
> Specify resolution as number of bits in spatial hilbert

- .travis/deploy.sh
- publish-local-crossversion.sh
- publish-local.sh
- publish-m2.sh
- publish-snapshot.sh
- spark/src/main/scala/geotrellis/spark/utils/SparkUtils.scala
Due to #1314 we got rid of a `testkit`, this pr fixes local and travis publishment.
> Publishment scripts fix

- raster/src/main/scala/geotrellis/raster/ArrayTile.scala
Added return types, to provide `Scala: 2.11.5 JDK: oraclejdk7` building.
* https://s3.amazonaws.com/archive.travis-ci.org/jobs/109893365/log.txt
* https://s3.amazonaws.com/archive.travis-ci.org/jobs/109624744/log.txt
> Travis compilation fix

- raster/src/main/scala/geotrellis/raster/DoubleArrayTile.scala
- raster/src/main/scala/geotrellis/raster/FloatArrayTile.scala
- raster/src/main/scala/geotrellis/raster/IntArrayTile.scala
- raster/src/main/scala/geotrellis/raster/ShortArrayTile.scala
`Scala: 2.11.5 JDK: oraclejdk7` fail fix again. This time launched several times `./publish-local-crossversion.sh` in an [oraclejdk7 docker container](https://hub.docker.com/r/daunnc/java-7-oracle/), think this time everything should publish correct.
> Travis compilation fix [2]

- vector/src/main/scala/geotrellis/vector/Point.scala
- vector/src/main/scala/geotrellis/vector/package.scala
- vector/src/main/scala/geotrellis/vector/prepared/PreparedGeometry.scala
- vector/src/main/scala/geotrellis/vector/prepared/PreparedGeometryMethods.scala
> Expose JTS CGAlgorithms methods in Geometry

- spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala
cutTiles does not mosaic overlapping parts, must use tileToLayout
> Fix: Etl.ignest

- raster-test/src/test/scala/geotrellis/raster/CroppedTileSpec.scala
- raster/src/main/scala/geotrellis/raster/ArrayTile.scala
- raster/src/main/scala/geotrellis/raster/CompositeTile.scala
- spark/build.sbt
- vector-test/src/test/scala/spec/geotrellis/vector/ExtentSpec.scala
- vector/src/main/scala/geotrellis/vector/Extent.scala
> [Fix] Small fixes

- .travis/deploy.sh
- accumulo/build.sbt
- docs/README.md
- project/Environment.scala
- s3/build.sbt
- spark/build.sbt
Finished off gdal remove of #1370 
/cc @moradology, didn't catch these in code review.
> Removed remaining gdal project references.

- docs/proj4/proj4-implementation.md
- proj4/src/main/java/org/osgeo/proj4j/BasicCoordinateTransform.java
- proj4/src/main/java/org/osgeo/proj4j/CoordinateReferenceSystem.java
- proj4/src/main/java/org/osgeo/proj4j/datum/Datum.java
- proj4/src/main/java/org/osgeo/proj4j/datum/Ellipsoid.java
- proj4/src/main/java/org/osgeo/proj4j/datum/Grid.java
- proj4/src/main/java/org/osgeo/proj4j/datum/PrimeMeridian.java
- proj4/src/main/java/org/osgeo/proj4j/proj/Projection.java
Add some references for better context in ``proj4`` module's docs and code comments.
> Add links and proj.4 references for proj.4

- raster-test/src/test/scala/geotrellis/raster/render/ColorMapSpec.scala
- raster-test/src/test/scala/geotrellis/raster/render/ColorRasterSpec.scala
- raster-test/src/test/scala/geotrellis/raster/render/ColorSpec.scala
- raster-test/src/test/scala/geotrellis/raster/render/jpg/EncoderSpec.scala
- raster-test/src/test/scala/geotrellis/raster/render/png/RenderPngTests.scala
- raster/src/main/scala/geotrellis/raster/render/ColorMap.scala
- raster/src/main/scala/geotrellis/raster/render/ColorRamp.scala
- raster/src/main/scala/geotrellis/raster/render/JpgRenderMethods.scala
- raster/src/main/scala/geotrellis/raster/render/jpg/Settings.scala
- raster/src/main/scala/geotrellis/raster/render/package.scala
- raster/src/main/scala/geotrellis/raster/render/png/PngColorEncoding.scala
This fixes a bug with index-encoded PNG writing, writes some tests around rendering PNGs, and adds some additional ways to create a color map from a color ramp.
> More color/render fixes

- docs/README.md
- docs/util/util-intro.md
- util/src/main/scala/geotrellis/util/Filesystem.scala
- util/src/main/scala/geotrellis/util/MethodExtensions.scala
> Documentation for geotrellis.util

- proj4/src/main/scala/geotrellis/proj4/ConusAlbers.scala
- proj4/src/main/scala/geotrellis/proj4/LatLng.scala
- proj4/src/main/scala/geotrellis/proj4/WebMercator.scala
This change adds the Conus Albers CRS to the roster of available ones.
> Add Conus Albers CRS

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloUtils.scala
A function called `addSplits` has been added to the `AccumuloUtils` object.  This function splits a given Accumulo table into a given number of tablets to improve ingest performance.
> Add addSplits Function into AccumuloUtils

- raster-test/src/test/scala/geotrellis/raster/rasterize/polygon/PolygonRasterizerSpec.scala
- raster/src/main/scala/geotrellis/raster/rasterize/polygon/PolygonRasterizer.scala
This fixes an error in the polygon rasterizer when pixels are treated as extents.
Fixes #1482
> Fix Rasterizer Bug

- raster/src/main/scala/geotrellis/raster/CellType.scala
> Added support for int32raw cell types in CellType.fromString

- project/Version.scala
Updating master branch version to 1.0.0
> Update version to 1.0.0

- raster/src/main/scala/geotrellis/raster/io/geotiff/BitGeoTiffTile.scala
> Backport: Optimize reading from compressed Bit geotiffs

- raster-test/src/test/scala/geotrellis/raster/histogram/FastMapHistogramSpec.scala
- raster/src/main/scala/geotrellis/raster/histogram/FastMapHistogram.scala
> Backport: Store FastMapHistogram counts as longs

- raster-test/src/test/scala/geotrellis/raster/CellTypeSpec.scala
- raster/src/main/scala/geotrellis/raster/CellType.scala
> Backport: Fixes to user defined float/double CellType parsing

- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
- spark/src/main/scala/geotrellis/spark/tiling/CutTiles.scala
> Backport: Pass resampling method argument to merge in CutTiles.

- build.sbt
> Backport: Handle Special Characters 

- raster/src/main/scala/geotrellis/raster/ArrayMultibandTile.scala
- spark/src/main/scala/geotrellis/spark/io/avro/codecs/TileCodecs.scala
- spark/src/test/scala/geotrellis/spark/io/avro/AvroTools.scala
- spark/src/test/scala/geotrellis/spark/io/avro/TileCodecsSpec.scala
> Backport: Fix nodata values in codecs

- spark-etl/src/main/scala/geotrellis/spark/etl/MultibandIngest.scala
> Backport: Update MultibandIngest.scala

- spark/src/main/scala/geotrellis/spark/io/index/ZCurveKeyIndexMethod.scala
- spark/src/main/scala/geotrellis/spark/io/index/zcurve/ZSpaceTimeKeyIndex.scala
> Backport: Fix month and year calculations

- raster-test/src/test/scala/geotrellis/raster/rasterize/polygon/PolygonRasterizerSpec.scala
- raster/src/main/scala/geotrellis/raster/rasterize/polygon/PolygonRasterizer.scala
> Backport: Fix Rasterizer Bug

- project/Dependencies.scala
- project/Version.scala
- spark-etl/build.sbt
- vector-test/build.sbt
- vector-test/src/test/scala/spec/geotrellis/vector/io/json/CrsSpec.scala
- vector-test/src/test/scala/spec/geotrellis/vector/io/json/FeatureFormatsSpec.scala
- vector-test/src/test/scala/spec/geotrellis/vector/io/json/GeometryFormatsSpec.scala
- vector/src/main/scala/geotrellis/vector/io/json/CRS.scala
#1485
NOTE: This is not a full backport; I left a commit out that removed the engine and related subprojects.
> Backport: Upgrade dependencies as part of our LocationTech CQ process

- raster-test/src/test/scala/geotrellis/raster/render/ColorRampSpec.scala
- raster/src/main/scala/geotrellis/raster/render/ColorRamp.scala
> Backport: Handle entire layers of `NODATA`

- raster/src/main/scala/geotrellis/raster/CellType.scala
> Backport: Added support for int32raw cell types in CellType.fromString

- raster-test/src/test/scala/geotrellis/raster/histogram/StreamingHistogramSpec.scala
- raster/src/main/scala/geotrellis/raster/summary/SummaryMethods.scala
> Backport: Add ability to specify number of streaming buckets

- raster-test/src/test/scala/geotrellis/raster/histogram/StreamingHistogramSpec.scala
- raster/src/main/scala/geotrellis/raster/histogram/StreamingHistogram.scala
> Backport: Add logic to ensure use of minval/avoid repetition of breaks

- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopSparkContextMethods.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/formats/TemporalGeoTiffInputFormat.scala
> Backport: SparkContext temporal GeoTiff format args

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloLayerUpdater.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3LayerUpdater.scala
- spark/src/main/scala/geotrellis/spark/TileLayerMetadata.scala
- spark/src/main/scala/geotrellis/spark/io/file/FileLayerUpdater.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopLayerUpdater.scala
- spark/src/test/scala/geotrellis/spark/io/LayerUpdateSpaceTimeTileFeatureSpec.scala
- spark/src/test/scala/geotrellis/spark/io/LayerUpdateSpaceTimeTileSpec.scala
* leftOuterJoin problem
* layer key bounds were not updating in metadata table
> LayerUpdater fix

- project/Version.scala
- scripts/buildall.sh
Also removed benchmark from buildall.sh.
> Update version 0.10.1

- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopLayerMover.scala
> Backport: Fix HadoopLayerMover

- spark-etl/build.sbt
- spark-etl/src/main/scala/geotrellis/spark/etl/EtlConf.scala
> [Backport] Fix Spark Etl

- spark/src/main/scala/geotrellis/spark/merge/RDDLayoutMerge.scala
- spark/src/main/scala/geotrellis/spark/merge/RddLayoutMergeMethods.scala
> [Backport] Moved RDDLayoutMergeMethods functionality to object.

- build.sbt
- doc-examples/src/main/scala/geotrellis/doc/examples/spark/SparkExamples.scala
- doc-examples/src/test/scala/geotrellis/doc/examples/spark/SparkExamplesTests.scala
- docs/spark/spark-examples.md
Also add an example for querying a region by a multipolygon, masking by that geometry, computing max NDVI over time and saving as GeoTiff.
> Added example for focal operation on multiband layer.

- geotools/build.sbt
- spark/src/test/scala/geotrellis/spark/io/avro/AvroTools.scala
- util/build.sbt
- util/src/main/scala/geotrellis/util/package.scala
- util/src/test/scala/geotrellis/util/ComponentSpec.scala
> Close out remaining issues for 0.10.2

- spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/EtlConf.scala
- spark/src/main/scala/geotrellis/spark/TileLayerMetadata.scala
> Backport: Add ETL option to specify upper zoom limit for raster layer ingestion

- vector-test/src/test/scala/spec/geotrellis/vector/PolygonSpec.scala
- vector-test/src/test/scala/spec/geotrellis/vector/SeqMethodsSpec.scala
- vector/src/main/scala/geotrellis/vector/MultiPolygon.scala
- vector/src/main/scala/geotrellis/vector/Polygon.scala
- vector/src/main/scala/geotrellis/vector/Results.scala
- vector/src/main/scala/geotrellis/vector/SeqMethods.scala
> Backport: Polygon sequence union can result in NoResult.

- shapefile/build.sbt
- spark/src/test/scala/geotrellis/spark/io/avro/AvroTools.scala
- util/build.sbt
- util/src/main/scala/geotrellis/util/package.scala
- util/src/test/scala/geotrellis/util/ComponentSpec.scala
> Backport: Close out remaining issues for 0.10.2

- raster/src/main/scala/geotrellis/raster/TileFeature.scala
- spark/src/main/scala/geotrellis/spark/io/avro/codecs/TileFeatureCodec.scala
* TileFeature should extend CellGrid
* Additional avro codec to work with MultibandTiles
> TileFeature additions

- docs/release-notes/release-notes-0.10.0.md
- docs/release-notes/release-notes-0.10.1.md
- docs/release-notes/release-notes-0.10.2.md
> Backport: Adding release notes to documentation.

- vector/src/main/scala/geotrellis/vector/voronoi/Voronoi.scala
> Addressed warning in compilation of Voronoi

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTileSpec.scala
- raster/src/main/scala/geotrellis/raster/ArrayMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/MultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTile.scala
This is a pull request for issue #1530 (Multiband foreach method that gives all band values).
> add multiband foreach to MultibandTile

- .travis.yml
- .travis/hbase-install.sh
- project/Version.scala
Update up to HBase 1.2.3, fix Travis CI tests.
> HBase upgrade

- doc-examples/src/main/scala/geotrellis/doc/examples/spark/ShardingKeyIndex.scala
- doc-examples/src/test/resources/application.conf
- doc-examples/src/test/scala/geotrellis/doc/examples/spark/ShardingKeyIndexSpec.scala
- docs/spark/custom-keyindex.md
This PR provides an example of how to implement a new `KeyIndex` from scratch.
> Example: ShardingKeyIndex[K]

- spark/src/main/scala/geotrellis/spark/summary/polygonal/Implicits.scala
- spark/src/main/scala/geotrellis/spark/summary/polygonal/PolygonalSummaryTileRDDMethods.scala
> Backport: [Polygonal Summary] Relax types to anything `Tile`d

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTileSpec.scala
- raster/src/main/scala/geotrellis/raster/ArrayMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/MultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTile.scala
> Backport: add multiband foreach to MultibandTile

- slick/src/test/scala/geotrellis/slick/PostgisSpec.scala
- slick/src/test/scala/geotrellis/slick/ProjectedSpec.scala
> PostGis Spec bug 

- slick/src/test/scala/geotrellis/slick/PostgisSpec.scala
Fix of possible table drop issue, related to https://github.com/geotrellis/geotrellis/issues/1635
> PostGISSpec drop table fix

- README.md
- docs/spark-etl/spark-etl-intro.md
- docs/spark-etl/spark-etl-run-examples.md
- raster/build.sbt
- raster/src/main/scala/geotrellis/raster/ArrayTile.scala
- raster/src/main/scala/geotrellis/raster/CompositeTile.scala
- raster/src/main/scala/geotrellis/raster/ConstantTile.scala
- raster/src/main/scala/geotrellis/raster/CroppedTile.scala
- raster/src/main/scala/geotrellis/raster/Tile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffTile.scala
- spark-etl/src/main/resources/input-schema.json
- spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/config/Input.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/config/json/ConfigFormats.scala
- spark/src/main/scala/geotrellis/spark/io/file/FileLayerDeleter.scala
* https://github.com/geotrellis/geotrellis/issues/1547
* https://github.com/geotrellis/geotrellis/issues/1642
* https://github.com/geotrellis/geotrellis/issues/1641
* https://github.com/geotrellis/geotrellis/issues/1276
* https://github.com/geotrellis/geotrellis/issues/1408
> ETL Improvements and other issues fixes

- scripts/slickTestDB.sh
- slick/src/main/scala/geotrellis/slick/PostGisProjectionSupport.scala
- slick/src/main/scala/geotrellis/slick/PostGisSupport.scala
This PR removes some code that was copied in from PostGIS, which presents some IP issues.
> Remove some copied in PostGIS code

- accumulo/build.sbt
- build.sbt
- cassandra/build.sbt
- geomesa/build.sbt
- geowave/build.sbt
- hbase/build.sbt
- hbase/src/test/scala/geotrellis/spark/HBaseTestEnvironment.scala
- s3/build.sbt
- spark-testkit/build.sbt
- spark/build.sbt
- vectortile/build.sbt
Fixes https://github.com/geotrellis/geotrellis/issues/1680
> HBase tests fix

- raster/src/main/scala/geotrellis/raster/NoData.scala
- spark/src/main/scala/geotrellis/spark/summary/polygonal/PolygonalSummaryTileLayerCollectionMethods.scala
- spark/src/main/scala/geotrellis/spark/summary/polygonal/PolygonalSummaryTileLayerRDDMethods.scala
> [Polygonal Summary] Guard on empty RDDs/Seqs

- README.md
Updated to include core members joined since 2015.
> Update Contributor list

- .travis/hbase-install.sh
> Fix HBase download url

- shapefile/src/main/scala/geotrellis/shapefile/ShapeFileReader.scala
> Disposed of DataStore in readSimpleFeatures

- raster-test/src/test/scala/geotrellis/raster/resample/CubicResampleSpec.scala
- raster/src/main/scala/geotrellis/raster/equalization/HistogramEqualization.scala
- raster/src/main/scala/geotrellis/raster/equalization/SinglebandEqualizationMethods.scala
- raster/src/main/scala/geotrellis/raster/resample/CubicResample.scala
- raster/src/main/scala/geotrellis/raster/resample/Resample.scala
This changeset causes bicubic interpolation (spline, convolutional, and lanczos) to be done on the entire input tile, rather than just in the interior.  Previously, the code would fall back to bilinear interpolation on the edges and corners, which could cause unexpected behavior.
Fixes #1554 
```
GeoTiff:
10.0  10.0    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND
10.0  10.0  10.0  10.0    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND
10.0  10.0  10.0  10.0  10.0  10.0    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND
10.0  10.0  10.0  10.0  10.0  10.0  10.0  10.0    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND    ND
10.0  10.0  10.0 …
```
> Do Bicubic Interpolation on Entire Tile

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloWriteStrategy.scala
- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraRDDWriter.scala
- hbase/src/main/scala/geotrellis/spark/io/hbase/HBaseRDDWriter.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3RDDWriter.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopRDDWriter.scala
We need to be sure that partition is not empty, as creating a connection / session is expensive.
Thx @fosskers for a pointer long time ago.
> RDDWriters resources allocation improvements

- docs/vector/geojson-support.md
Fixes #1432 
Expands the documentation for GeoJson support.
> Update to GeoJson documentation

- docs/guide/faq.md
This PR adds a FAQ regarding implicits and typeclasses.
> FAQ - typeclass use

- contributing.md
- docs/contributing.md
- mkdocs.yml
I added a symlink to the main file in the front of the repo, and updated some information / formatting.
> Spruce up `Contributing`

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/writer/TiffTagFieldValue.scala
> Fix for #1756: TIFF tag value wrapping

- spark/src/main/scala/geotrellis/spark/ingest/Ingest.scala
- spark/src/main/scala/geotrellis/spark/ingest/MultibandIngest.scala
- spark/src/test/scala/geotrellis/spark/ingest/IngestSpec.scala
Update to satisfy https://github.com/geotrellis/geotrellis/issues/1717
> Ingest objects update

- docs/architecture/high-performance-scala.md
> Additional Text Relating to Performance

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/BigTiffSpec.scala
- raster-test/src/test/scala/geotrellis/raster/io/geotiff/CroppedWindowedGeoTiffSpec.scala
- raster-test/src/test/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTileSpec.scala
- raster-test/src/test/scala/geotrellis/raster/io/geotiff/MultibandCropIteratorSpec.scala
- raster-test/src/test/scala/geotrellis/raster/io/geotiff/SinglebandCropIteratorSpec.scala
- raster-test/src/test/scala/geotrellis/raster/io/geotiff/UInt16GeoTiffTileSpec.scala
- raster-test/src/test/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReaderSpec.scala
- raster-test/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala
- raster-test/src/test/scala/geotrellis/raster/rasterize/polygon/PolygonRasterizerSpec.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiff.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/MultibandGeoTiff.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/SinglebandGeoTiff.scala
> Removed implicits on GeoTiffs that caused confusion

- spark/src/main/scala/geotrellis/spark/join/VectorJoin.scala
This changeset includes various fixes and improvements to vector join.
Connects #1795
> VectorJoin Fixes

- docs/guide/core-concepts.md
The changes here address issues in the `CellType` documentation.
> Update docs with celltype suggestions

- docs/tutorials/kernel-density.md
This PR alters the kernel density tutorial so that the code can be copied and pasted into a console and run directly.
> Ensure code in tutorial runs

- spark-etl/src/main/resources/output-schema.json
Fixes #1819 after locationtech repo move
> Etl typos fix

- project/Dependencies.scala
> Update collect neighbors

- slick/src/main/scala/geotrellis/slick/PostGisProjectionSupport.scala
- slick/src/test/scala/geotrellis/slick/PostGisProjectionSupportSpec.scala
- vector/build.sbt
- vector/src/main/scala/geotrellis/vector/io/WKB/WKB.scala
- vector/src/main/scala/geotrellis/vector/io/WKT/WKT.scala
> [BACKPORT] Fix support for slick WKB reading

- raster/src/main/scala/geotrellis/raster/interpolation/InverseDistanceWeighted.scala
> [BACKPORT] Fixed typo in variable names in IDW

- spark/src/main/scala/geotrellis/spark/join/VectorJoin.scala
- spark/src/main/scala/org/apache/spark/rdd/FilteredCartesianRDD.scala
- spark/src/test/scala/geotrellis/spark/join/VectorJoinRDDSpec.scala
> [BACKPORT] Remediate VectorJoin 

- project/build.properties
- sbt
Fixes #1788 after locationtech repo move
> upgrade sbt up to .13; updated sbt download file

- docs/tutorials/reading-geoTiffs.md
- mkdocs.yml
Fixes some rendering issues, as well as makes the file visible to ReadTheDocs.
> Spruce up GeoTiff IO tutorial

- README.md
The link provided didn't fetch the image correctly.
> Fix broken RTD badge

- docs/guide/core-concepts.md
This PR adds some introductory discussion for the `LayoutScheme` and `LayoutDefinition` core concepts
> Add to core concepts in guide

- pointcloud/src/main/scala/geotrellis/spark/io/hadoop/HadoopPointCloudRDD.scala
- pointcloud/src/main/scala/geotrellis/spark/io/hadoop/formats/PointCloudInputFormat.scala
- pointcloud/src/main/scala/geotrellis/spark/io/s3/S3PointCloudInputFormat.scala
- pointcloud/src/main/scala/geotrellis/spark/io/s3/S3PointCloudRDD.scala
- pointcloud/src/main/scala/geotrellis/spark/pointcloud/dem/Implicits.scala
- pointcloud/src/main/scala/geotrellis/spark/pointcloud/dem/PointCloudToDem.scala
- pointcloud/src/main/scala/geotrellis/spark/pointcloud/dem/PointCloudToDemMethods.scala
- pointcloud/src/main/scala/geotrellis/spark/pointcloud/json/MetadataFormat.scala
- pointcloud/src/main/scala/geotrellis/spark/pointcloud/tiling/TilerMethods.scala
- Allow pulling only a subset of dim types
- pointcloud to dem methods
> Pointcloud changes

- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopAttributeStore.scala
> [BACKPORT] - Use relative paths to check if layerExists

- docs/guide/core-concepts.md
- pointcloud/src/main/scala/geotrellis/spark/pointcloud/triangulation/HalfEdgeTable.scala
- pointcloud/src/main/scala/geotrellis/spark/pointcloud/triangulation/LightPoint.scala
- pointcloud/src/main/scala/geotrellis/spark/pointcloud/triangulation/PointCloudTriangulation.scala
- pointcloud/src/main/scala/geotrellis/spark/pointcloud/triangulation/TinToDem.scala
- raster/src/main/scala/geotrellis/raster/CellSize.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopAttributeStore.scala
This PR contains some other changes and merges from master, as well.
> Added pointcloud-specific triangulation

- pointcloud/src/main/scala/geotrellis/spark/pointcloud/triangulation/HalfEdgeTable.scala
- pointcloud/src/main/scala/geotrellis/spark/pointcloud/triangulation/PointCloudTriangulation.scala
- raster/src/main/scala/geotrellis/raster/triangulation/DelaunayRasterizer.scala
- vector/src/main/java/geotrellis/vector/triangulation/ShewchuksDeterminant.java
- vector/src/main/scala/geotrellis/vector/triangulation/FastDelaunay.scala
- vector/src/main/scala/geotrellis/vector/triangulation/HalfEdge.scala
- vector/src/main/scala/geotrellis/vector/triangulation/LightPoint.scala
- vector/src/main/scala/geotrellis/vector/triangulation/Predicates.scala
- vector/src/main/scala/geotrellis/vector/triangulation/StitchedDelaunay.scala
Commit from #1901, but with proper signoff.
@jpolchlo as part of the eclipse requirements, you'll have to sign off on commits (for each commit, use the `-s` flag). I've signed off on this one.
> Slight changes to PointCloudTriangulation

- pointcloud/build.sbt
- project/Dependencies.scala
Move repo to sonatype and version to snapshot
> PDAL dep update

- proj4/src/main/java/org/osgeo/proj4j/CRSFactory.java
- proj4/src/main/scala/geotrellis/proj4/CRS.scala
Signed-off-by: Simeon H.K. fitch <simeon@metasim.net>
> Fixed typo for CRS authority "NAD83"

- raster/src/main/scala/geotrellis/raster/io/geotiff/ArraySegmentBytes.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/Float32GeoTiffSegmentCollection.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/Float64GeoTiffSegmentCollection.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/LazySegmentBytes.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReader.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/TiffTagsReader.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/util/ByteReaderExtensions.scala
This PR changes the parameter order of a few internal methods and also fixes an issue where chunks would be created when they were not need/used. These changes have been taken from #1905.
> Small Updates for the 1.0.0

- raster/src/main/scala/geotrellis/raster/io/geotiff/ArraySegmentBytes.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/Float32GeoTiffSegmentCollection.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/Float64GeoTiffSegmentCollection.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/LazySegmentBytes.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReader.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/TiffTagsReader.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/util/ByteReaderExtensions.scala
> [BACKPORT] Small Updates for the 1.0.0 

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloValueReader.scala
- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraValueReader.scala
- hbase/src/main/scala/geotrellis/spark/io/hbase/HBaseValueReader.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3ValueReader.scala
- spark/src/main/scala/geotrellis/spark/io/file/FileValueReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopValueReader.scala
- spark/src/main/scala/geotrellis/spark/io/package.scala
- spark/src/main/scala/org/apache/spark/rdd/FilteredCartesianRDD.scala
> [BACKPORT] Final 1.0 changes

- .travis/build-and-test-set-2.sh
- build.sbt
- geotools/src/test/scala/geotrellis/geotools/GeometryToSimpleFeatureMethodsSpec.scala
- geowave/build.sbt
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeoWaveFeatureRDDReader.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeowaveLayerReader.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeowaveLayerWriter.scala
- project/Version.scala
- scripts/buildall.sh
- scripts/publish-local.sh
- scripts/publish-m2.sh
pretty basic version updates to the 0.9.3 release, with a small code change to a simplification on the API
most significant impact is going to be upgrading to geotools 16.0 from 14.4 but it the project does build on 16.0
> updates for geowave 0.9.3 release

- docs/CHANGELOG.md
**Note:** RTD wants *four* spaces in front of a subbullet.
> 1.0 Changelog tweaks

- docs/CHANGELOG.md
Original: https://github.com/locationtech/geotrellis/pull/1938
> [1.0 branch] Changelog Tweaks

- .travis/build-and-test-set-1.sh
- build.sbt
- pointcloud/src/main/scala/geotrellis/spark/io/hadoop/HadoopPointCloudRDD.scala
- pointcloud/src/main/scala/geotrellis/spark/io/hadoop/formats/PointCloudInputFormat.scala
- pointcloud/src/main/scala/geotrellis/spark/io/s3/S3PointCloudInputFormat.scala
- pointcloud/src/main/scala/geotrellis/spark/io/s3/S3PointCloudRDD.scala
- pointcloud/src/main/scala/geotrellis/spark/pointcloud/json/package.scala
- pointcloud/src/main/scala/geotrellis/spark/pointcloud/tiling/CutPointCloud.scala
- pointcloud/src/main/scala/geotrellis/spark/pointcloud/tiling/Implicits.scala
- pointcloud/src/main/scala/geotrellis/spark/pointcloud/triangulation/DelaunayPointSet.scala
- pointcloud/src/test/scala/geotrellis/spark/io/s3/S3PackedPointsRDDSpec.scala
- pointcloud/src/test/scala/geotrellis/spark/pointcloud/dem/PointCloudDemSpec.scala
- pointcloud/src/test/scala/geotrellis/spark/pointcloud/triangulation/PointCloudTriangulationSpec.scala
> Minor fixes

- s3/src/main/scala/geotrellis/spark/io/s3/S3InputFormat.scala
Previously, the NF ("Next Fit") strategy was used for building S3 partitions.  Compared to an optimal offline algorithm, NF offers an approximation ratio of 2 whereas H3 offers an approximation ratio of < 1.75.
Please see [1] for more details.
1. Epstein, Leah, Lene M. Favrholdt, and Jens S. Kohrt.
"Comparing online algorithms for bin packing problems."
Journal of Scheduling 15.1 (2012): 13-21.
Connects #1354
> Use H3 Rather Than NF Approximation Algorithm

- spark/src/test/scala/geotrellis/spark/SerializationTests.scala
> Tile logger serialization tests

- .travis/build-and-test-set-1.sh
- .travis/build-and-test-set-2.sh
- pointcloud/src/main/scala/geotrellis/pointcloud/pipeline/PipelineExpressions.scala
- pointcloud/src/main/scala/geotrellis/pointcloud/pipeline/package.scala
> Pipeline Implicits cleanup

- pointcloud/build.sbt
- pointcloud/src/main/scala/geotrellis/pointcloud/pipeline/package.scala
- pointcloud/src/main/scala/geotrellis/pointcloud/spark/json/Implicits.scala
> Update pointcloud project

- pointcloud/src/main/scala/geotrellis/pointcloud/spark/io/s3/S3PointCloudInputFormat.scala
> PointCloud S3Input format fix

- spark/src/main/scala/geotrellis/spark/io/avro/codecs/ConstantTileCodecs.scala
- spark/src/main/scala/geotrellis/spark/io/avro/codecs/Implicits.scala
- spark/src/main/scala/geotrellis/spark/io/file/FileLayerDeleter.scala
* Fixes #1992 (Missing Avro ConstantTileCodecs)
* Fixes #2011 (FileLayerDeleter bug)
> Small Bugfixes

- spark/src/main/scala/geotrellis/spark/join/VectorJoin.scala
- spark/src/main/scala/org/apache/spark/rdd/FilteredCartesianRDD.scala
Expanding documentation for FilteredCartesianRDD which relies on knowledge about spark internal implementations.
> Additional comments for FilteredCartesianRDD

- docs/CHANGELOG.rst
- docs/contributing.rst
- docs/guide/etl.rst
- docs/guide/spark.rst
- docs/tutorials/reading-geoTiffs.rst
This should make it clearer for @lossyrob how to add a new section.
> Docs: Spruce up Changelog

- docs/tutorials/quickstart.rst
> Fixed up quickstart guide.

- docs/guide/faq.rst
- docs/tutorials/setup.rst
A very popular question about Guava versions incompatibilities, this PR clarifies a bit the situation and provides a solution.
> Docs: Add shading information to FAQ

- spark/src/main/scala/geotrellis/spark/tiling/ZoomedLayoutScheme.scala
> Fix layoutForZoom function with return for level 0

- spark/src/main/scala/geotrellis/spark/io/avro/AvroEncoder.scala
Makes changes in https://github.com/locationtech/geotrellis/pull/1952/files eligible for 1.1
> Make AvroEncoder interface compatible with 1.0

- docs/guide/core-concepts.rst
- docs/guide/etl.rst
- docs/guide/spark.rst
I saw these over the weekend, here's the fix.
> Docs: Wrangling more wild markup

- docs/guide/faq.rst
- docs/index.rst
This is to match the corrections that were made in the Quick Start guide.
> Docs: Fix "Hello, Raster!" example on landing page

- publish/Dockerfile
- publish/Makefile
- publish/README.md
- publish/plugins.sbt
Updated to 1.1, also some fixes to the processes.
> Fixes to publish workflow

- spark/src/main/scala/geotrellis/spark/io/http/util/HttpRangeReader.scala
Support signed s3 urls that don't allow head requests.
Supersedes #2088
Fixes #2084
> Signed s3 streaming 

- spark/src/main/scala/geotrellis/spark/io/http/util/HttpRangeReader.scala
> [BACKPORT]: Signed s3 streaming

- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraRDDWriter.scala
> [BACKPORT]: Ensure keyspace exists in CassandraRDDWriter

- proj4/src/test/scala/geotrellis/proj4/io/wkt/WKTParserTest.scala
- raster/src/main/scala/geotrellis/raster/render/ColorMaps.scala
> [BACKPORT]: Added library of land use classification color maps.

- raster-test/src/test/scala/geotrellis/raster/render/ColorMapSpec.scala
- raster/src/main/scala/geotrellis/raster/render/ColorMap.scala
- raster/src/main/scala/geotrellis/raster/render/png/PngColorEncoding.scala
> [Backport]: Fix usage of IntCachedColorMap in Indexed PNG encoding

- docs/CHANGELOG.rst
> [BACKPORT] Docs: Updating changelog for 1.1.0-RC2

- raster-test/src/test/scala/geotrellis/raster/transform/TransformMethodsSpec.scala
- raster/src/main/scala/geotrellis/raster/package.scala
- raster/src/main/scala/geotrellis/raster/transform/Implicits.scala
- raster/src/main/scala/geotrellis/raster/transform/TransformMethods.scala
- raster/src/main/scala/geotrellis/raster/transform/TransformTileMethods.scala
> Tile transformation operations

- spark/src/main/scala/geotrellis/spark/io/avro/codecs/ConstantTileCodecs.scala
- spark/src/test/scala/geotrellis/spark/io/avro/AvroTools.scala
- spark/src/test/scala/geotrellis/spark/io/avro/ConstantTileCodecsSpec.scala
> Schema for `intConstantTileCodec` is incorrect

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloLayerDeleter.scala
- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloWriteStrategy.scala
Also close in a finally clause for AccumuloWriteStrategy.
Fixes #2089
> In AccumuloLayerDeleter, close batch deleter

- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffRDD.scala
- spark/src/test/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffRDDSpec.scala
> [BACKPORT] Resolved repartitioning issue with HadoopGeoTiffRDD

- spark/src/main/scala/geotrellis/spark/io/avro/codecs/ConstantTileCodecs.scala
- spark/src/test/scala/geotrellis/spark/io/avro/AvroTools.scala
- spark/src/test/scala/geotrellis/spark/io/avro/ConstantTileCodecsSpec.scala
> [BACKPORT] Schema for `intConstantTileCodec` is incorrect 

- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopAttributeStore.scala
> [BACKPORT] Get absolute path for attributePath 

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloLayerDeleter.scala
- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloWriteStrategy.scala
> [BACKPORT] In AccumuloLayerDeleter, close batch deleter

- docs/CHANGELOG.rst
> [BACKPORT] Updated changelog for 1.1.0-RC3 

- spark/src/main/scala/geotrellis/spark/tiling/ZoomedLayoutScheme.scala
Thx @Charmatzis for this report.
> Fix TMS scheme min zoom level

- s3-test/src/test/scala/geotrellis/spark/io/s3/S3InputFormatSpec.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3InputFormat.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/config/json/ConfigFormats.scala
> [BACKPORT] S3InputFormat - bucket names support period and dashes

- spark/src/main/scala/geotrellis/spark/tiling/ZoomedLayoutScheme.scala
> [BACKPORT] Fix TMS scheme min zoom level

- CONTRIBUTING.md
> [BACKPORT] Added back CONTRIBUTING.md

- s3-test/src/test/scala/geotrellis/spark/io/s3/S3AttributeStoreSpec.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3AttributeStore.scala
> [BACKPORT] S3AttributeStore now handles ending slashes in prefix.

- raster-test/src/test/scala/geotrellis/raster/CellTypeSpec.scala
- raster/src/main/scala/geotrellis/raster/CellType.scala
> [BACKPORT] Reorganized handling of `CellType.name`

- spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/config/Output.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/hadoop/SpatialRenderOutput.scala
- spark/src/main/scala/geotrellis/spark/KeyBounds.scala
- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
- spark/src/main/scala/geotrellis/spark/tiling/CutTiles.scala
- util/src/main/scala/geotrellis/util/LazyLogging.scala
> [BACKPORT] Repartition in ETL when re-tiling increases layer resolution

- docs/CHANGELOG.rst
> [BACKPORT] Updated changelog for 1.1.0-RC4

- geotools/build.sbt
- geowave/build.sbt
> [BACKPORT 1.1] Moved jai and geotiff dependencies to test only in geotools subproject

- spark-etl/src/main/scala/geotrellis/spark/etl/config/Output.scala
- spark-etl/src/test/scala/geotrellis/spark/etl/EtlSpec.scala
> Support for the ability to specify output CRS via proj4 string.

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloLayerReader.scala
> [BACKPORT 1.1] Added conditional to key bounds decomposition to detect full bounds query in Acccumulo.

- spark-etl/src/main/scala/geotrellis/spark/etl/config/Output.scala
- spark-etl/src/test/scala/geotrellis/spark/etl/EtlSpec.scala
See #2072
Signed-off-by: Matthew Eldridge <meldridge@astraea.io>
> [BACKPORT 1.1] Support for the ability to specify output CRC via proj4 string.

- raster-test/src/test/scala/geotrellis/raster/CellTypeSpec.scala
- raster/src/main/scala/geotrellis/raster/CellType.scala
- raster/src/main/scala/geotrellis/raster/CellTypeEncoding.scala
- raster/src/main/scala/geotrellis/raster/UserDefinedNoDataConversions.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/writer/TiffTagFieldValue.scala
- raster/src/main/scala/geotrellis/raster/io/json/Implicits.scala
> [BACKPORT 1.1] Fix 2166

- raster/src/main/scala/geotrellis/raster/ArrayTile.scala
> In ArrayTile.convert, debug instead of warn against floating point data loss.

- docs/CHANGELOG.rst
> [BACKPORT 1.1] Changelog 1.1.0-RC5

- spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala
> [BACKPORT 1.1] ETL typos fix

- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraRDDReader.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3RDDReader.scala
- spark-testkit/src/main/scala/geotrellis/spark/testkit/TestEnvironment.scala
- spark/src/main/scala/geotrellis/spark/io/file/FileRDDReader.scala
> [BACKPORT 1.1] Fix issue with duplicate tiles being read for File and Cassandra backends

- project/Version.scala
Signed-off-by: Eugene Cheipesh <echeipesh@gmail.com>
> Scala version 2.11.11

- raster-test/src/test/scala/geotrellis/raster/histogram/HistogramSpec.scala
- raster/src/main/scala/geotrellis/raster/histogram/Histogram.scala
Implements a pattern have duplicated in my code a number of times.
> Added convenience method to get bin labels paired with their counts.

- spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala
- spark/src/main/scala/geotrellis/spark/ingest/Ingest.scala
- spark/src/main/scala/geotrellis/spark/ingest/MultibandIngest.scala
- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReprojectMethods.scala
- spark/src/test/scala/geotrellis/spark/ingest/IngestSpec.scala
Target sellSize should be passed in all the reproject functions
Closes #2170
> Fix ETL upsampling bug

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/ArrayMultibandTileSpec.scala
- raster/src/main/scala/geotrellis/raster/MultibandTile.scala
- spark/src/main/scala/geotrellis/spark/mask/Mask.scala
- vector/src/main/scala/geotrellis/vector/Geometry.scala
- vector/src/main/scala/geotrellis/vector/MultiPolygon.scala
- vector/src/main/scala/geotrellis/vector/Polygon.scala
`MultibandTile.band` should not be used unless you're absolutely sure that the band index you're calling for is valid.
> Add `MultibandTile.safeBand`

- docs/tutorials/quickstart.rst
> Add a mention of the spark.serializer flag to the quickstart docs

- spark/src/main/scala/geotrellis/spark/costdistance/IterativeCostDistance.scala
The implicit parameter has been removed from `IterativeCostDistance.apply`
> Remove Implicit Parameter

- doc-examples/build.sbt
- doc-examples/src/main/scala/geotrellis/doc/examples/spark/LandsatMultibandRDDExample.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffRDD.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3InputFormat.scala
Also:
- Fixes #2231 
- Fixes #2232 
See: https://stackoverflow.com/questions/44421705/whats-the-easiest-way-to-load-single-band-landsat-8-rasters-from-aws-and-combin
> Example for creating a MultiBandTile RDD from Landsat GeoTiffs.

- raster/src/main/scala/geotrellis/raster/rasterize/FeatureRasterizeMethods.scala
- raster/src/main/scala/geotrellis/raster/rasterize/GeometryRasterizeMethods.scala
> Fixes typos with rasterizer extension methods

- .travis/hbase-install.sh
> [BACKPORT 1.1] Bump up HBase test DB

- project/Dependencies.scala
- spark-etl/build.sbt
- spark-etl/src/main/resources/input-schema.json
- spark-etl/src/main/scala/geotrellis/spark/etl/config/BaseEtlConf.scala
- spark-etl/src/main/scala/geotrellis/spark/etl/config/ConfigParse.scala
> [BACKPORT 1.1] Move to a different Json Schema validator

- spark/src/main/scala/geotrellis/spark/costdistance/IterativeCostDistance.scala
> [BACKPORT 1.1] Removed implicit parameter in IterativeCostDistance

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloLayerReader.scala
> [BACKPORT 1.1] Fixed logic in decompose function

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/BigTiffSpec.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReader.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/TiffTagsReader.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/util/ByteReaderExtensions.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/util/TiffTagOffsetSize.scala
> [BACKPORT 1.1] Fixed issue with BigTiff vs non-BigTiff offset value packing

- raster/src/main/scala/geotrellis/raster/rasterize/FeatureRasterizeMethods.scala
- raster/src/main/scala/geotrellis/raster/rasterize/GeometryRasterizeMethods.scala
> [BACKPORT 1.1] Fixes typos with rasterizer extension methods

- raster-test/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/MultibandGeoTiff.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/package.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/tags/TiffTags.scala
> [BACKPORT 1.1] Fix writing multiband GeoTiff with compression

- spark/src/main/scala/geotrellis/spark/buffer/BufferUnionable.scala
- spark/src/test/scala/geotrellis/spark/buffer/BufferUnionableSpec.scala
> Fix PointCloud branch tests

- .travis/build-and-test-set-2.sh
- spark-etl/src/test/scala/geotrellis/spark/etl/config/ConfigSpec.scala
Fixes spark-etl tests compilation, adds tests tun into travis.
> Fix spark-etl tests

- spark/src/main/scala/geotrellis/spark/package.scala
- spark/src/test/scala/geotrellis/spark/filter/TileLayerRDDFilterMethodsSpec.scala
More generic Metadata => MapTransform implicit, added tests.
Thanks @aaron-santos for report!
> Allow Contains(Point) query for temporal rdds

- s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffInfoReader.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffRDD.scala
- spark/src/main/scala/geotrellis/spark/io/GeoTiffInfoReader.scala
Related to: 
#2307
#2308
#2309
> Fix GeoTiffInfo serialization issues

- spark/src/main/scala/geotrellis/spark/pyramid/Pyramid.scala
This reverts commit 3d4be0be42e14868d99c090816d137c0ed070492.
The change has a surprising result of checking the pyramid:
> Revert "Merge pyramid tiles during combine step"

- raster/src/main/scala/geotrellis/raster/render/ColorRamps.scala
Lets you provide the number of stops.
> Added utility to construct greyscale color ramps

- raster/src/main/scala/geotrellis/raster/rasterize/Rasterizer.scala
This partially satisfies https://github.com/locationtech/geotrellis/issues/2343
> Fuse Loops

- docs/CHANGELOG.rst
> Update CHANGELOG to reflect VectorTile updates

- build.sbt
Signed-off-by: Simeon H.K. fitch <fitch@astraea.io>
> Added SCM info, per #2076.

- raster-test/src/test/scala/geotrellis/raster/RasterExtentSpec.scala
- raster/src/main/scala/geotrellis/raster/RasterExtent.scala
> Grid bounds bug

- docs/guide/tile-backends.rst
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopLayerProvider.scala
* Added wasb and wasbs URI schemes
Signed-off-by: Austin Heyne <aheyne@ccri.com>
Fixes #2373
> GeoTrellis-2372 Add Microsoft Azure Blob Storage Support

- spark/src/main/scala/geotrellis/spark/io/slippy/HadoopSlippyTileWriter.scala
> Changed scheme path file from /User -> current working dir

- macros/build.sbt
- project/Dependencies.scala
- project/Version.scala
> Normalized spire version per #2397.

- raster-test/src/test/scala/geotrellis/raster/ArrayTileSpec.scala
- raster-test/src/test/scala/geotrellis/raster/ConstantTileSpec.scala
- raster/src/main/scala/geotrellis/raster/ConstantTile.scala
Signed-off-by: Simeon H.K. fitch <fitch@astraea.io>
> Added ConstantTile.fromBytes

- spark/src/main/scala/geotrellis/spark/io/AttributeCaching.scala
This PR potentially resolves the `AbstractMethodException` issue that is found in `AttributeCaching`. It's a potential fix since the error could not be replicated locally, but the output of the binary issues report suggests that the problem may be resolved.
> AbstractMethodException Issue in AttributeCaching Fix

- vector/src/main/scala/geotrellis/vector/Extent.scala
- vector/src/main/scala/geotrellis/vector/Feature.scala
- vector/src/main/scala/geotrellis/vector/GeomFactory.scala
- vector/src/main/scala/geotrellis/vector/Geometry.scala
- vector/src/main/scala/geotrellis/vector/GeometryCollection.scala
- vector/src/main/scala/geotrellis/vector/GeometryCollectionBuilder.scala
- vector/src/main/scala/geotrellis/vector/Results.scala
- vector/src/main/scala/geotrellis/vector/affine/AffineTransformation.scala
- vector/src/main/scala/geotrellis/vector/interpolation/EmpiricalVariogram.scala
- vector/src/main/scala/geotrellis/vector/interpolation/Kriging.scala
- vector/src/main/scala/geotrellis/vector/interpolation/LeastSquaresFittingNuggetProblem.scala
- vector/src/main/scala/geotrellis/vector/interpolation/LeastSquaresFittingProblem.scala
- vector/src/main/scala/geotrellis/vector/interpolation/Semivariogram.scala
- vector/src/main/scala/geotrellis/vector/mesh/HalfEdge.scala
- vector/src/main/scala/geotrellis/vector/mesh/HalfEdgeTable.scala
- vector/src/main/scala/geotrellis/vector/prepared/PreparedGeometry.scala
- vector/src/main/scala/geotrellis/vector/triangulation/BoundaryDelaunay.scala
- vector/src/main/scala/geotrellis/vector/triangulation/DelaunayStitcher.scala
- vector/src/main/scala/geotrellis/vector/triangulation/DelaunayTriangulation.scala
- vector/src/main/scala/geotrellis/vector/triangulation/QuadricError.scala
- vector/src/main/scala/geotrellis/vector/triangulation/StitchedDelaunay.scala
- vector/src/main/scala/geotrellis/vector/triangulation/TriangleMap.scala
- vector/src/main/scala/geotrellis/vector/triangulation/TriangulationPredicates.scala
- vector/src/main/scala/geotrellis/vector/voronoi/ConformingDelaunay.scala
- vector/src/main/scala/geotrellis/vector/voronoi/Delaunay.scala
- vector/src/main/scala/geotrellis/vector/voronoi/Voronoi.scala
- vector/src/main/scala/geotrellis/vector/voronoi/VoronoiDiagram.scala
Stray whitespace has also been removed.
Resolves #2381
> Mark Various Vector Classes Serializable

- spark/src/main/scala/geotrellis/spark/io/avro/codecs/Implicits.scala
> Fix ConstantTile union codec

- docs/architecture/005-etl-pipeline.rst
- docs/architecture/adrs.rst
- docs/guide/examples.rst
- docs/index.rst
- spark/src/main/scala/geotrellis/spark/package.scala
> Docs: Tile -> TileLayerRDD

- spark/src/main/resources/reference.conf
- spark/src/main/scala/geotrellis/spark/io/AttributeCaching.scala
> Add AttributeStore cache enabled flag

- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
Removed method is not sensitive to tile sizes and resolution changes stemming from target layout selection. Removing until reproject performance can be treated as a whole to avoid.
The work that prompted this optimization is still going on separate from this issue: https://github.com/echeipesh/geotrellis/tree/refactor/rdd-reproject
Resolves: https://github.com/locationtech/geotrellis/issues/2315
> Remove partitioner resizing from TileRDDReproject

- build.sbt
https://repo.locationtech.org/content/repositories/geotrellis-releases
> Enable publishing to LocationTech Releases repo

- build.sbt
- raster/src/main/scala/geotrellis/raster/distance/EuclideanDistanceTileMethods.scala
- raster/src/main/scala/geotrellis/raster/rasterize/Rasterizer.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopCollectionReader.scala
- spark/src/main/scala/geotrellis/spark/tiling/MapKeyTransform.scala
Misc changes and cleanups required for RC1 publication.
> 1.2-RC1  cleanup

- raster/src/main/scala/geotrellis/raster/io/geotiff/writer/CoordinateSystemParser.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala
> Fix LCC projection inaccuracy

- scripts/emr/Makefile
Updates json parsing, taking into account latest released terraform changes.
> Update EMR Makefile

- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
Connects: https://github.com/locationtech/geotrellis/pull/2451
> Avoid using RDD join to buffer sizes in RDD reproject

- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffSegmentLayout.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffTile.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffInfoReader.scala
- s3/src/main/scala/geotrellis/spark/io/s3/S3GeoTiffRDD.scala
- s3/src/test/scala/geotrellis/spark/io/s3/S3GeoTiffRDDSpec.scala
- spark/src/main/scala/geotrellis/spark/io/GeoTiffInfoReader.scala
- spark/src/main/scala/geotrellis/spark/io/RasterReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffInfoReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopGeoTiffRDD.scala
Resolves: https://github.com/locationtech/geotrellis/issues/2469
Additionally there needs to be some effort to review the added code since 1.1 that enabled these features to make sure it still makes sense given this refactor.
> Fix GeoTiffRDD Segment Partitioning

- doc-examples/src/main/scala/geotrellis/doc/examples/spark/ClipToGridExamples.scala
See https://stackoverflow.com/questions/47359243/geotrellis-get-the-points-that-fall-in-a-polygon-grid-rdd
> Added example of using clipToGrid to calculate mean over points

- spark/src/main/scala/geotrellis/spark/pyramid/Pyramid.scala
Supersedes: https://github.com/locationtech/geotrellis/pull/2496
Implements the same optimization using one of the functions available to `TileMergeMethods`. This allows this optimization to be back-ported to 1.2 branch.
Also adds documentation and usage notes to relevant Pyramid functions.
> Pyramid optimization: Resample on map side

- bench/src/main/scala/geotrellis/spark/io/index/MergeQueueBench.scala
@metasim Seemed like reasonable updates, but as you're the author can you look over and make sure it makes sense?
> Updated benchmark for compile

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloInstance.scala
- docs/CHANGELOG.rst
Changelog update + formatting changes
> Update changelog to reflect kerberos changes 

- raster/src/main/scala/geotrellis/raster/CellType.scala
- raster/src/main/scala/geotrellis/raster/ConstantTile.scala
- raster/src/test/scala/geotrellis/raster/CellTypeSpec.scala
> across ConstantNoData and UserDefinedNoData.
> Signed-off-by: Simeon H.K. fitch <fitch@astraea.io
Rebase of https://github.com/locationtech/geotrellis/pull/2387
> Normalized ability to query NoData values

- accumulo/build.sbt
- build.sbt
- cassandra/build.sbt
- doc-examples/build.sbt
- geomesa/build.sbt
- geotools/build.sbt
- geowave/build.sbt
- hbase/build.sbt
- macros/build.sbt
- proj4/build.sbt
- project/Dependencies.scala
- project/Version.scala
- project/build.properties
- project/plugins.sbt
- raster/build.sbt
- s3-testkit/build.sbt
- s3/build.sbt
- sbt
- slick/build.sbt
- spark-etl/build.sbt
- spark-testkit/build.sbt
- spark/build.sbt
- util/build.sbt
- vector/build.sbt
- vectortile/build.sbt
Fixes #2172 
~Blocked by https://github.com/sksamuel/sbt-scapegoat/issues/55~
> Update SBT up to 1.1.0

- scripts/publish-local.sh
- scripts/publish-m2.sh
This PR fixes deprecated sbt 0.13.x syntax in sh publish scripts.
> Fix publish local scripts

- .travis/build-and-test-set-1.sh
- project/Dependencies.scala
- project/Version.scala
- spark-pipeline/build.sbt
- spark-pipeline/src/main/scala/geotrellis/spark/pipeline/ast/Transform.scala
- spark-pipeline/src/main/scala/geotrellis/spark/pipeline/json/Implicits.scala
This PR fixes compatibility with the current geotrellis master, updates circe version.
> Update circe version and Pipeline project compilation

- s3/src/main/scala/geotrellis/spark/io/s3/S3LayerUpdater.scala
This duplicates some code from `LayerUpdater.validateUpdate` in order to avoid casting `AttributeStore` to `S3AttributeStore` in `S3LayerUpdater`. 
The required `bucket` and `prefix` for the layer update can be read from the layer header.
Closes #2559
> Fix S3LayerUpdater to avoid casting to S3AttributeStore

- spark-testkit/src/main/scala/geotrellis/spark/testkit/TestEnvironment.scala
Signed-off-by: Simeon H.K. Fitch <fitch@astraea.io>
> Provided override hook for Spark master in TestEnvironment.

- raster/src/main/scala/geotrellis/raster/crop/RasterCropMethods.scala
Signed-off-by: Kevin Thompson <kevin.thompson@theautomaters.com>
> Update crop to clamp based on options

- raster/src/main/scala/geotrellis/raster/hydrology/FlowDirection.scala
Adding a couple changes to improve performance of flow direction.
* only calculate neighbors once per row and column
* "short circuit" check for isSink
Performance Test on a 433MB tiff shows an improvement of 70%.
Signed-off-by: Jeff Melching <jeff.melching@climate.com>
> Improve performance of flow direction

- raster/src/main/scala/geotrellis/raster/io/geotiff/LazySegmentBytes.scala
Previously LazySegmentBytes would read all segments between the first and
last segment causing much more data to be downloaded when the
StreamingByteReader is used.
Signed-off-by: Kevin Thompson <kevin.thompson@theautomaters.com>
> Update LazySegmentBytes to only read required segments

- s3/src/main/scala/geotrellis/spark/io/s3/geotiff/S3IMGeoTiffAttributeStore.scala
- s3/src/main/scala/geotrellis/spark/io/s3/geotiff/S3JsonGeoTiffAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/file/geotiff/FileIMGeoTiffAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/file/geotiff/FileJsonGeoTiffAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/geotiff/GeoTiffMetadataTree.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/geotiff/HadoopIMGeoTiffAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/geotiff/HadoopJsonGeoTiffAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/geotiff/InMemoryGeoTiffAttributeStore.scala
Implement persistence functions for unstructured COGs.
@notthatbreezy if you can make a review of this PR it would be great.
> Implement persistence functions for Hadoop & File UCOGs

- .travis/build-and-test-set-1.sh
An attempt to fix CI timeouts.
> Fix Travis CI timeouts

- docs/CHANGELOG.rst
- spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala
- spark-pipeline/src/main/scala/geotrellis/spark/pipeline/ast/Transform.scala
- spark/src/main/scala/geotrellis/spark/ingest/Ingest.scala
- spark/src/main/scala/geotrellis/spark/ingest/MultibandIngest.scala
- spark/src/main/scala/geotrellis/spark/tiling/TilerMethods.scala
This PR fixes some of `TilerMethods` functions declarations
Closes #2278
> TilerMethods return TileLayerRDD types

- docs/CHANGELOG.rst
- raster/src/main/scala/geotrellis/raster/crop/MultibandTileCropMethods.scala
- raster/src/main/scala/geotrellis/raster/crop/SinglebandTileCropMethods.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffMultibandTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffTile.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/MultibandGeoTiff.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/SinglebandGeoTiff.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/MultibandGeoTiffSpec.scala
- raster/src/test/scala/geotrellis/raster/io/geotiff/SinglebandGeoTiffSpec.scala
Fixes GeoTiff crop by extent function behaviour.
> Crop function works properly with Extents out of tiff bounds

- .travis/hbase-install.sh
This PR changes HBase links to use US mirror.
> Fix links to HBase

- raster/src/main/scala/geotrellis/raster/io/geotiff/reader/GeoTiffReader.scala
Signed-off-by: Simeon H.K. Fitch <fitch@astraea.io>
> Added forwarding method for backwards compatibility with 1.2.x.

- s3/src/main/scala/geotrellis/spark/io/s3/geotiff/S3GeoTiffInput.scala
- s3/src/main/scala/geotrellis/spark/io/s3/geotiff/S3GeoTiffLayerReader.scala
- s3/src/main/scala/geotrellis/spark/io/s3/geotiff/S3IMGeoTiffAttributeStore.scala
- s3/src/main/scala/geotrellis/spark/io/s3/geotiff/S3JsonGeoTiffAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/file/geotiff/FileGeoTiffLayerReader.scala
- spark/src/main/scala/geotrellis/spark/io/file/geotiff/FileIMGeoTiffAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/file/geotiff/FileJsonGeoTiffAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/geotiff/AttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/geotiff/GeoTiffLayerReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/geotiff/GeoTiffMetadata.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/geotiff/GeoTiffMetadataTree.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/geotiff/HadoopGeoTiffInput.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/geotiff/HadoopGeoTiffLayerReader.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/geotiff/HadoopIMGeoTiffAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/geotiff/HadoopJsonGeoTiffAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/geotiff/InMemoryGeoTiffAttributeStore.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/geotiff/JsonGeoTiffAttributeStore.scala
This PR marks all unstructured COG API as `experimental`.
> Unstructured COG API Marked as experimental

- README.md
This PR fixes travis badge branch.
> Fix TravisCI badge branch

- docs/guide/core-concepts.rst
The core concepts guide was somewhat messy, and omitted some important topics.  This PR fills in some of those gaps and makes other changes for style and clarity.
Closes #2679
> [DOCS] Update core concepts guide

- build.sbt
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeoWaveLayerReader.scala
- raster/src/main/scala/geotrellis/raster/CellType.scala
- raster/src/main/scala/geotrellis/raster/GridBounds.scala
- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffSegmentLayout.scala
- raster/src/main/scala/geotrellis/raster/rasterize/Rasterizer.scala
- raster/src/test/scala/geotrellis/raster/CellTypeSpec.scala
- raster/src/test/scala/geotrellis/raster/GridBoundsSpec.scala
- spark/src/main/scala/geotrellis/spark/io/AttributeStore.scala
- spark/src/test/scala/geotrellis/spark/resample/ZoomResampleSpec.scala
Cleanup deprecations and minor changes.
> Fix 2.0 deprecations

- build.sbt
- doc-examples/src/main/scala/geotrellis/doc/examples/spark/PipelineSparkExamples.scala
- docs/guide/etl.rst
- docs/guide/pipeline.rst
> [DOCS] Add pipeline docs and examples

- project/build.properties
- sbt
This PR updates SBT up to 1.2.0
> Update SBT up to 1.2.0

- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiff.scala
> Expose getClosestOverview into public

- raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffOptions.scala
Closes https://github.com/locationtech/geotrellis/issues/2806
> Make Tiled a default GeoTiffOptions storageMethod

- vector/src/main/scala/geotrellis/vector/io/json/FeatureFormats.scala
- vector/src/main/scala/geotrellis/vector/io/json/GeometryFormats.scala
- vector/src/main/scala/geotrellis/vector/io/json/JsonFeatureCollection.scala
- vector/src/main/scala/geotrellis/vector/io/json/JsonFeatureCollectionMap.scala
- vector/src/test/scala/spec/geotrellis/vector/io/json/FeatureFormatsSpec.scala
- vector/src/test/scala/spec/geotrellis/vector/io/json/GeoJsonSpec.scala
- vector/src/test/scala/spec/geotrellis/vector/io/json/JsonCrsSpec.scala
This PR adds a bbox field into all Features Json Writers
Closes https://github.com/locationtech/geotrellis/issues/2809
> Add bbox field into Features JsonWriters

- .travis/hbase-install.sh
This PR fixes failing Travis CI
> Update HBase URIs and version

- .sbtopts
- .travis.yml
- .travis/build-and-test-set-1.sh
- .travis/build-and-test-set-2.sh
- .travis/build-and-test-set-3.sh
- .travis/build-set-1.sh
- .travis/build-set-2.sh
- .travis/build-set-3.sh
- project/build.properties
- sbt
- spark-testkit/src/main/scala/geotrellis/spark/testkit/TestEnvironment.scala
This PR uses a `local[2]` mode for all tests.
Fixes https://github.com/locationtech/geotrellis/issues/2820
> Use a local[2] mode inside TestEnvironment trait

- project/Dependencies.scala
- project/Version.scala
This PR downgrades PR down to 0.13
Closes https://github.com/locationtech/geotrellis/issues/2832
> Downgrade Spire version

- .travis.yml
- .travis/before-script.sh
It turned out that https://github.com/locationtech/geotrellis/pull/2847 was not enough. It's the second round of the TravisCI war.
> This PR is for experiments with TravisCI #2

- raster/src/main/scala/geotrellis/raster/histogram/FastMapHistogram.scala
- raster/src/main/scala/geotrellis/raster/histogram/StreamingHistogram.scala
Fixes: https://github.com/locationtech/geotrellis/issues/2845
> Make histogram.merge methods more specific

- .travis/hbase-install.sh
- accumulo/src/main/scala/geotrellis/spark/io/accumulo/AccumuloLayerCopier.scala
- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraLayerCopier.scala
- hbase/src/main/scala/geotrellis/spark/io/hbase/HBaseLayerCopier.scala
- project/Settings.scala
- spark/src/main/scala/geotrellis/spark/TileLayerMetadata.scala
- spark/src/main/scala/geotrellis/spark/io/GenericLayerCopier.scala
> Fix {Backend}LayerCopy exception handling

- docs/CHANGELOG.rst
> Add v2.2.0 changelog [skip ci]

- .travis/hbase-install.sh
Link to HBase 2.1.2 had been suspended.
> Bump HBase version up to 2.1.3

- .travis/hbase-install.sh
- docs/architecture/adrs.rst
- docs/index.rst
This PR fixes failing travis builds.
> Bump HBase version up

- cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraAttributeStore.scala
Closes https://github.com/locationtech/geotrellis/issues/2900
@ALPSMAC attention is required, since this PR changes the AttributeStore table.
Actually this can not be back ported into 2.x branch.
> Fix Cassandra AttributeStore performance issues

- accumulo/src/main/scala/geotrellis/spark/io/accumulo/conf/AccumuloConfig.scala
- cassandra/src/main/scala/geotrellis/spark/io/cassandra/conf/CassandraConfig.scala
- geomesa/src/main/scala/geotrellis/spark/io/geomesa/conf/GeoMesaConfig.scala
- hbase/src/main/scala/geotrellis/spark/io/hbase/conf/HBaseConfig.scala
- project/Dependencies.scala
- s3/src/main/scala/geotrellis/spark/io/s3/conf/S3Config.scala
- spark/src/main/scala/geotrellis/spark/io/file/conf/FileConfig.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/conf/AttributeConfig.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/conf/CamelCaseConfig.scala
- spark/src/main/scala/geotrellis/spark/io/hadoop/conf/HadoopConfig.scala
- vector/src/main/scala/geotrellis/vector/conf/JtsConfig.scala
Updates pureconfig to version 0.10.2
> update pureconfig to version 0.10.2

- geowave/src/main/scala/geotrellis/spark/io/geowave/GeoWaveAttributeStore.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeoWaveFeatureRDDReader.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeoWaveFeatureRDDWriter.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeoWaveLayerReader.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeoWaveLayerWriter.scala
- geowave/src/test/scala/geotrellis/spark/io/geowave/GeoWaveSpatialSpec.scala
This PR updates the imports of the `geowave` package so that they reflect the new split API.
This PR is based on another, open PR: #2944 
This PR addresses the geowave update in #2934
> Geowave Spark Split

- .locationtech/deploy-211.sh
- .locationtech/deploy-212.sh
- .travis/build-and-test-set-1.sh
- .travis/build-set-1.sh
- scripts/buildall.sh
- scripts/publish-local.sh
- scripts/publish-m2.sh
- scripts/publish-snapshot.sh
This PR fixes all publish scripts.
> Fix test, release and publish scripts

- .travis/hbase-install.sh
This PR updates the downloaded HBase version from 2.1.4 to 2.1.5
> Bump HBase Version

- geowave/src/main/scala/geotrellis/spark/io/geowave/GeoWaveAttributeStore.scala
- geowave/src/main/scala/geotrellis/spark/io/geowave/GeoWaveLayerWriter.scala
- geowave/src/test/scala/geotrellis/spark/io/geowave/GeoWaveSpatialSpec.scala
- hbase-spark/src/main/resources/META-INF/services/geotrellis.layers.AttributeStoreProvider
- hbase-spark/src/main/resources/META-INF/services/geotrellis.layers.CollectionLayerReaderProvider
- hbase-spark/src/main/resources/META-INF/services/geotrellis.layers.LayerReaderProvider
- hbase-spark/src/main/resources/META-INF/services/geotrellis.layers.LayerWriterProvider
- hbase-spark/src/main/resources/META-INF/services/geotrellis.layers.ValueReaderProvider
- hbase-spark/src/main/resources/META-INF/services/geotrellis.spark.io.LayerReaderProvider
- hbase-spark/src/main/resources/META-INF/services/geotrellis.spark.io.LayerWriterProvider
- hbase-store/src/main/scala/geotrellis/store/hbase/HBaseAttributeStore.scala
- layers/src/main/scala/geotrellis/layers/hadoop/HadoopAttributeStore.scala
This PR fixes various problems that were introduced during the spark split that are causing Travis to fail.
This should probably be merged before: #2969
> Misc Fixes

- .travis/hbase-install.sh
> Bump travis hbase to 2.1.5

- project/Settings.scala
- project/Version.scala
Temporary exclude GeoWave subproject from tests.
Connects https://github.com/locationtech/geotrellis/issues/2999
> Update GeoWave resolvers

- .locationtech/deploy-211.sh
- .locationtech/deploy-212.sh
- layers/src/main/scala/geotrellis/layers/hadoop/package.scala
Fix locationtech deployment scripts, remove un unused code
> Fix locationtech deployment scripts, remove un unused code

- raster/src/test/scala/geotrellis/raster/GridExtentSpec.scala
GridExtent is woefully undertested.  This PR adds some needed tests.
Closes #2989
> Add tests for GridExtent

- raster/src/main/scala/geotrellis/raster/GridExtent.scala
- raster/src/test/scala/geotrellis/raster/GridExtentSpec.scala
#Overview
A commit went missing from #3019.  This is that.
> Minor additions to GridExtent tests

- .travis/hbase-install.sh
- raster/src/main/scala/geotrellis/raster/RasterExtent.scala
- raster/src/test/scala/geotrellis/raster/RasterExtentSpec.scala
Backport bug fix on 3.x
N/A
N/A
N/A
Closes #3047
> In 2.x, fix map{X|Y}ToGrid function behavior that could give a bit incorrect results

- .travis/build-and-test-set-1.sh
- .travis/build-and-test-set-2.sh
- .travis/build-set-1.sh
- .travis/build-set-2.sh
This PR should prevent travis timeouts.
> Move GDAL tests into GDAL test set 1

- s3-spark/src/main/scala/geotrellis/spark/store/s3/S3SparkLayerProvider.scala
- s3/src/main/scala/geotrellis/store/s3/S3CollectionLayerProvider.scala
> Make S3SparkLayerProvider Serializable

- .locationtech/deploy-211.sh
- .locationtech/deploy-212.sh
- build.sbt
- publish/Dockerfile
- publish/Makefile
- publish/README.md
- publish/global.sbt
- publish/publish-to-sonatype-211.sh
- publish/publish-to-sonatype-212.sh
- publish/publish-to-sonatype.sh
- scripts/nginxTestHttp.sh
- scripts/publish-snapshot.sh
This PR updates publish scripts.
> Update sonatype publish scripts 

- project/build.properties
This PR updates SBT up to 1.3.6
> Bump SBT version up

- project/Settings.scala
This PR removes dead boundless repositories with two fresh osgo repositories
> Update dependencies resolvers

- project/Dependencies.scala
- project/Settings.scala
The old osgeo repo is dead, we need to fix an explicit reference to jai_core as well.
> Fix jai_core uri

- .github/PULL_REQUEST_TEMPLATE.md
> Update PULL_REQUEST_TEMPLATE.md checklist

- docs/guide/vectors.rst
> Fix a typo in vectors.rst

- docs/architecture/proj4-implementation.rst
one line doc fix for broken link
> fix broken link to usgs hosted paper

- docs/guide/spark.rst
> Fix spelling

- project/Settings.scala
This PR fixes Jenkins SNAPSHOTS publish process
> Add the new JenkinsCI credentials location

- project/Dependencies.scala
- project/Settings.scala
This PR removes unused HBase deps
> Cleanup HBase dependencies

- project/Dependencies.scala
- project/Settings.scala
This PR cleans up GeoTools build.
> Cleanup GeoTools deps

- .circleci/config.yml
- build.sbt
- project/Settings.scala
- project/build.properties
- project/plugins.sbt
- sbt
This PR upgrades GT Scala version up to 2.12.14 and SBT up to 1.5.3
> Bump Scala version and SBT up

- project/Dependencies.scala
This PR updates proj4j version up.
> Bump proj4j version up

- spark-testkit/src/main/scala/geotrellis/spark/testkit/TestEnvironment.scala
This PR fixes a forward reference definition in TestEnvironment
> Fix forward reference in TestEnvironment.scala

- .circleci/config.yml
- build.sbt
- project/Dependencies.scala
This PR is required for the RasterFrames compat with GeoMesa 3.2
> Bump JTS up to 1.17.0

- raster/src/main/scala/geotrellis/raster/Dimensions.scala
This PR adds more constructors into the Dimensions companion object
> Add Dimensions apply overloads

- docs/guide/ingests.rst
Added some information as per discussion in a gitter thread
Updated the documentation of raster ingestion.
Closes #XXX
> Update raster ingestion documentation

- CHANGELOG.md
- project/Dependencies.scala
This PR does not address https://github.com/locationtech/geotrellis/issues/3381
> Accumulo update up to 1.10.x

- spark/src/main/scala/geotrellis/spark/regrid/Regrid.scala
Created this one to try out the tests behavior of the https://github.com/locationtech/geotrellis/pull/3517
Closes https://github.com/locationtech/geotrellis/pull/3517
> Regrid: force crop to avoid going out of memory

- .github/workflows/ci.yml
- build.sbt
- project/Dependencies.scala
- project/Settings.scala
- project/build.properties
- project/plugins.sbt
- sbt
This is a pre-release dependencies update!
Could not use the most up to date SBT, see https://github.com/sbt/sbt/issues/7463
[List of CQs](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/?sort=created_date&state=opened&author_username=gpomadchin&first_page_size=20) (link should be empty in case of all CQs approved)
> Dependencies update

- .github/docker-compose.yml
- .github/workflows/ci.yml
- CHANGELOG.md
- geotools/src/main/scala/geotrellis/geotools/FeatureToSimpleFeatureMethods.scala
- geotools/src/main/scala/geotrellis/geotools/GeometryToSimpleFeature.scala
- geotools/src/main/scala/geotrellis/geotools/GeometryToSimpleFeatureMethods.scala
- geotools/src/main/scala/geotrellis/geotools/GridCoverage2DConverters.scala
- geotools/src/main/scala/geotrellis/geotools/SimpleFeatureToFeature.scala
- geotools/src/main/scala/geotrellis/geotools/SimpleFeatureToFeatureMethods.scala
- geotools/src/main/scala/geotrellis/geotools/SimpleFeatureToGeometryMethods.scala
- geotools/src/main/scala/geotrellis/geotools/package.scala
- project/Dependencies.scala
- project/Settings.scala
- project/build.properties
- shapefile/src/main/scala/geotrellis/shapefile/ShapeFileReader.scala
This PR updates GeoTools version up to the most recent snapshot. 
Closes #3515
Closes #3470
Closes #3522
Thx @jodygarnett for pointing out that there is a new fresh GeoTools version around!
Not going to be merged for now, we're waiting for the release!
> Bump GeoTools version up to 31.0

- .github/workflows/ci.yml
This PR makes use of the SBT action.
> Update CI to use SBT action

- CHANGELOG.md
- spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
- spark/src/test/scala/geotrellis/spark/reproject/TileRDDReprojectSpec.scala
A cleaned up version of https://github.com/locationtech/geotrellis/pull/3560 
Closes https://github.com/locationtech/geotrellis/issues/3559
Closes https://github.com/locationtech/geotrellis/pull/3560
All credits to @jdries!
> Avoid GeoAttrsError by using more robust target extent calculation

- CHANGELOG.md
- raster/src/main/scala/geotrellis/raster/mapalgebra/focal/Kernel.scala
- raster/src/test/scala/geotrellis/raster/mapalgebra/focal/KernelSpec.scala
Add some new kernel for focal calculate.
> Add new kernels

- .github/workflows/ci.yml
- project/build.properties
- project/plugins.sbt
This PR updates SBT and the release plugin to align, that's needed due to the Maven Central migration.
> SBT & Maven Central release update
